// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: api/rtp/v1/rtp.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SelectSpinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`                             //商户
	PlayerId      string                 `protobuf:"bytes,2,opt,name=playerId,proto3" json:"playerId,omitempty"`                       //账号id
	GameBrand     string                 `protobuf:"bytes,3,opt,name=gameBrand,proto3" json:"gameBrand,omitempty"`                     //游戏厂商
	GameId        string                 `protobuf:"bytes,4,opt,name=gameId,proto3" json:"gameId,omitempty"`                           //游戏id
	Bet           float64                `protobuf:"fixed64,5,opt,name=bet,proto3" json:"bet,omitempty"`                               //下注
	RoundModel    string                 `protobuf:"bytes,6,opt,name=round_model,json=roundModel,proto3" json:"round_model,omitempty"` // 模式: DEFAULT,EXTRA,BUY
	Currency      string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	Mock          string                 `protobuf:"bytes,8,opt,name=mock,proto3" json:"mock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectSpinRequest) Reset() {
	*x = SelectSpinRequest{}
	mi := &file_api_rtp_v1_rtp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectSpinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectSpinRequest) ProtoMessage() {}

func (x *SelectSpinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtp_v1_rtp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectSpinRequest.ProtoReflect.Descriptor instead.
func (*SelectSpinRequest) Descriptor() ([]byte, []int) {
	return file_api_rtp_v1_rtp_proto_rawDescGZIP(), []int{0}
}

func (x *SelectSpinRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *SelectSpinRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *SelectSpinRequest) GetGameBrand() string {
	if x != nil {
		return x.GameBrand
	}
	return ""
}

func (x *SelectSpinRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *SelectSpinRequest) GetBet() float64 {
	if x != nil {
		return x.Bet
	}
	return 0
}

func (x *SelectSpinRequest) GetRoundModel() string {
	if x != nil {
		return x.RoundModel
	}
	return ""
}

func (x *SelectSpinRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *SelectSpinRequest) GetMock() string {
	if x != nil {
		return x.Mock
	}
	return ""
}

type SelectSpinReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SpinId         int64                  `protobuf:"varint,1,opt,name=spinId,proto3" json:"spinId,omitempty"`      //spin样本id
	GameBrand      string                 `protobuf:"bytes,2,opt,name=gameBrand,proto3" json:"gameBrand,omitempty"` //游戏厂商
	GameId         string                 `protobuf:"bytes,3,opt,name=gameId,proto3" json:"gameId,omitempty"`       //游戏id
	Bet            float64                `protobuf:"fixed64,4,opt,name=bet,proto3" json:"bet,omitempty"`           //下注
	OriginBet      float64                `protobuf:"fixed64,5,opt,name=originBet,proto3" json:"originBet,omitempty"`
	OriginTotalWin float64                `protobuf:"fixed64,6,opt,name=originTotalWin,proto3" json:"originTotalWin,omitempty"`
	Data           []byte                 `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`                               // spin数据
	RoundModel     string                 `protobuf:"bytes,8,opt,name=round_model,json=roundModel,proto3" json:"round_model,omitempty"` // 模式: DEFAULT,EXTRA,BUY
	TableName      string                 `protobuf:"bytes,9,opt,name=tableName,proto3" json:"tableName,omitempty"`                     //本次表名
	Rtp            string                 `protobuf:"bytes,10,opt,name=rtp,proto3" json:"rtp,omitempty"`                                // 本次rtp档位
	Rate           float64                `protobuf:"fixed64,11,opt,name=rate,proto3" json:"rate,omitempty"`                            // 本次spin的概率
	Compress       int32                  `protobuf:"varint,12,opt,name=compress,proto3" json:"compress,omitempty"`                     // 压缩数据
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SelectSpinReply) Reset() {
	*x = SelectSpinReply{}
	mi := &file_api_rtp_v1_rtp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectSpinReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectSpinReply) ProtoMessage() {}

func (x *SelectSpinReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtp_v1_rtp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectSpinReply.ProtoReflect.Descriptor instead.
func (*SelectSpinReply) Descriptor() ([]byte, []int) {
	return file_api_rtp_v1_rtp_proto_rawDescGZIP(), []int{1}
}

func (x *SelectSpinReply) GetSpinId() int64 {
	if x != nil {
		return x.SpinId
	}
	return 0
}

func (x *SelectSpinReply) GetGameBrand() string {
	if x != nil {
		return x.GameBrand
	}
	return ""
}

func (x *SelectSpinReply) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *SelectSpinReply) GetBet() float64 {
	if x != nil {
		return x.Bet
	}
	return 0
}

func (x *SelectSpinReply) GetOriginBet() float64 {
	if x != nil {
		return x.OriginBet
	}
	return 0
}

func (x *SelectSpinReply) GetOriginTotalWin() float64 {
	if x != nil {
		return x.OriginTotalWin
	}
	return 0
}

func (x *SelectSpinReply) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SelectSpinReply) GetRoundModel() string {
	if x != nil {
		return x.RoundModel
	}
	return ""
}

func (x *SelectSpinReply) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *SelectSpinReply) GetRtp() string {
	if x != nil {
		return x.Rtp
	}
	return ""
}

func (x *SelectSpinReply) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *SelectSpinReply) GetCompress() int32 {
	if x != nil {
		return x.Compress
	}
	return 0
}

type GetPlayerRtpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`         //商户
	PlayerId      string                 `protobuf:"bytes,2,opt,name=playerId,proto3" json:"playerId,omitempty"`   //账号id
	GameBrand     string                 `protobuf:"bytes,3,opt,name=gameBrand,proto3" json:"gameBrand,omitempty"` //游戏厂商
	GameId        string                 `protobuf:"bytes,4,opt,name=gameId,proto3" json:"gameId,omitempty"`       //游戏id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerRtpRequest) Reset() {
	*x = GetPlayerRtpRequest{}
	mi := &file_api_rtp_v1_rtp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerRtpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerRtpRequest) ProtoMessage() {}

func (x *GetPlayerRtpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtp_v1_rtp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerRtpRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerRtpRequest) Descriptor() ([]byte, []int) {
	return file_api_rtp_v1_rtp_proto_rawDescGZIP(), []int{2}
}

func (x *GetPlayerRtpRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GetPlayerRtpRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *GetPlayerRtpRequest) GetGameBrand() string {
	if x != nil {
		return x.GameBrand
	}
	return ""
}

func (x *GetPlayerRtpRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type GetPlayerRtpReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rtp           string                 `protobuf:"bytes,1,opt,name=rtp,proto3" json:"rtp,omitempty"` // 本次rtp档位
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerRtpReply) Reset() {
	*x = GetPlayerRtpReply{}
	mi := &file_api_rtp_v1_rtp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerRtpReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerRtpReply) ProtoMessage() {}

func (x *GetPlayerRtpReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtp_v1_rtp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerRtpReply.ProtoReflect.Descriptor instead.
func (*GetPlayerRtpReply) Descriptor() ([]byte, []int) {
	return file_api_rtp_v1_rtp_proto_rawDescGZIP(), []int{3}
}

func (x *GetPlayerRtpReply) GetRtp() string {
	if x != nil {
		return x.Rtp
	}
	return ""
}

type GetBaccaratRtpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`         //商户
	GameBrand     string                 `protobuf:"bytes,2,opt,name=gameBrand,proto3" json:"gameBrand,omitempty"` //游戏厂商
	GameId        string                 `protobuf:"bytes,3,opt,name=gameId,proto3" json:"gameId,omitempty"`       //游戏id
	RoundId       string                 `protobuf:"bytes,4,opt,name=roundId,proto3" json:"roundId,omitempty"`     // 局id
	Rtp           string                 `protobuf:"bytes,5,opt,name=rtp,proto3" json:"rtp,omitempty"`             // rtp档位
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBaccaratRtpRequest) Reset() {
	*x = GetBaccaratRtpRequest{}
	mi := &file_api_rtp_v1_rtp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBaccaratRtpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBaccaratRtpRequest) ProtoMessage() {}

func (x *GetBaccaratRtpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtp_v1_rtp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBaccaratRtpRequest.ProtoReflect.Descriptor instead.
func (*GetBaccaratRtpRequest) Descriptor() ([]byte, []int) {
	return file_api_rtp_v1_rtp_proto_rawDescGZIP(), []int{4}
}

func (x *GetBaccaratRtpRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GetBaccaratRtpRequest) GetGameBrand() string {
	if x != nil {
		return x.GameBrand
	}
	return ""
}

func (x *GetBaccaratRtpRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GetBaccaratRtpRequest) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *GetBaccaratRtpRequest) GetRtp() string {
	if x != nil {
		return x.Rtp
	}
	return ""
}

type GetBaccaratRtpReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rtp           string                 `protobuf:"bytes,1,opt,name=rtp,proto3" json:"rtp,omitempty"`       // rtp档位
	Rate1         float64                `protobuf:"fixed64,2,opt,name=rate1,proto3" json:"rate1,omitempty"` // 1倍爆率
	Rate2         float64                `protobuf:"fixed64,3,opt,name=rate2,proto3" json:"rate2,omitempty"` // >=2倍爆率
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBaccaratRtpReply) Reset() {
	*x = GetBaccaratRtpReply{}
	mi := &file_api_rtp_v1_rtp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBaccaratRtpReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBaccaratRtpReply) ProtoMessage() {}

func (x *GetBaccaratRtpReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtp_v1_rtp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBaccaratRtpReply.ProtoReflect.Descriptor instead.
func (*GetBaccaratRtpReply) Descriptor() ([]byte, []int) {
	return file_api_rtp_v1_rtp_proto_rawDescGZIP(), []int{5}
}

func (x *GetBaccaratRtpReply) GetRtp() string {
	if x != nil {
		return x.Rtp
	}
	return ""
}

func (x *GetBaccaratRtpReply) GetRate1() float64 {
	if x != nil {
		return x.Rate1
	}
	return 0
}

func (x *GetBaccaratRtpReply) GetRate2() float64 {
	if x != nil {
		return x.Rate2
	}
	return 0
}

type SettleBaccaratRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AppId            string                 `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`                         //商户
	GameBrand        string                 `protobuf:"bytes,2,opt,name=gameBrand,proto3" json:"gameBrand,omitempty"`                 //游戏厂商
	GameId           string                 `protobuf:"bytes,3,opt,name=gameId,proto3" json:"gameId,omitempty"`                       //游戏id
	RoundBetTotal    float64                `protobuf:"fixed64,4,opt,name=roundBetTotal,proto3" json:"roundBetTotal,omitempty"`       //本局下注总额
	RoundProfitTotal float64                `protobuf:"fixed64,5,opt,name=roundProfitTotal,proto3" json:"roundProfitTotal,omitempty"` //本局平台本次盈利
	RoundId          string                 `protobuf:"bytes,6,opt,name=roundId,proto3" json:"roundId,omitempty"`                     // 局id
	Rtp              string                 `protobuf:"bytes,7,opt,name=rtp,proto3" json:"rtp,omitempty"`                             // rtp档位
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SettleBaccaratRequest) Reset() {
	*x = SettleBaccaratRequest{}
	mi := &file_api_rtp_v1_rtp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleBaccaratRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleBaccaratRequest) ProtoMessage() {}

func (x *SettleBaccaratRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtp_v1_rtp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleBaccaratRequest.ProtoReflect.Descriptor instead.
func (*SettleBaccaratRequest) Descriptor() ([]byte, []int) {
	return file_api_rtp_v1_rtp_proto_rawDescGZIP(), []int{6}
}

func (x *SettleBaccaratRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *SettleBaccaratRequest) GetGameBrand() string {
	if x != nil {
		return x.GameBrand
	}
	return ""
}

func (x *SettleBaccaratRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *SettleBaccaratRequest) GetRoundBetTotal() float64 {
	if x != nil {
		return x.RoundBetTotal
	}
	return 0
}

func (x *SettleBaccaratRequest) GetRoundProfitTotal() float64 {
	if x != nil {
		return x.RoundProfitTotal
	}
	return 0
}

func (x *SettleBaccaratRequest) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *SettleBaccaratRequest) GetRtp() string {
	if x != nil {
		return x.Rtp
	}
	return ""
}

type SettleBaccaratReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleBaccaratReply) Reset() {
	*x = SettleBaccaratReply{}
	mi := &file_api_rtp_v1_rtp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleBaccaratReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleBaccaratReply) ProtoMessage() {}

func (x *SettleBaccaratReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtp_v1_rtp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleBaccaratReply.ProtoReflect.Descriptor instead.
func (*SettleBaccaratReply) Descriptor() ([]byte, []int) {
	return file_api_rtp_v1_rtp_proto_rawDescGZIP(), []int{7}
}

type ResetBaccaratRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`         //商户
	GameBrand     string                 `protobuf:"bytes,2,opt,name=gameBrand,proto3" json:"gameBrand,omitempty"` //游戏厂商
	GameId        string                 `protobuf:"bytes,3,opt,name=gameId,proto3" json:"gameId,omitempty"`       //游戏id
	Rtp           string                 `protobuf:"bytes,4,opt,name=rtp,proto3" json:"rtp,omitempty"`             // rtp档位
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetBaccaratRequest) Reset() {
	*x = ResetBaccaratRequest{}
	mi := &file_api_rtp_v1_rtp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetBaccaratRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetBaccaratRequest) ProtoMessage() {}

func (x *ResetBaccaratRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtp_v1_rtp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetBaccaratRequest.ProtoReflect.Descriptor instead.
func (*ResetBaccaratRequest) Descriptor() ([]byte, []int) {
	return file_api_rtp_v1_rtp_proto_rawDescGZIP(), []int{8}
}

func (x *ResetBaccaratRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ResetBaccaratRequest) GetGameBrand() string {
	if x != nil {
		return x.GameBrand
	}
	return ""
}

func (x *ResetBaccaratRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *ResetBaccaratRequest) GetRtp() string {
	if x != nil {
		return x.Rtp
	}
	return ""
}

type ResetBaccaratReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetBaccaratReply) Reset() {
	*x = ResetBaccaratReply{}
	mi := &file_api_rtp_v1_rtp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetBaccaratReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetBaccaratReply) ProtoMessage() {}

func (x *ResetBaccaratReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtp_v1_rtp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetBaccaratReply.ProtoReflect.Descriptor instead.
func (*ResetBaccaratReply) Descriptor() ([]byte, []int) {
	return file_api_rtp_v1_rtp_proto_rawDescGZIP(), []int{9}
}

var File_api_rtp_v1_rtp_proto protoreflect.FileDescriptor

const file_api_rtp_v1_rtp_proto_rawDesc = "" +
	"\n" +
	"\x14api/rtp/v1/rtp.proto\x12\x06rtp.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xde\x01\n" +
	"\x11SelectSpinRequest\x12\x14\n" +
	"\x05appId\x18\x01 \x01(\tR\x05appId\x12\x1a\n" +
	"\bplayerId\x18\x02 \x01(\tR\bplayerId\x12\x1c\n" +
	"\tgameBrand\x18\x03 \x01(\tR\tgameBrand\x12\x16\n" +
	"\x06gameId\x18\x04 \x01(\tR\x06gameId\x12\x10\n" +
	"\x03bet\x18\x05 \x01(\x01R\x03bet\x12\x1f\n" +
	"\vround_model\x18\x06 \x01(\tR\n" +
	"roundModel\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x12\x12\n" +
	"\x04mock\x18\b \x01(\tR\x04mock\"\xcc\x02\n" +
	"\x0fSelectSpinReply\x12\x16\n" +
	"\x06spinId\x18\x01 \x01(\x03R\x06spinId\x12\x1c\n" +
	"\tgameBrand\x18\x02 \x01(\tR\tgameBrand\x12\x16\n" +
	"\x06gameId\x18\x03 \x01(\tR\x06gameId\x12\x10\n" +
	"\x03bet\x18\x04 \x01(\x01R\x03bet\x12\x1c\n" +
	"\toriginBet\x18\x05 \x01(\x01R\toriginBet\x12&\n" +
	"\x0eoriginTotalWin\x18\x06 \x01(\x01R\x0eoriginTotalWin\x12\x12\n" +
	"\x04data\x18\a \x01(\fR\x04data\x12\x1f\n" +
	"\vround_model\x18\b \x01(\tR\n" +
	"roundModel\x12\x1c\n" +
	"\ttableName\x18\t \x01(\tR\ttableName\x12\x10\n" +
	"\x03rtp\x18\n" +
	" \x01(\tR\x03rtp\x12\x12\n" +
	"\x04rate\x18\v \x01(\x01R\x04rate\x12\x1a\n" +
	"\bcompress\x18\f \x01(\x05R\bcompress\"}\n" +
	"\x13GetPlayerRtpRequest\x12\x14\n" +
	"\x05appId\x18\x01 \x01(\tR\x05appId\x12\x1a\n" +
	"\bplayerId\x18\x02 \x01(\tR\bplayerId\x12\x1c\n" +
	"\tgameBrand\x18\x03 \x01(\tR\tgameBrand\x12\x16\n" +
	"\x06gameId\x18\x04 \x01(\tR\x06gameId\"%\n" +
	"\x11GetPlayerRtpReply\x12\x10\n" +
	"\x03rtp\x18\x01 \x01(\tR\x03rtp\"\x8f\x01\n" +
	"\x15GetBaccaratRtpRequest\x12\x14\n" +
	"\x05appId\x18\x01 \x01(\tR\x05appId\x12\x1c\n" +
	"\tgameBrand\x18\x02 \x01(\tR\tgameBrand\x12\x16\n" +
	"\x06gameId\x18\x03 \x01(\tR\x06gameId\x12\x18\n" +
	"\aroundId\x18\x04 \x01(\tR\aroundId\x12\x10\n" +
	"\x03rtp\x18\x05 \x01(\tR\x03rtp\"S\n" +
	"\x13GetBaccaratRtpReply\x12\x10\n" +
	"\x03rtp\x18\x01 \x01(\tR\x03rtp\x12\x14\n" +
	"\x05rate1\x18\x02 \x01(\x01R\x05rate1\x12\x14\n" +
	"\x05rate2\x18\x03 \x01(\x01R\x05rate2\"\xe1\x01\n" +
	"\x15SettleBaccaratRequest\x12\x14\n" +
	"\x05appId\x18\x01 \x01(\tR\x05appId\x12\x1c\n" +
	"\tgameBrand\x18\x02 \x01(\tR\tgameBrand\x12\x16\n" +
	"\x06gameId\x18\x03 \x01(\tR\x06gameId\x12$\n" +
	"\rroundBetTotal\x18\x04 \x01(\x01R\rroundBetTotal\x12*\n" +
	"\x10roundProfitTotal\x18\x05 \x01(\x01R\x10roundProfitTotal\x12\x18\n" +
	"\aroundId\x18\x06 \x01(\tR\aroundId\x12\x10\n" +
	"\x03rtp\x18\a \x01(\tR\x03rtp\"\x15\n" +
	"\x13SettleBaccaratReply\"t\n" +
	"\x14ResetBaccaratRequest\x12\x14\n" +
	"\x05appId\x18\x01 \x01(\tR\x05appId\x12\x1c\n" +
	"\tgameBrand\x18\x02 \x01(\tR\tgameBrand\x12\x16\n" +
	"\x06gameId\x18\x03 \x01(\tR\x06gameId\x12\x10\n" +
	"\x03rtp\x18\x04 \x01(\tR\x03rtp\"\x14\n" +
	"\x12ResetBaccaratReply2\xf9\x02\n" +
	"\x06RtpApi\x12@\n" +
	"\n" +
	"SelectSpin\x12\x19.rtp.v1.SelectSpinRequest\x1a\x17.rtp.v1.SelectSpinReply\x12F\n" +
	"\fGetPlayerRtp\x12\x1b.rtp.v1.GetPlayerRtpRequest\x1a\x19.rtp.v1.GetPlayerRtpReply\x12L\n" +
	"\x0eGetBaccaratRtp\x12\x1d.rtp.v1.GetBaccaratRtpRequest\x1a\x1b.rtp.v1.GetBaccaratRtpReply\x12L\n" +
	"\x0eSettleBaccarat\x12\x1d.rtp.v1.SettleBaccaratRequest\x1a\x1b.rtp.v1.SettleBaccaratReply\x12I\n" +
	"\rResetBaccarat\x12\x1c.rtp.v1.ResetBaccaratRequest\x1a\x1a.rtp.v1.ResetBaccaratReplyBR\n" +
	"\x15dev.kratos.api.rtp.v1B\n" +
	"RtpProtoV1P\x01Z+cn.qingdou.server/game_common/api/rtp/v1;v1b\x06proto3"

var (
	file_api_rtp_v1_rtp_proto_rawDescOnce sync.Once
	file_api_rtp_v1_rtp_proto_rawDescData []byte
)

func file_api_rtp_v1_rtp_proto_rawDescGZIP() []byte {
	file_api_rtp_v1_rtp_proto_rawDescOnce.Do(func() {
		file_api_rtp_v1_rtp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_rtp_v1_rtp_proto_rawDesc), len(file_api_rtp_v1_rtp_proto_rawDesc)))
	})
	return file_api_rtp_v1_rtp_proto_rawDescData
}

var file_api_rtp_v1_rtp_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_rtp_v1_rtp_proto_goTypes = []any{
	(*SelectSpinRequest)(nil),     // 0: rtp.v1.SelectSpinRequest
	(*SelectSpinReply)(nil),       // 1: rtp.v1.SelectSpinReply
	(*GetPlayerRtpRequest)(nil),   // 2: rtp.v1.GetPlayerRtpRequest
	(*GetPlayerRtpReply)(nil),     // 3: rtp.v1.GetPlayerRtpReply
	(*GetBaccaratRtpRequest)(nil), // 4: rtp.v1.GetBaccaratRtpRequest
	(*GetBaccaratRtpReply)(nil),   // 5: rtp.v1.GetBaccaratRtpReply
	(*SettleBaccaratRequest)(nil), // 6: rtp.v1.SettleBaccaratRequest
	(*SettleBaccaratReply)(nil),   // 7: rtp.v1.SettleBaccaratReply
	(*ResetBaccaratRequest)(nil),  // 8: rtp.v1.ResetBaccaratRequest
	(*ResetBaccaratReply)(nil),    // 9: rtp.v1.ResetBaccaratReply
}
var file_api_rtp_v1_rtp_proto_depIdxs = []int32{
	0, // 0: rtp.v1.RtpApi.SelectSpin:input_type -> rtp.v1.SelectSpinRequest
	2, // 1: rtp.v1.RtpApi.GetPlayerRtp:input_type -> rtp.v1.GetPlayerRtpRequest
	4, // 2: rtp.v1.RtpApi.GetBaccaratRtp:input_type -> rtp.v1.GetBaccaratRtpRequest
	6, // 3: rtp.v1.RtpApi.SettleBaccarat:input_type -> rtp.v1.SettleBaccaratRequest
	8, // 4: rtp.v1.RtpApi.ResetBaccarat:input_type -> rtp.v1.ResetBaccaratRequest
	1, // 5: rtp.v1.RtpApi.SelectSpin:output_type -> rtp.v1.SelectSpinReply
	3, // 6: rtp.v1.RtpApi.GetPlayerRtp:output_type -> rtp.v1.GetPlayerRtpReply
	5, // 7: rtp.v1.RtpApi.GetBaccaratRtp:output_type -> rtp.v1.GetBaccaratRtpReply
	7, // 8: rtp.v1.RtpApi.SettleBaccarat:output_type -> rtp.v1.SettleBaccaratReply
	9, // 9: rtp.v1.RtpApi.ResetBaccarat:output_type -> rtp.v1.ResetBaccaratReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_rtp_v1_rtp_proto_init() }
func file_api_rtp_v1_rtp_proto_init() {
	if File_api_rtp_v1_rtp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_rtp_v1_rtp_proto_rawDesc), len(file_api_rtp_v1_rtp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_rtp_v1_rtp_proto_goTypes,
		DependencyIndexes: file_api_rtp_v1_rtp_proto_depIdxs,
		MessageInfos:      file_api_rtp_v1_rtp_proto_msgTypes,
	}.Build()
	File_api_rtp_v1_rtp_proto = out.File
	file_api_rtp_v1_rtp_proto_goTypes = nil
	file_api_rtp_v1_rtp_proto_depIdxs = nil
}
