// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/rtp/v1/rtp.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RtpApi_SelectSpin_FullMethodName     = "/rtp.v1.RtpApi/SelectSpin"
	RtpApi_GetPlayerRtp_FullMethodName   = "/rtp.v1.RtpApi/GetPlayerRtp"
	RtpApi_GetBaccaratRtp_FullMethodName = "/rtp.v1.RtpApi/GetBaccaratRtp"
	RtpApi_SettleBaccarat_FullMethodName = "/rtp.v1.RtpApi/SettleBaccarat"
	RtpApi_ResetBaccarat_FullMethodName  = "/rtp.v1.RtpApi/ResetBaccarat"
)

// RtpApiClient is the client API for RtpApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RtpApiClient interface {
	// 获取spin
	SelectSpin(ctx context.Context, in *SelectSpinRequest, opts ...grpc.CallOption) (*SelectSpinReply, error)
	// 获取玩家当前RTP(优先玩家->再按游戏->再按商户)
	GetPlayerRtp(ctx context.Context, in *GetPlayerRtpRequest, opts ...grpc.CallOption) (*GetPlayerRtpReply, error)
	// 获取baccarat rtp
	GetBaccaratRtp(ctx context.Context, in *GetBaccaratRtpRequest, opts ...grpc.CallOption) (*GetBaccaratRtpReply, error)
	// baccarat结算
	SettleBaccarat(ctx context.Context, in *SettleBaccaratRequest, opts ...grpc.CallOption) (*SettleBaccaratReply, error)
	// baccarat重置库存（仅运营层面使用）
	ResetBaccarat(ctx context.Context, in *ResetBaccaratRequest, opts ...grpc.CallOption) (*ResetBaccaratReply, error)
}

type rtpApiClient struct {
	cc grpc.ClientConnInterface
}

func NewRtpApiClient(cc grpc.ClientConnInterface) RtpApiClient {
	return &rtpApiClient{cc}
}

func (c *rtpApiClient) SelectSpin(ctx context.Context, in *SelectSpinRequest, opts ...grpc.CallOption) (*SelectSpinReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelectSpinReply)
	err := c.cc.Invoke(ctx, RtpApi_SelectSpin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rtpApiClient) GetPlayerRtp(ctx context.Context, in *GetPlayerRtpRequest, opts ...grpc.CallOption) (*GetPlayerRtpReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlayerRtpReply)
	err := c.cc.Invoke(ctx, RtpApi_GetPlayerRtp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rtpApiClient) GetBaccaratRtp(ctx context.Context, in *GetBaccaratRtpRequest, opts ...grpc.CallOption) (*GetBaccaratRtpReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBaccaratRtpReply)
	err := c.cc.Invoke(ctx, RtpApi_GetBaccaratRtp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rtpApiClient) SettleBaccarat(ctx context.Context, in *SettleBaccaratRequest, opts ...grpc.CallOption) (*SettleBaccaratReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettleBaccaratReply)
	err := c.cc.Invoke(ctx, RtpApi_SettleBaccarat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rtpApiClient) ResetBaccarat(ctx context.Context, in *ResetBaccaratRequest, opts ...grpc.CallOption) (*ResetBaccaratReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetBaccaratReply)
	err := c.cc.Invoke(ctx, RtpApi_ResetBaccarat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RtpApiServer is the server API for RtpApi service.
// All implementations must embed UnimplementedRtpApiServer
// for forward compatibility.
type RtpApiServer interface {
	// 获取spin
	SelectSpin(context.Context, *SelectSpinRequest) (*SelectSpinReply, error)
	// 获取玩家当前RTP(优先玩家->再按游戏->再按商户)
	GetPlayerRtp(context.Context, *GetPlayerRtpRequest) (*GetPlayerRtpReply, error)
	// 获取baccarat rtp
	GetBaccaratRtp(context.Context, *GetBaccaratRtpRequest) (*GetBaccaratRtpReply, error)
	// baccarat结算
	SettleBaccarat(context.Context, *SettleBaccaratRequest) (*SettleBaccaratReply, error)
	// baccarat重置库存（仅运营层面使用）
	ResetBaccarat(context.Context, *ResetBaccaratRequest) (*ResetBaccaratReply, error)
	mustEmbedUnimplementedRtpApiServer()
}

// UnimplementedRtpApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRtpApiServer struct{}

func (UnimplementedRtpApiServer) SelectSpin(context.Context, *SelectSpinRequest) (*SelectSpinReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectSpin not implemented")
}
func (UnimplementedRtpApiServer) GetPlayerRtp(context.Context, *GetPlayerRtpRequest) (*GetPlayerRtpReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayerRtp not implemented")
}
func (UnimplementedRtpApiServer) GetBaccaratRtp(context.Context, *GetBaccaratRtpRequest) (*GetBaccaratRtpReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBaccaratRtp not implemented")
}
func (UnimplementedRtpApiServer) SettleBaccarat(context.Context, *SettleBaccaratRequest) (*SettleBaccaratReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SettleBaccarat not implemented")
}
func (UnimplementedRtpApiServer) ResetBaccarat(context.Context, *ResetBaccaratRequest) (*ResetBaccaratReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetBaccarat not implemented")
}
func (UnimplementedRtpApiServer) mustEmbedUnimplementedRtpApiServer() {}
func (UnimplementedRtpApiServer) testEmbeddedByValue()                {}

// UnsafeRtpApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RtpApiServer will
// result in compilation errors.
type UnsafeRtpApiServer interface {
	mustEmbedUnimplementedRtpApiServer()
}

func RegisterRtpApiServer(s grpc.ServiceRegistrar, srv RtpApiServer) {
	// If the following call pancis, it indicates UnimplementedRtpApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RtpApi_ServiceDesc, srv)
}

func _RtpApi_SelectSpin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectSpinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RtpApiServer).SelectSpin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RtpApi_SelectSpin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RtpApiServer).SelectSpin(ctx, req.(*SelectSpinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RtpApi_GetPlayerRtp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerRtpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RtpApiServer).GetPlayerRtp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RtpApi_GetPlayerRtp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RtpApiServer).GetPlayerRtp(ctx, req.(*GetPlayerRtpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RtpApi_GetBaccaratRtp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBaccaratRtpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RtpApiServer).GetBaccaratRtp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RtpApi_GetBaccaratRtp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RtpApiServer).GetBaccaratRtp(ctx, req.(*GetBaccaratRtpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RtpApi_SettleBaccarat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleBaccaratRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RtpApiServer).SettleBaccarat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RtpApi_SettleBaccarat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RtpApiServer).SettleBaccarat(ctx, req.(*SettleBaccaratRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RtpApi_ResetBaccarat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetBaccaratRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RtpApiServer).ResetBaccarat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RtpApi_ResetBaccarat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RtpApiServer).ResetBaccarat(ctx, req.(*ResetBaccaratRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RtpApi_ServiceDesc is the grpc.ServiceDesc for RtpApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RtpApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rtp.v1.RtpApi",
	HandlerType: (*RtpApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SelectSpin",
			Handler:    _RtpApi_SelectSpin_Handler,
		},
		{
			MethodName: "GetPlayerRtp",
			Handler:    _RtpApi_GetPlayerRtp_Handler,
		},
		{
			MethodName: "GetBaccaratRtp",
			Handler:    _RtpApi_GetBaccaratRtp_Handler,
		},
		{
			MethodName: "SettleBaccarat",
			Handler:    _RtpApi_SettleBaccarat_Handler,
		},
		{
			MethodName: "ResetBaccarat",
			Handler:    _RtpApi_ResetBaccarat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/rtp/v1/rtp.proto",
}
