// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: minitoken.proto

package minitoken

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenPayload struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AppId     string                 `protobuf:"bytes,1,opt,name=AppId,proto3" json:"AppId,omitempty"`
	PlayerId  string                 `protobuf:"bytes,2,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	GameBrand string                 `protobuf:"bytes,3,opt,name=GameBrand,proto3" json:"GameBrand,omitempty"`
	GameId    string                 `protobuf:"bytes,4,opt,name=GameId,proto3" json:"GameId,omitempty"`
	// 以下参数，不需要用户填写
	Expire        int64  `protobuf:"varint,99,opt,name=Expire,proto3" json:"Expire,omitempty"` // 过期时间，单位秒
	Sign          string `protobuf:"bytes,100,opt,name=Sign,proto3" json:"Sign,omitempty"`     // 签名，验证数据是否被修改
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenPayload) Reset() {
	*x = TokenPayload{}
	mi := &file_minitoken_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenPayload) ProtoMessage() {}

func (x *TokenPayload) ProtoReflect() protoreflect.Message {
	mi := &file_minitoken_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenPayload.ProtoReflect.Descriptor instead.
func (*TokenPayload) Descriptor() ([]byte, []int) {
	return file_minitoken_proto_rawDescGZIP(), []int{0}
}

func (x *TokenPayload) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *TokenPayload) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *TokenPayload) GetGameBrand() string {
	if x != nil {
		return x.GameBrand
	}
	return ""
}

func (x *TokenPayload) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *TokenPayload) GetExpire() int64 {
	if x != nil {
		return x.Expire
	}
	return 0
}

func (x *TokenPayload) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

var File_minitoken_proto protoreflect.FileDescriptor

const file_minitoken_proto_rawDesc = "" +
	"\n" +
	"\x0fminitoken.proto\x12\tminitoken\"\xa2\x01\n" +
	"\fTokenPayload\x12\x14\n" +
	"\x05AppId\x18\x01 \x01(\tR\x05AppId\x12\x1a\n" +
	"\bPlayerId\x18\x02 \x01(\tR\bPlayerId\x12\x1c\n" +
	"\tGameBrand\x18\x03 \x01(\tR\tGameBrand\x12\x16\n" +
	"\x06GameId\x18\x04 \x01(\tR\x06GameId\x12\x16\n" +
	"\x06Expire\x18c \x01(\x03R\x06Expire\x12\x12\n" +
	"\x04Sign\x18d \x01(\tR\x04SignB\x0eZ\f./;minitokenb\x06proto3"

var (
	file_minitoken_proto_rawDescOnce sync.Once
	file_minitoken_proto_rawDescData []byte
)

func file_minitoken_proto_rawDescGZIP() []byte {
	file_minitoken_proto_rawDescOnce.Do(func() {
		file_minitoken_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_minitoken_proto_rawDesc), len(file_minitoken_proto_rawDesc)))
	})
	return file_minitoken_proto_rawDescData
}

var file_minitoken_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_minitoken_proto_goTypes = []any{
	(*TokenPayload)(nil), // 0: minitoken.TokenPayload
}
var file_minitoken_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_minitoken_proto_init() }
func file_minitoken_proto_init() {
	if File_minitoken_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_minitoken_proto_rawDesc), len(file_minitoken_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_minitoken_proto_goTypes,
		DependencyIndexes: file_minitoken_proto_depIdxs,
		MessageInfos:      file_minitoken_proto_msgTypes,
	}.Build()
	File_minitoken_proto = out.File
	file_minitoken_proto_goTypes = nil
	file_minitoken_proto_depIdxs = nil
}
