// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: history/v1/baccarat_game.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BaccaratApi_CreateBaccarat_FullMethodName = "/baccarat.v1.BaccaratApi/CreateBaccarat"
	BaccaratApi_GetBaccarat_FullMethodName    = "/baccarat.v1.BaccaratApi/GetBaccarat"
)

// BaccaratApiClient is the client API for BaccaratApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 百人场
type BaccaratApiClient interface {
	// 创建游戏记录
	CreateBaccarat(ctx context.Context, in *CreateBaccaratRequest, opts ...grpc.CallOption) (*CreateBaccaratReply, error)
	// 获取记录详情
	GetBaccarat(ctx context.Context, in *GetBaccaratRequest, opts ...grpc.CallOption) (*GetBaccaratReply, error)
}

type baccaratApiClient struct {
	cc grpc.ClientConnInterface
}

func NewBaccaratApiClient(cc grpc.ClientConnInterface) BaccaratApiClient {
	return &baccaratApiClient{cc}
}

func (c *baccaratApiClient) CreateBaccarat(ctx context.Context, in *CreateBaccaratRequest, opts ...grpc.CallOption) (*CreateBaccaratReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBaccaratReply)
	err := c.cc.Invoke(ctx, BaccaratApi_CreateBaccarat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baccaratApiClient) GetBaccarat(ctx context.Context, in *GetBaccaratRequest, opts ...grpc.CallOption) (*GetBaccaratReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBaccaratReply)
	err := c.cc.Invoke(ctx, BaccaratApi_GetBaccarat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BaccaratApiServer is the server API for BaccaratApi service.
// All implementations must embed UnimplementedBaccaratApiServer
// for forward compatibility.
//
// 百人场
type BaccaratApiServer interface {
	// 创建游戏记录
	CreateBaccarat(context.Context, *CreateBaccaratRequest) (*CreateBaccaratReply, error)
	// 获取记录详情
	GetBaccarat(context.Context, *GetBaccaratRequest) (*GetBaccaratReply, error)
	mustEmbedUnimplementedBaccaratApiServer()
}

// UnimplementedBaccaratApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBaccaratApiServer struct{}

func (UnimplementedBaccaratApiServer) CreateBaccarat(context.Context, *CreateBaccaratRequest) (*CreateBaccaratReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBaccarat not implemented")
}
func (UnimplementedBaccaratApiServer) GetBaccarat(context.Context, *GetBaccaratRequest) (*GetBaccaratReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBaccarat not implemented")
}
func (UnimplementedBaccaratApiServer) mustEmbedUnimplementedBaccaratApiServer() {}
func (UnimplementedBaccaratApiServer) testEmbeddedByValue()                     {}

// UnsafeBaccaratApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BaccaratApiServer will
// result in compilation errors.
type UnsafeBaccaratApiServer interface {
	mustEmbedUnimplementedBaccaratApiServer()
}

func RegisterBaccaratApiServer(s grpc.ServiceRegistrar, srv BaccaratApiServer) {
	// If the following call pancis, it indicates UnimplementedBaccaratApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BaccaratApi_ServiceDesc, srv)
}

func _BaccaratApi_CreateBaccarat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBaccaratRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaccaratApiServer).CreateBaccarat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaccaratApi_CreateBaccarat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaccaratApiServer).CreateBaccarat(ctx, req.(*CreateBaccaratRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaccaratApi_GetBaccarat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBaccaratRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaccaratApiServer).GetBaccarat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaccaratApi_GetBaccarat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaccaratApiServer).GetBaccarat(ctx, req.(*GetBaccaratRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BaccaratApi_ServiceDesc is the grpc.ServiceDesc for BaccaratApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BaccaratApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "baccarat.v1.BaccaratApi",
	HandlerType: (*BaccaratApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBaccarat",
			Handler:    _BaccaratApi_CreateBaccarat_Handler,
		},
		{
			MethodName: "GetBaccarat",
			Handler:    _BaccaratApi_GetBaccarat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "history/v1/baccarat_game.proto",
}
