// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: history/v1/baccarat_game.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBaccaratRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AppId          string                 `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`                      //appid
	GameBrand      string                 `protobuf:"bytes,2,opt,name=gameBrand,proto3" json:"gameBrand,omitempty"`              //游戏品牌
	GameId         string                 `protobuf:"bytes,3,opt,name=gameId,proto3" json:"gameId,omitempty"`                    //游戏id
	RoundId        string                 `protobuf:"bytes,4,opt,name=roundId,proto3" json:"roundId,omitempty"`                  //游戏id
	RoomName       string                 `protobuf:"bytes,5,opt,name=roomName,proto3" json:"roomName,omitempty"`                //房间
	Rtp            string                 `protobuf:"bytes,6,opt,name=rtp,proto3" json:"rtp,omitempty"`                          // rtp
	StartTime      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=startTime,proto3" json:"startTime,omitempty"`              // 开始时间
	EndTime        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=endTime,proto3" json:"endTime,omitempty"`                  // 结束时间
	TotalPlayerBet float64                `protobuf:"fixed64,9,opt,name=totalPlayerBet,proto3" json:"totalPlayerBet,omitempty"`  // 总下注
	TotalPlayerWin float64                `protobuf:"fixed64,10,opt,name=totalPlayerWin,proto3" json:"totalPlayerWin,omitempty"` // 总派奖
	GameData       []byte                 `protobuf:"bytes,11,opt,name=gameData,proto3" json:"gameData,omitempty"`               //  自定义游戏数据
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateBaccaratRequest) Reset() {
	*x = CreateBaccaratRequest{}
	mi := &file_history_v1_baccarat_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBaccaratRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBaccaratRequest) ProtoMessage() {}

func (x *CreateBaccaratRequest) ProtoReflect() protoreflect.Message {
	mi := &file_history_v1_baccarat_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBaccaratRequest.ProtoReflect.Descriptor instead.
func (*CreateBaccaratRequest) Descriptor() ([]byte, []int) {
	return file_history_v1_baccarat_game_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBaccaratRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *CreateBaccaratRequest) GetGameBrand() string {
	if x != nil {
		return x.GameBrand
	}
	return ""
}

func (x *CreateBaccaratRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *CreateBaccaratRequest) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *CreateBaccaratRequest) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *CreateBaccaratRequest) GetRtp() string {
	if x != nil {
		return x.Rtp
	}
	return ""
}

func (x *CreateBaccaratRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *CreateBaccaratRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *CreateBaccaratRequest) GetTotalPlayerBet() float64 {
	if x != nil {
		return x.TotalPlayerBet
	}
	return 0
}

func (x *CreateBaccaratRequest) GetTotalPlayerWin() float64 {
	if x != nil {
		return x.TotalPlayerWin
	}
	return 0
}

func (x *CreateBaccaratRequest) GetGameData() []byte {
	if x != nil {
		return x.GameData
	}
	return nil
}

type CreateBaccaratReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaccaratId    int64                  `protobuf:"varint,1,opt,name=baccaratId,proto3" json:"baccaratId,omitempty"` // 记录id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBaccaratReply) Reset() {
	*x = CreateBaccaratReply{}
	mi := &file_history_v1_baccarat_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBaccaratReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBaccaratReply) ProtoMessage() {}

func (x *CreateBaccaratReply) ProtoReflect() protoreflect.Message {
	mi := &file_history_v1_baccarat_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBaccaratReply.ProtoReflect.Descriptor instead.
func (*CreateBaccaratReply) Descriptor() ([]byte, []int) {
	return file_history_v1_baccarat_game_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBaccaratReply) GetBaccaratId() int64 {
	if x != nil {
		return x.BaccaratId
	}
	return 0
}

type GetBaccaratRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`         //appid
	GameBrand     string                 `protobuf:"bytes,2,opt,name=gameBrand,proto3" json:"gameBrand,omitempty"` //游戏品牌
	GameId        string                 `protobuf:"bytes,3,opt,name=gameId,proto3" json:"gameId,omitempty"`       //游戏id
	RoundId       string                 `protobuf:"bytes,4,opt,name=roundId,proto3" json:"roundId,omitempty"`     //游戏id
	RoomName      string                 `protobuf:"bytes,5,opt,name=roomName,proto3" json:"roomName,omitempty"`   //房间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBaccaratRequest) Reset() {
	*x = GetBaccaratRequest{}
	mi := &file_history_v1_baccarat_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBaccaratRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBaccaratRequest) ProtoMessage() {}

func (x *GetBaccaratRequest) ProtoReflect() protoreflect.Message {
	mi := &file_history_v1_baccarat_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBaccaratRequest.ProtoReflect.Descriptor instead.
func (*GetBaccaratRequest) Descriptor() ([]byte, []int) {
	return file_history_v1_baccarat_game_proto_rawDescGZIP(), []int{2}
}

func (x *GetBaccaratRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GetBaccaratRequest) GetGameBrand() string {
	if x != nil {
		return x.GameBrand
	}
	return ""
}

func (x *GetBaccaratRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GetBaccaratRequest) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *GetBaccaratRequest) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

type GetBaccaratReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *BaccaratDetail        `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` //记录详情
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBaccaratReply) Reset() {
	*x = GetBaccaratReply{}
	mi := &file_history_v1_baccarat_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBaccaratReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBaccaratReply) ProtoMessage() {}

func (x *GetBaccaratReply) ProtoReflect() protoreflect.Message {
	mi := &file_history_v1_baccarat_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBaccaratReply.ProtoReflect.Descriptor instead.
func (*GetBaccaratReply) Descriptor() ([]byte, []int) {
	return file_history_v1_baccarat_game_proto_rawDescGZIP(), []int{3}
}

func (x *GetBaccaratReply) GetData() *BaccaratDetail {
	if x != nil {
		return x.Data
	}
	return nil
}

type BaccaratDetail struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AppId          string                 `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`                      //appid
	GameBrand      string                 `protobuf:"bytes,2,opt,name=gameBrand,proto3" json:"gameBrand,omitempty"`              //游戏品牌
	GameId         string                 `protobuf:"bytes,3,opt,name=gameId,proto3" json:"gameId,omitempty"`                    //游戏id
	RoundId        string                 `protobuf:"bytes,4,opt,name=roundId,proto3" json:"roundId,omitempty"`                  //游戏id
	RoomName       string                 `protobuf:"bytes,5,opt,name=roomName,proto3" json:"roomName,omitempty"`                //房间
	Rtp            string                 `protobuf:"bytes,6,opt,name=rtp,proto3" json:"rtp,omitempty"`                          // rtp
	StartTime      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=startTime,proto3" json:"startTime,omitempty"`              // 开始时间
	EndTime        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=endTime,proto3" json:"endTime,omitempty"`                  // 结束时间
	TotalPlayerBet float64                `protobuf:"fixed64,9,opt,name=totalPlayerBet,proto3" json:"totalPlayerBet,omitempty"`  // 总下注
	TotalPlayerWin float64                `protobuf:"fixed64,10,opt,name=totalPlayerWin,proto3" json:"totalPlayerWin,omitempty"` // 总派奖
	GameData       []byte                 `protobuf:"bytes,11,opt,name=gameData,proto3" json:"gameData,omitempty"`               //  自定义游戏数据
	CreateTime     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=createTime,proto3" json:"createTime,omitempty"`           // 创建时间
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BaccaratDetail) Reset() {
	*x = BaccaratDetail{}
	mi := &file_history_v1_baccarat_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaccaratDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaccaratDetail) ProtoMessage() {}

func (x *BaccaratDetail) ProtoReflect() protoreflect.Message {
	mi := &file_history_v1_baccarat_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaccaratDetail.ProtoReflect.Descriptor instead.
func (*BaccaratDetail) Descriptor() ([]byte, []int) {
	return file_history_v1_baccarat_game_proto_rawDescGZIP(), []int{4}
}

func (x *BaccaratDetail) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *BaccaratDetail) GetGameBrand() string {
	if x != nil {
		return x.GameBrand
	}
	return ""
}

func (x *BaccaratDetail) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *BaccaratDetail) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *BaccaratDetail) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *BaccaratDetail) GetRtp() string {
	if x != nil {
		return x.Rtp
	}
	return ""
}

func (x *BaccaratDetail) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *BaccaratDetail) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *BaccaratDetail) GetTotalPlayerBet() float64 {
	if x != nil {
		return x.TotalPlayerBet
	}
	return 0
}

func (x *BaccaratDetail) GetTotalPlayerWin() float64 {
	if x != nil {
		return x.TotalPlayerWin
	}
	return 0
}

func (x *BaccaratDetail) GetGameData() []byte {
	if x != nil {
		return x.GameData
	}
	return nil
}

func (x *BaccaratDetail) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

var File_history_v1_baccarat_game_proto protoreflect.FileDescriptor

const file_history_v1_baccarat_game_proto_rawDesc = "" +
	"\n" +
	"\x1ehistory/v1/baccarat_game.proto\x12\vbaccarat.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x87\x03\n" +
	"\x15CreateBaccaratRequest\x12\x14\n" +
	"\x05appId\x18\x01 \x01(\tR\x05appId\x12\x1c\n" +
	"\tgameBrand\x18\x02 \x01(\tR\tgameBrand\x12\x16\n" +
	"\x06gameId\x18\x03 \x01(\tR\x06gameId\x12\x18\n" +
	"\aroundId\x18\x04 \x01(\tR\aroundId\x12\x1a\n" +
	"\broomName\x18\x05 \x01(\tR\broomName\x12\x10\n" +
	"\x03rtp\x18\x06 \x01(\tR\x03rtp\x128\n" +
	"\tstartTime\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x124\n" +
	"\aendTime\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12&\n" +
	"\x0etotalPlayerBet\x18\t \x01(\x01R\x0etotalPlayerBet\x12&\n" +
	"\x0etotalPlayerWin\x18\n" +
	" \x01(\x01R\x0etotalPlayerWin\x12\x1a\n" +
	"\bgameData\x18\v \x01(\fR\bgameData\"5\n" +
	"\x13CreateBaccaratReply\x12\x1e\n" +
	"\n" +
	"baccaratId\x18\x01 \x01(\x03R\n" +
	"baccaratId\"\x96\x01\n" +
	"\x12GetBaccaratRequest\x12\x14\n" +
	"\x05appId\x18\x01 \x01(\tR\x05appId\x12\x1c\n" +
	"\tgameBrand\x18\x02 \x01(\tR\tgameBrand\x12\x16\n" +
	"\x06gameId\x18\x03 \x01(\tR\x06gameId\x12\x18\n" +
	"\aroundId\x18\x04 \x01(\tR\aroundId\x12\x1a\n" +
	"\broomName\x18\x05 \x01(\tR\broomName\"C\n" +
	"\x10GetBaccaratReply\x12/\n" +
	"\x04data\x18\x01 \x01(\v2\x1b.baccarat.v1.BaccaratDetailR\x04data\"\xbc\x03\n" +
	"\x0eBaccaratDetail\x12\x14\n" +
	"\x05appId\x18\x01 \x01(\tR\x05appId\x12\x1c\n" +
	"\tgameBrand\x18\x02 \x01(\tR\tgameBrand\x12\x16\n" +
	"\x06gameId\x18\x03 \x01(\tR\x06gameId\x12\x18\n" +
	"\aroundId\x18\x04 \x01(\tR\aroundId\x12\x1a\n" +
	"\broomName\x18\x05 \x01(\tR\broomName\x12\x10\n" +
	"\x03rtp\x18\x06 \x01(\tR\x03rtp\x128\n" +
	"\tstartTime\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x124\n" +
	"\aendTime\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12&\n" +
	"\x0etotalPlayerBet\x18\t \x01(\x01R\x0etotalPlayerBet\x12&\n" +
	"\x0etotalPlayerWin\x18\n" +
	" \x01(\x01R\x0etotalPlayerWin\x12\x1a\n" +
	"\bgameData\x18\v \x01(\fR\bgameData\x12:\n" +
	"\n" +
	"createTime\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime2\xb4\x01\n" +
	"\vBaccaratApi\x12V\n" +
	"\x0eCreateBaccarat\x12\".baccarat.v1.CreateBaccaratRequest\x1a .baccarat.v1.CreateBaccaratReply\x12M\n" +
	"\vGetBaccarat\x12\x1f.baccarat.v1.GetBaccaratRequest\x1a\x1d.baccarat.v1.GetBaccaratReplyB`\n" +
	"\x1adev.kratos.api.baccarat.v1B\x0eHistoryProtoV1P\x01Z0cn.qingdou.server/game_common/api/baccarat/v1;v1b\x06proto3"

var (
	file_history_v1_baccarat_game_proto_rawDescOnce sync.Once
	file_history_v1_baccarat_game_proto_rawDescData []byte
)

func file_history_v1_baccarat_game_proto_rawDescGZIP() []byte {
	file_history_v1_baccarat_game_proto_rawDescOnce.Do(func() {
		file_history_v1_baccarat_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_history_v1_baccarat_game_proto_rawDesc), len(file_history_v1_baccarat_game_proto_rawDesc)))
	})
	return file_history_v1_baccarat_game_proto_rawDescData
}

var file_history_v1_baccarat_game_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_history_v1_baccarat_game_proto_goTypes = []any{
	(*CreateBaccaratRequest)(nil), // 0: baccarat.v1.CreateBaccaratRequest
	(*CreateBaccaratReply)(nil),   // 1: baccarat.v1.CreateBaccaratReply
	(*GetBaccaratRequest)(nil),    // 2: baccarat.v1.GetBaccaratRequest
	(*GetBaccaratReply)(nil),      // 3: baccarat.v1.GetBaccaratReply
	(*BaccaratDetail)(nil),        // 4: baccarat.v1.BaccaratDetail
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_history_v1_baccarat_game_proto_depIdxs = []int32{
	5, // 0: baccarat.v1.CreateBaccaratRequest.startTime:type_name -> google.protobuf.Timestamp
	5, // 1: baccarat.v1.CreateBaccaratRequest.endTime:type_name -> google.protobuf.Timestamp
	4, // 2: baccarat.v1.GetBaccaratReply.data:type_name -> baccarat.v1.BaccaratDetail
	5, // 3: baccarat.v1.BaccaratDetail.startTime:type_name -> google.protobuf.Timestamp
	5, // 4: baccarat.v1.BaccaratDetail.endTime:type_name -> google.protobuf.Timestamp
	5, // 5: baccarat.v1.BaccaratDetail.createTime:type_name -> google.protobuf.Timestamp
	0, // 6: baccarat.v1.BaccaratApi.CreateBaccarat:input_type -> baccarat.v1.CreateBaccaratRequest
	2, // 7: baccarat.v1.BaccaratApi.GetBaccarat:input_type -> baccarat.v1.GetBaccaratRequest
	1, // 8: baccarat.v1.BaccaratApi.CreateBaccarat:output_type -> baccarat.v1.CreateBaccaratReply
	3, // 9: baccarat.v1.BaccaratApi.GetBaccarat:output_type -> baccarat.v1.GetBaccaratReply
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_history_v1_baccarat_game_proto_init() }
func file_history_v1_baccarat_game_proto_init() {
	if File_history_v1_baccarat_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_history_v1_baccarat_game_proto_rawDesc), len(file_history_v1_baccarat_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_history_v1_baccarat_game_proto_goTypes,
		DependencyIndexes: file_history_v1_baccarat_game_proto_depIdxs,
		MessageInfos:      file_history_v1_baccarat_game_proto_msgTypes,
	}.Build()
	File_history_v1_baccarat_game_proto = out.File
	file_history_v1_baccarat_game_proto_goTypes = nil
	file_history_v1_baccarat_game_proto_depIdxs = nil
}
