// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: history/v1/control.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlApi_Decide_FullMethodName  = "/control.v1.ControlApi/Decide"
	ControlApi_Settle_FullMethodName  = "/control.v1.ControlApi/Settle"
	ControlApi_Release_FullMethodName = "/control.v1.ControlApi/Release"
)

// ControlApiClient is the client API for ControlApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 运营活动旁路。Decide 失败或未命中时 hit=false，调用方继续基础 RTP。
type ControlApiClient interface {
	Decide(ctx context.Context, in *DecideRequest, opts ...grpc.CallOption) (*DecideReply, error)
	Settle(ctx context.Context, in *SettleRequest, opts ...grpc.CallOption) (*SettleReply, error)
	Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseReply, error)
}

type controlApiClient struct {
	cc grpc.ClientConnInterface
}

func NewControlApiClient(cc grpc.ClientConnInterface) ControlApiClient {
	return &controlApiClient{cc}
}

func (c *controlApiClient) Decide(ctx context.Context, in *DecideRequest, opts ...grpc.CallOption) (*DecideReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecideReply)
	err := c.cc.Invoke(ctx, ControlApi_Decide_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlApiClient) Settle(ctx context.Context, in *SettleRequest, opts ...grpc.CallOption) (*SettleReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettleReply)
	err := c.cc.Invoke(ctx, ControlApi_Settle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlApiClient) Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseReply)
	err := c.cc.Invoke(ctx, ControlApi_Release_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlApiServer is the server API for ControlApi service.
// All implementations must embed UnimplementedControlApiServer
// for forward compatibility.
//
// 运营活动旁路。Decide 失败或未命中时 hit=false，调用方继续基础 RTP。
type ControlApiServer interface {
	Decide(context.Context, *DecideRequest) (*DecideReply, error)
	Settle(context.Context, *SettleRequest) (*SettleReply, error)
	Release(context.Context, *ReleaseRequest) (*ReleaseReply, error)
	mustEmbedUnimplementedControlApiServer()
}

// UnimplementedControlApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlApiServer struct{}

func (UnimplementedControlApiServer) Decide(context.Context, *DecideRequest) (*DecideReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Decide not implemented")
}
func (UnimplementedControlApiServer) Settle(context.Context, *SettleRequest) (*SettleReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Settle not implemented")
}
func (UnimplementedControlApiServer) Release(context.Context, *ReleaseRequest) (*ReleaseReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Release not implemented")
}
func (UnimplementedControlApiServer) mustEmbedUnimplementedControlApiServer() {}
func (UnimplementedControlApiServer) testEmbeddedByValue()                    {}

// UnsafeControlApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlApiServer will
// result in compilation errors.
type UnsafeControlApiServer interface {
	mustEmbedUnimplementedControlApiServer()
}

func RegisterControlApiServer(s grpc.ServiceRegistrar, srv ControlApiServer) {
	// If the following call pancis, it indicates UnimplementedControlApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlApi_ServiceDesc, srv)
}

func _ControlApi_Decide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlApiServer).Decide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlApi_Decide_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlApiServer).Decide(ctx, req.(*DecideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlApi_Settle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlApiServer).Settle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlApi_Settle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlApiServer).Settle(ctx, req.(*SettleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlApi_Release_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlApiServer).Release(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlApi_Release_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlApiServer).Release(ctx, req.(*ReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlApi_ServiceDesc is the grpc.ServiceDesc for ControlApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "control.v1.ControlApi",
	HandlerType: (*ControlApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Decide",
			Handler:    _ControlApi_Decide_Handler,
		},
		{
			MethodName: "Settle",
			Handler:    _ControlApi_Settle_Handler,
		},
		{
			MethodName: "Release",
			Handler:    _ControlApi_Release_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "history/v1/control.proto",
}
