// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: history/v1/control.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DecideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=playerId,proto3" json:"playerId,omitempty"`
	UniqueId      string                 `protobuf:"bytes,3,opt,name=uniqueId,proto3" json:"uniqueId,omitempty"`
	Platform      string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"` // ai777 / api5 / select_spin
	GameBrand     string                 `protobuf:"bytes,5,opt,name=gameBrand,proto3" json:"gameBrand,omitempty"`
	GameId        string                 `protobuf:"bytes,6,opt,name=gameId,proto3" json:"gameId,omitempty"`
	RoundId       string                 `protobuf:"bytes,7,opt,name=roundId,proto3" json:"roundId,omitempty"`
	Currency      string                 `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	RoundModel    string                 `protobuf:"bytes,9,opt,name=roundModel,proto3" json:"roundModel,omitempty"` // DEFAULT / BUY / EXTRA
	BaseRtp       string                 `protobuf:"bytes,10,opt,name=baseRtp,proto3" json:"baseRtp,omitempty"`      // 调用方已取到的基础 RTP
	Bet           float64                `protobuf:"fixed64,11,opt,name=bet,proto3" json:"bet,omitempty"`
	Pinned        bool                   `protobuf:"varint,12,opt,name=pinned,proto3" json:"pinned,omitempty"` // 点控预留。true 时不抬档、不扣局
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecideRequest) Reset() {
	*x = DecideRequest{}
	mi := &file_history_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecideRequest) ProtoMessage() {}

func (x *DecideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_history_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecideRequest.ProtoReflect.Descriptor instead.
func (*DecideRequest) Descriptor() ([]byte, []int) {
	return file_history_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *DecideRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *DecideRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *DecideRequest) GetUniqueId() string {
	if x != nil {
		return x.UniqueId
	}
	return ""
}

func (x *DecideRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *DecideRequest) GetGameBrand() string {
	if x != nil {
		return x.GameBrand
	}
	return ""
}

func (x *DecideRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *DecideRequest) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *DecideRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *DecideRequest) GetRoundModel() string {
	if x != nil {
		return x.RoundModel
	}
	return ""
}

func (x *DecideRequest) GetBaseRtp() string {
	if x != nil {
		return x.BaseRtp
	}
	return ""
}

func (x *DecideRequest) GetBet() float64 {
	if x != nil {
		return x.Bet
	}
	return 0
}

func (x *DecideRequest) GetPinned() bool {
	if x != nil {
		return x.Pinned
	}
	return false
}

type DecideReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hit           bool                   `protobuf:"varint,1,opt,name=hit,proto3" json:"hit,omitempty"`
	CampaignType  string                 `protobuf:"bytes,2,opt,name=campaignType,proto3" json:"campaignType,omitempty"`
	CampaignId    int64                  `protobuf:"varint,3,opt,name=campaignId,proto3" json:"campaignId,omitempty"`
	Rtp           string                 `protobuf:"bytes,4,opt,name=rtp,proto3" json:"rtp,omitempty"` // 未命中时等于 baseRtp
	MaxWin        float64                `protobuf:"fixed64,5,opt,name=maxWin,proto3" json:"maxWin,omitempty"`
	MaxRate       float64                `protobuf:"fixed64,6,opt,name=maxRate,proto3" json:"maxRate,omitempty"`
	Track         bool                   `protobuf:"varint,7,opt,name=track,proto3" json:"track,omitempty"`
	Consume       bool                   `protobuf:"varint,8,opt,name=consume,proto3" json:"consume,omitempty"`
	SkipReason    string                 `protobuf:"bytes,9,opt,name=skipReason,proto3" json:"skipReason,omitempty"`
	Reason        string                 `protobuf:"bytes,10,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecideReply) Reset() {
	*x = DecideReply{}
	mi := &file_history_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecideReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecideReply) ProtoMessage() {}

func (x *DecideReply) ProtoReflect() protoreflect.Message {
	mi := &file_history_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecideReply.ProtoReflect.Descriptor instead.
func (*DecideReply) Descriptor() ([]byte, []int) {
	return file_history_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *DecideReply) GetHit() bool {
	if x != nil {
		return x.Hit
	}
	return false
}

func (x *DecideReply) GetCampaignType() string {
	if x != nil {
		return x.CampaignType
	}
	return ""
}

func (x *DecideReply) GetCampaignId() int64 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

func (x *DecideReply) GetRtp() string {
	if x != nil {
		return x.Rtp
	}
	return ""
}

func (x *DecideReply) GetMaxWin() float64 {
	if x != nil {
		return x.MaxWin
	}
	return 0
}

func (x *DecideReply) GetMaxRate() float64 {
	if x != nil {
		return x.MaxRate
	}
	return 0
}

func (x *DecideReply) GetTrack() bool {
	if x != nil {
		return x.Track
	}
	return false
}

func (x *DecideReply) GetConsume() bool {
	if x != nil {
		return x.Consume
	}
	return false
}

func (x *DecideReply) GetSkipReason() string {
	if x != nil {
		return x.SkipReason
	}
	return ""
}

func (x *DecideReply) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type SettleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	RoundId       string                 `protobuf:"bytes,4,opt,name=roundId,proto3" json:"roundId,omitempty"`
	GameBrand     string                 `protobuf:"bytes,5,opt,name=gameBrand,proto3" json:"gameBrand,omitempty"`
	GameId        string                 `protobuf:"bytes,6,opt,name=gameId,proto3" json:"gameId,omitempty"`
	Currency      string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	Bet           float64                `protobuf:"fixed64,8,opt,name=bet,proto3" json:"bet,omitempty"`
	Win           float64                `protobuf:"fixed64,9,opt,name=win,proto3" json:"win,omitempty"` // 该 RoundID 的整局派彩
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleRequest) Reset() {
	*x = SettleRequest{}
	mi := &file_history_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleRequest) ProtoMessage() {}

func (x *SettleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_history_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleRequest.ProtoReflect.Descriptor instead.
func (*SettleRequest) Descriptor() ([]byte, []int) {
	return file_history_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *SettleRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *SettleRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *SettleRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *SettleRequest) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *SettleRequest) GetGameBrand() string {
	if x != nil {
		return x.GameBrand
	}
	return ""
}

func (x *SettleRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *SettleRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *SettleRequest) GetBet() float64 {
	if x != nil {
		return x.Bet
	}
	return 0
}

func (x *SettleRequest) GetWin() float64 {
	if x != nil {
		return x.Win
	}
	return 0
}

type SettleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Saved         bool                   `protobuf:"varint,1,opt,name=saved,proto3" json:"saved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleReply) Reset() {
	*x = SettleReply{}
	mi := &file_history_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleReply) ProtoMessage() {}

func (x *SettleReply) ProtoReflect() protoreflect.Message {
	mi := &file_history_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleReply.ProtoReflect.Descriptor instead.
func (*SettleReply) Descriptor() ([]byte, []int) {
	return file_history_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *SettleReply) GetSaved() bool {
	if x != nil {
		return x.Saved
	}
	return false
}

type ReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	RoundId       string                 `protobuf:"bytes,4,opt,name=roundId,proto3" json:"roundId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseRequest) Reset() {
	*x = ReleaseRequest{}
	mi := &file_history_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRequest) ProtoMessage() {}

func (x *ReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_history_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRequest) Descriptor() ([]byte, []int) {
	return file_history_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *ReleaseRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ReleaseRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ReleaseRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ReleaseRequest) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

type ReleaseReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseReply) Reset() {
	*x = ReleaseReply{}
	mi := &file_history_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseReply) ProtoMessage() {}

func (x *ReleaseReply) ProtoReflect() protoreflect.Message {
	mi := &file_history_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseReply.ProtoReflect.Descriptor instead.
func (*ReleaseReply) Descriptor() ([]byte, []int) {
	return file_history_v1_control_proto_rawDescGZIP(), []int{5}
}

var File_history_v1_control_proto protoreflect.FileDescriptor

const file_history_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x18history/v1/control.proto\x12\n" +
	"control.v1\"\xc9\x02\n" +
	"\rDecideRequest\x12\x14\n" +
	"\x05appId\x18\x01 \x01(\tR\x05appId\x12\x1a\n" +
	"\bplayerId\x18\x02 \x01(\tR\bplayerId\x12\x1a\n" +
	"\buniqueId\x18\x03 \x01(\tR\buniqueId\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12\x1c\n" +
	"\tgameBrand\x18\x05 \x01(\tR\tgameBrand\x12\x16\n" +
	"\x06gameId\x18\x06 \x01(\tR\x06gameId\x12\x18\n" +
	"\aroundId\x18\a \x01(\tR\aroundId\x12\x1a\n" +
	"\bcurrency\x18\b \x01(\tR\bcurrency\x12\x1e\n" +
	"\n" +
	"roundModel\x18\t \x01(\tR\n" +
	"roundModel\x12\x18\n" +
	"\abaseRtp\x18\n" +
	" \x01(\tR\abaseRtp\x12\x10\n" +
	"\x03bet\x18\v \x01(\x01R\x03bet\x12\x16\n" +
	"\x06pinned\x18\f \x01(\bR\x06pinned\"\x8f\x02\n" +
	"\vDecideReply\x12\x10\n" +
	"\x03hit\x18\x01 \x01(\bR\x03hit\x12\"\n" +
	"\fcampaignType\x18\x02 \x01(\tR\fcampaignType\x12\x1e\n" +
	"\n" +
	"campaignId\x18\x03 \x01(\x03R\n" +
	"campaignId\x12\x10\n" +
	"\x03rtp\x18\x04 \x01(\tR\x03rtp\x12\x16\n" +
	"\x06maxWin\x18\x05 \x01(\x01R\x06maxWin\x12\x18\n" +
	"\amaxRate\x18\x06 \x01(\x01R\amaxRate\x12\x14\n" +
	"\x05track\x18\a \x01(\bR\x05track\x12\x18\n" +
	"\aconsume\x18\b \x01(\bR\aconsume\x12\x1e\n" +
	"\n" +
	"skipReason\x18\t \x01(\tR\n" +
	"skipReason\x12\x16\n" +
	"\x06reason\x18\n" +
	" \x01(\tR\x06reason\"\xed\x01\n" +
	"\rSettleRequest\x12\x14\n" +
	"\x05appId\x18\x01 \x01(\tR\x05appId\x12\x1a\n" +
	"\bplayerId\x18\x02 \x01(\tR\bplayerId\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x18\n" +
	"\aroundId\x18\x04 \x01(\tR\aroundId\x12\x1c\n" +
	"\tgameBrand\x18\x05 \x01(\tR\tgameBrand\x12\x16\n" +
	"\x06gameId\x18\x06 \x01(\tR\x06gameId\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x12\x10\n" +
	"\x03bet\x18\b \x01(\x01R\x03bet\x12\x10\n" +
	"\x03win\x18\t \x01(\x01R\x03win\"#\n" +
	"\vSettleReply\x12\x14\n" +
	"\x05saved\x18\x01 \x01(\bR\x05saved\"x\n" +
	"\x0eReleaseRequest\x12\x14\n" +
	"\x05appId\x18\x01 \x01(\tR\x05appId\x12\x1a\n" +
	"\bplayerId\x18\x02 \x01(\tR\bplayerId\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x18\n" +
	"\aroundId\x18\x04 \x01(\tR\aroundId\"\x0e\n" +
	"\fReleaseReply2\xc9\x01\n" +
	"\n" +
	"ControlApi\x12<\n" +
	"\x06Decide\x12\x19.control.v1.DecideRequest\x1a\x17.control.v1.DecideReply\x12<\n" +
	"\x06Settle\x12\x19.control.v1.SettleRequest\x1a\x17.control.v1.SettleReply\x12?\n" +
	"\aRelease\x12\x1a.control.v1.ReleaseRequest\x1a\x18.control.v1.ReleaseReplyBc\n" +
	"\x19dev.kratos.api.control.v1B\x0eControlProtoV1P\x01Z4github.com/card-engine/game_common/api/history/v1;v1b\x06proto3"

var (
	file_history_v1_control_proto_rawDescOnce sync.Once
	file_history_v1_control_proto_rawDescData []byte
)

func file_history_v1_control_proto_rawDescGZIP() []byte {
	file_history_v1_control_proto_rawDescOnce.Do(func() {
		file_history_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_history_v1_control_proto_rawDesc), len(file_history_v1_control_proto_rawDesc)))
	})
	return file_history_v1_control_proto_rawDescData
}

var file_history_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_history_v1_control_proto_goTypes = []any{
	(*DecideRequest)(nil),  // 0: control.v1.DecideRequest
	(*DecideReply)(nil),    // 1: control.v1.DecideReply
	(*SettleRequest)(nil),  // 2: control.v1.SettleRequest
	(*SettleReply)(nil),    // 3: control.v1.SettleReply
	(*ReleaseRequest)(nil), // 4: control.v1.ReleaseRequest
	(*ReleaseReply)(nil),   // 5: control.v1.ReleaseReply
}
var file_history_v1_control_proto_depIdxs = []int32{
	0, // 0: control.v1.ControlApi.Decide:input_type -> control.v1.DecideRequest
	2, // 1: control.v1.ControlApi.Settle:input_type -> control.v1.SettleRequest
	4, // 2: control.v1.ControlApi.Release:input_type -> control.v1.ReleaseRequest
	1, // 3: control.v1.ControlApi.Decide:output_type -> control.v1.DecideReply
	3, // 4: control.v1.ControlApi.Settle:output_type -> control.v1.SettleReply
	5, // 5: control.v1.ControlApi.Release:output_type -> control.v1.ReleaseReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_history_v1_control_proto_init() }
func file_history_v1_control_proto_init() {
	if File_history_v1_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_history_v1_control_proto_rawDesc), len(file_history_v1_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_history_v1_control_proto_goTypes,
		DependencyIndexes: file_history_v1_control_proto_depIdxs,
		MessageInfos:      file_history_v1_control_proto_msgTypes,
	}.Build()
	File_history_v1_control_proto = out.File
	file_history_v1_control_proto_goTypes = nil
	file_history_v1_control_proto_depIdxs = nil
}
