// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: api/history/v1/game_bet_config.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameBetConfigApi_GetGameBetConfig_FullMethodName = "/game_bet_config.v1.GameBetConfigApi/GetGameBetConfig"
)

// GameBetConfigApiClient is the client API for GameBetConfigApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 游戏下注配置
type GameBetConfigApiClient interface {
	// 获取游戏下注配置详情
	GetGameBetConfig(ctx context.Context, in *GetGameBetConfigRequest, opts ...grpc.CallOption) (*GetGameBetConfigReply, error)
}

type gameBetConfigApiClient struct {
	cc grpc.ClientConnInterface
}

func NewGameBetConfigApiClient(cc grpc.ClientConnInterface) GameBetConfigApiClient {
	return &gameBetConfigApiClient{cc}
}

func (c *gameBetConfigApiClient) GetGameBetConfig(ctx context.Context, in *GetGameBetConfigRequest, opts ...grpc.CallOption) (*GetGameBetConfigReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGameBetConfigReply)
	err := c.cc.Invoke(ctx, GameBetConfigApi_GetGameBetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameBetConfigApiServer is the server API for GameBetConfigApi service.
// All implementations must embed UnimplementedGameBetConfigApiServer
// for forward compatibility.
//
// 游戏下注配置
type GameBetConfigApiServer interface {
	// 获取游戏下注配置详情
	GetGameBetConfig(context.Context, *GetGameBetConfigRequest) (*GetGameBetConfigReply, error)
	mustEmbedUnimplementedGameBetConfigApiServer()
}

// UnimplementedGameBetConfigApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameBetConfigApiServer struct{}

func (UnimplementedGameBetConfigApiServer) GetGameBetConfig(context.Context, *GetGameBetConfigRequest) (*GetGameBetConfigReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGameBetConfig not implemented")
}
func (UnimplementedGameBetConfigApiServer) mustEmbedUnimplementedGameBetConfigApiServer() {}
func (UnimplementedGameBetConfigApiServer) testEmbeddedByValue()                          {}

// UnsafeGameBetConfigApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameBetConfigApiServer will
// result in compilation errors.
type UnsafeGameBetConfigApiServer interface {
	mustEmbedUnimplementedGameBetConfigApiServer()
}

func RegisterGameBetConfigApiServer(s grpc.ServiceRegistrar, srv GameBetConfigApiServer) {
	// If the following call pancis, it indicates UnimplementedGameBetConfigApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameBetConfigApi_ServiceDesc, srv)
}

func _GameBetConfigApi_GetGameBetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameBetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameBetConfigApiServer).GetGameBetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameBetConfigApi_GetGameBetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameBetConfigApiServer).GetGameBetConfig(ctx, req.(*GetGameBetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameBetConfigApi_ServiceDesc is the grpc.ServiceDesc for GameBetConfigApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameBetConfigApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game_bet_config.v1.GameBetConfigApi",
	HandlerType: (*GameBetConfigApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGameBetConfig",
			Handler:    _GameBetConfigApi_GetGameBetConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/history/v1/game_bet_config.proto",
}
