// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: history/v1/game_stat.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserStatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`         //appid
	PlayerId      string                 `protobuf:"bytes,2,opt,name=playerId,proto3" json:"playerId,omitempty"`   //玩家id
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=startTime,proto3" json:"startTime,omitempty"` // 开始时间
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=endTime,proto3" json:"endTime,omitempty"`     // 结束时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserStatRequest) Reset() {
	*x = GetUserStatRequest{}
	mi := &file_history_v1_game_stat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserStatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatRequest) ProtoMessage() {}

func (x *GetUserStatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_history_v1_game_stat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatRequest.ProtoReflect.Descriptor instead.
func (*GetUserStatRequest) Descriptor() ([]byte, []int) {
	return file_history_v1_game_stat_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserStatRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GetUserStatRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *GetUserStatRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetUserStatRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type GetUserStatSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bet           float64                `protobuf:"fixed64,1,opt,name=bet,proto3" json:"bet,omitempty"`                 // 总下注
	Win           float64                `protobuf:"fixed64,2,opt,name=win,proto3" json:"win,omitempty"`                 // 总赢钱
	RoundCount    int64                  `protobuf:"varint,3,opt,name=roundCount,proto3" json:"roundCount,omitempty"`    // 记录数
	RealtimeRtp   float32                `protobuf:"fixed32,4,opt,name=realtimeRtp,proto3" json:"realtimeRtp,omitempty"` // 实时rtp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserStatSnapshot) Reset() {
	*x = GetUserStatSnapshot{}
	mi := &file_history_v1_game_stat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserStatSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatSnapshot) ProtoMessage() {}

func (x *GetUserStatSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_history_v1_game_stat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatSnapshot.ProtoReflect.Descriptor instead.
func (*GetUserStatSnapshot) Descriptor() ([]byte, []int) {
	return file_history_v1_game_stat_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserStatSnapshot) GetBet() float64 {
	if x != nil {
		return x.Bet
	}
	return 0
}

func (x *GetUserStatSnapshot) GetWin() float64 {
	if x != nil {
		return x.Win
	}
	return 0
}

func (x *GetUserStatSnapshot) GetRoundCount() int64 {
	if x != nil {
		return x.RoundCount
	}
	return 0
}

func (x *GetUserStatSnapshot) GetRealtimeRtp() float32 {
	if x != nil {
		return x.RealtimeRtp
	}
	return 0
}

// BehaviorProfile 近 1h 玩家行为画像（TTL 1h，不随 short FIFO 窗口失真）。
type BehaviorProfile struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MinBet         float64                `protobuf:"fixed64,1,opt,name=minBet,proto3" json:"minBet,omitempty"`                 // 1h 内最小单局注额
	MaxBet         float64                `protobuf:"fixed64,2,opt,name=maxBet,proto3" json:"maxBet,omitempty"`                 // 1h 内最大单局注额（历史峰值）
	LastBet        float64                `protobuf:"fixed64,3,opt,name=lastBet,proto3" json:"lastBet,omitempty"`               // 上一局注额
	SameBetStreak  int64                  `protobuf:"varint,4,opt,name=sameBetStreak,proto3" json:"sameBetStreak,omitempty"`    // 当前注额连续局数（换档重置为 1）
	RampSteps      int64                  `protobuf:"varint,5,opt,name=rampSteps,proto3" json:"rampSteps,omitempty"`            // 升档次数（bet 严格增大时 +1）
	PeakRounds     int64                  `protobuf:"varint,6,opt,name=peakRounds,proto3" json:"peakRounds,omitempty"`          // 在 maxBet 档上的累计局数
	PeakBetTotal   float64                `protobuf:"fixed64,7,opt,name=peakBetTotal,proto3" json:"peakBetTotal,omitempty"`     // maxBet 档累计下注
	PeakWinTotal   float64                `protobuf:"fixed64,8,opt,name=peakWinTotal,proto3" json:"peakWinTotal,omitempty"`     // maxBet 档累计派彩
	PeakRtp        float32                `protobuf:"fixed32,9,opt,name=peakRtp,proto3" json:"peakRtp,omitempty"`               // maxBet 档 RTP（peakWin/peakBet*100）
	TotalRounds    int64                  `protobuf:"varint,11,opt,name=totalRounds,proto3" json:"totalRounds,omitempty"`       // 1h 内总局数
	BetDownSteps   int64                  `protobuf:"varint,12,opt,name=betDownSteps,proto3" json:"betDownSteps,omitempty"`     // 降档次数；0 表示全程单调升档
	LastRampFrom   float64                `protobuf:"fixed64,13,opt,name=lastRampFrom,proto3" json:"lastRampFrom,omitempty"`    // 最近一次升档起点注额
	LastRampTo     float64                `protobuf:"fixed64,14,opt,name=lastRampTo,proto3" json:"lastRampTo,omitempty"`        // 最近一次升档终点注额
	LastRampRounds int64                  `protobuf:"varint,15,opt,name=lastRampRounds,proto3" json:"lastRampRounds,omitempty"` // 升档前在 lastRampFrom 档停留局数
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BehaviorProfile) Reset() {
	*x = BehaviorProfile{}
	mi := &file_history_v1_game_stat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BehaviorProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BehaviorProfile) ProtoMessage() {}

func (x *BehaviorProfile) ProtoReflect() protoreflect.Message {
	mi := &file_history_v1_game_stat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BehaviorProfile.ProtoReflect.Descriptor instead.
func (*BehaviorProfile) Descriptor() ([]byte, []int) {
	return file_history_v1_game_stat_proto_rawDescGZIP(), []int{2}
}

func (x *BehaviorProfile) GetMinBet() float64 {
	if x != nil {
		return x.MinBet
	}
	return 0
}

func (x *BehaviorProfile) GetMaxBet() float64 {
	if x != nil {
		return x.MaxBet
	}
	return 0
}

func (x *BehaviorProfile) GetLastBet() float64 {
	if x != nil {
		return x.LastBet
	}
	return 0
}

func (x *BehaviorProfile) GetSameBetStreak() int64 {
	if x != nil {
		return x.SameBetStreak
	}
	return 0
}

func (x *BehaviorProfile) GetRampSteps() int64 {
	if x != nil {
		return x.RampSteps
	}
	return 0
}

func (x *BehaviorProfile) GetPeakRounds() int64 {
	if x != nil {
		return x.PeakRounds
	}
	return 0
}

func (x *BehaviorProfile) GetPeakBetTotal() float64 {
	if x != nil {
		return x.PeakBetTotal
	}
	return 0
}

func (x *BehaviorProfile) GetPeakWinTotal() float64 {
	if x != nil {
		return x.PeakWinTotal
	}
	return 0
}

func (x *BehaviorProfile) GetPeakRtp() float32 {
	if x != nil {
		return x.PeakRtp
	}
	return 0
}

func (x *BehaviorProfile) GetTotalRounds() int64 {
	if x != nil {
		return x.TotalRounds
	}
	return 0
}

func (x *BehaviorProfile) GetBetDownSteps() int64 {
	if x != nil {
		return x.BetDownSteps
	}
	return 0
}

func (x *BehaviorProfile) GetLastRampFrom() float64 {
	if x != nil {
		return x.LastRampFrom
	}
	return 0
}

func (x *BehaviorProfile) GetLastRampTo() float64 {
	if x != nil {
		return x.LastRampTo
	}
	return 0
}

func (x *BehaviorProfile) GetLastRampRounds() int64 {
	if x != nil {
		return x.LastRampRounds
	}
	return 0
}

type GetUserStatReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalBet       float64                `protobuf:"fixed64,1,opt,name=totalBet,proto3" json:"totalBet,omitempty"`            // 总下注
	TotalWin       float64                `protobuf:"fixed64,2,opt,name=totalWin,proto3" json:"totalWin,omitempty"`            // 总赢钱
	RoundCount     int64                  `protobuf:"varint,3,opt,name=roundCount,proto3" json:"roundCount,omitempty"`         // 记录数
	RealtimeRtp    float32                `protobuf:"fixed32,4,opt,name=realtimeRtp,proto3" json:"realtimeRtp,omitempty"`      // 实时rtp
	RecentSnapshot *GetUserStatSnapshot   `protobuf:"bytes,5,opt,name=recentSnapshot,proto3" json:"recentSnapshot,omitempty"`  // 最近快照
	TodaySnapshot  *GetUserStatSnapshot   `protobuf:"bytes,6,opt,name=todaySnapshot,proto3" json:"todaySnapshot,omitempty"`    // 今日快照
	RecentBets     []float64              `protobuf:"fixed64,7,rep,packed,name=recentBets,proto3" json:"recentBets,omitempty"` // 近 N 局注额，旧→新
	Behavior       *BehaviorProfile       `protobuf:"bytes,8,opt,name=behavior,proto3" json:"behavior,omitempty"`              // 近 1h 行为画像
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUserStatReply) Reset() {
	*x = GetUserStatReply{}
	mi := &file_history_v1_game_stat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserStatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatReply) ProtoMessage() {}

func (x *GetUserStatReply) ProtoReflect() protoreflect.Message {
	mi := &file_history_v1_game_stat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatReply.ProtoReflect.Descriptor instead.
func (*GetUserStatReply) Descriptor() ([]byte, []int) {
	return file_history_v1_game_stat_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserStatReply) GetTotalBet() float64 {
	if x != nil {
		return x.TotalBet
	}
	return 0
}

func (x *GetUserStatReply) GetTotalWin() float64 {
	if x != nil {
		return x.TotalWin
	}
	return 0
}

func (x *GetUserStatReply) GetRoundCount() int64 {
	if x != nil {
		return x.RoundCount
	}
	return 0
}

func (x *GetUserStatReply) GetRealtimeRtp() float32 {
	if x != nil {
		return x.RealtimeRtp
	}
	return 0
}

func (x *GetUserStatReply) GetRecentSnapshot() *GetUserStatSnapshot {
	if x != nil {
		return x.RecentSnapshot
	}
	return nil
}

func (x *GetUserStatReply) GetTodaySnapshot() *GetUserStatSnapshot {
	if x != nil {
		return x.TodaySnapshot
	}
	return nil
}

func (x *GetUserStatReply) GetRecentBets() []float64 {
	if x != nil {
		return x.RecentBets
	}
	return nil
}

func (x *GetUserStatReply) GetBehavior() *BehaviorProfile {
	if x != nil {
		return x.Behavior
	}
	return nil
}

var File_history_v1_game_stat_proto protoreflect.FileDescriptor

const file_history_v1_game_stat_proto_rawDesc = "" +
	"\n" +
	"\x1ahistory/v1/game_stat.proto\x12\vbaccarat.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb6\x01\n" +
	"\x12GetUserStatRequest\x12\x14\n" +
	"\x05appId\x18\x01 \x01(\tR\x05appId\x12\x1a\n" +
	"\bplayerId\x18\x02 \x01(\tR\bplayerId\x128\n" +
	"\tstartTime\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x124\n" +
	"\aendTime\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"{\n" +
	"\x13GetUserStatSnapshot\x12\x10\n" +
	"\x03bet\x18\x01 \x01(\x01R\x03bet\x12\x10\n" +
	"\x03win\x18\x02 \x01(\x01R\x03win\x12\x1e\n" +
	"\n" +
	"roundCount\x18\x03 \x01(\x03R\n" +
	"roundCount\x12 \n" +
	"\vrealtimeRtp\x18\x04 \x01(\x02R\vrealtimeRtp\"\xd3\x03\n" +
	"\x0fBehaviorProfile\x12\x16\n" +
	"\x06minBet\x18\x01 \x01(\x01R\x06minBet\x12\x16\n" +
	"\x06maxBet\x18\x02 \x01(\x01R\x06maxBet\x12\x18\n" +
	"\alastBet\x18\x03 \x01(\x01R\alastBet\x12$\n" +
	"\rsameBetStreak\x18\x04 \x01(\x03R\rsameBetStreak\x12\x1c\n" +
	"\trampSteps\x18\x05 \x01(\x03R\trampSteps\x12\x1e\n" +
	"\n" +
	"peakRounds\x18\x06 \x01(\x03R\n" +
	"peakRounds\x12\"\n" +
	"\fpeakBetTotal\x18\a \x01(\x01R\fpeakBetTotal\x12\"\n" +
	"\fpeakWinTotal\x18\b \x01(\x01R\fpeakWinTotal\x12\x18\n" +
	"\apeakRtp\x18\t \x01(\x02R\apeakRtp\x12 \n" +
	"\vtotalRounds\x18\v \x01(\x03R\vtotalRounds\x12\"\n" +
	"\fbetDownSteps\x18\f \x01(\x03R\fbetDownSteps\x12\"\n" +
	"\flastRampFrom\x18\r \x01(\x01R\flastRampFrom\x12\x1e\n" +
	"\n" +
	"lastRampTo\x18\x0e \x01(\x01R\n" +
	"lastRampTo\x12&\n" +
	"\x0elastRampRounds\x18\x0f \x01(\x03R\x0elastRampRounds\"\xf8\x02\n" +
	"\x10GetUserStatReply\x12\x1a\n" +
	"\btotalBet\x18\x01 \x01(\x01R\btotalBet\x12\x1a\n" +
	"\btotalWin\x18\x02 \x01(\x01R\btotalWin\x12\x1e\n" +
	"\n" +
	"roundCount\x18\x03 \x01(\x03R\n" +
	"roundCount\x12 \n" +
	"\vrealtimeRtp\x18\x04 \x01(\x02R\vrealtimeRtp\x12H\n" +
	"\x0erecentSnapshot\x18\x05 \x01(\v2 .baccarat.v1.GetUserStatSnapshotR\x0erecentSnapshot\x12F\n" +
	"\rtodaySnapshot\x18\x06 \x01(\v2 .baccarat.v1.GetUserStatSnapshotR\rtodaySnapshot\x12\x1e\n" +
	"\n" +
	"recentBets\x18\a \x03(\x01R\n" +
	"recentBets\x128\n" +
	"\bbehavior\x18\b \x01(\v2\x1c.baccarat.v1.BehaviorProfileR\bbehavior2\\\n" +
	"\vGameStatApi\x12M\n" +
	"\vGetUserStat\x12\x1f.baccarat.v1.GetUserStatRequest\x1a\x1d.baccarat.v1.GetUserStatReplyBg\n" +
	"\x1bdev.kratos.api.game_stat.v1B\x0eHistoryProtoV1P\x01Z6github.com/card-engine/game_common/api/game_stat/v1;v1b\x06proto3"

var (
	file_history_v1_game_stat_proto_rawDescOnce sync.Once
	file_history_v1_game_stat_proto_rawDescData []byte
)

func file_history_v1_game_stat_proto_rawDescGZIP() []byte {
	file_history_v1_game_stat_proto_rawDescOnce.Do(func() {
		file_history_v1_game_stat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_history_v1_game_stat_proto_rawDesc), len(file_history_v1_game_stat_proto_rawDesc)))
	})
	return file_history_v1_game_stat_proto_rawDescData
}

var file_history_v1_game_stat_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_history_v1_game_stat_proto_goTypes = []any{
	(*GetUserStatRequest)(nil),    // 0: baccarat.v1.GetUserStatRequest
	(*GetUserStatSnapshot)(nil),   // 1: baccarat.v1.GetUserStatSnapshot
	(*BehaviorProfile)(nil),       // 2: baccarat.v1.BehaviorProfile
	(*GetUserStatReply)(nil),      // 3: baccarat.v1.GetUserStatReply
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_history_v1_game_stat_proto_depIdxs = []int32{
	4, // 0: baccarat.v1.GetUserStatRequest.startTime:type_name -> google.protobuf.Timestamp
	4, // 1: baccarat.v1.GetUserStatRequest.endTime:type_name -> google.protobuf.Timestamp
	1, // 2: baccarat.v1.GetUserStatReply.recentSnapshot:type_name -> baccarat.v1.GetUserStatSnapshot
	1, // 3: baccarat.v1.GetUserStatReply.todaySnapshot:type_name -> baccarat.v1.GetUserStatSnapshot
	2, // 4: baccarat.v1.GetUserStatReply.behavior:type_name -> baccarat.v1.BehaviorProfile
	0, // 5: baccarat.v1.GameStatApi.GetUserStat:input_type -> baccarat.v1.GetUserStatRequest
	3, // 6: baccarat.v1.GameStatApi.GetUserStat:output_type -> baccarat.v1.GetUserStatReply
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_history_v1_game_stat_proto_init() }
func file_history_v1_game_stat_proto_init() {
	if File_history_v1_game_stat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_history_v1_game_stat_proto_rawDesc), len(file_history_v1_game_stat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_history_v1_game_stat_proto_goTypes,
		DependencyIndexes: file_history_v1_game_stat_proto_depIdxs,
		MessageInfos:      file_history_v1_game_stat_proto_msgTypes,
	}.Build()
	File_history_v1_game_stat_proto = out.File
	file_history_v1_game_stat_proto_goTypes = nil
	file_history_v1_game_stat_proto_depIdxs = nil
}
