// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: api/history/v1/game_bet_config.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetGameBetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`         //appid
	GameBrand     string                 `protobuf:"bytes,2,opt,name=gameBrand,proto3" json:"gameBrand,omitempty"` //游戏品牌
	GameId        string                 `protobuf:"bytes,3,opt,name=gameId,proto3" json:"gameId,omitempty"`       //游戏id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameBetConfigRequest) Reset() {
	*x = GetGameBetConfigRequest{}
	mi := &file_api_history_v1_game_bet_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameBetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameBetConfigRequest) ProtoMessage() {}

func (x *GetGameBetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_history_v1_game_bet_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameBetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetGameBetConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_history_v1_game_bet_config_proto_rawDescGZIP(), []int{0}
}

func (x *GetGameBetConfigRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GetGameBetConfigRequest) GetGameBrand() string {
	if x != nil {
		return x.GameBrand
	}
	return ""
}

func (x *GetGameBetConfigRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type GetGameBetConfigReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BetConfig     *GameBetConfig         `protobuf:"bytes,1,opt,name=betConfig,proto3" json:"betConfig,omitempty"`   // 游戏下注配置
	ConfigJson    string                 `protobuf:"bytes,2,opt,name=configJson,proto3" json:"configJson,omitempty"` //原始游戏下注配置json字符串
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameBetConfigReply) Reset() {
	*x = GetGameBetConfigReply{}
	mi := &file_api_history_v1_game_bet_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameBetConfigReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameBetConfigReply) ProtoMessage() {}

func (x *GetGameBetConfigReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_history_v1_game_bet_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameBetConfigReply.ProtoReflect.Descriptor instead.
func (*GetGameBetConfigReply) Descriptor() ([]byte, []int) {
	return file_api_history_v1_game_bet_config_proto_rawDescGZIP(), []int{1}
}

func (x *GetGameBetConfigReply) GetBetConfig() *GameBetConfig {
	if x != nil {
		return x.BetConfig
	}
	return nil
}

func (x *GetGameBetConfigReply) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

type GameBetConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinBet        float64                `protobuf:"fixed64,1,opt,name=minBet,proto3" json:"minBet,omitempty"`                // 最小下注金额
	MaxBet        float64                `protobuf:"fixed64,2,opt,name=maxBet,proto3" json:"maxBet,omitempty"`                // 最大下注金额
	DefaultBet    float64                `protobuf:"fixed64,3,opt,name=defaultBet,proto3" json:"defaultBet,omitempty"`        // 默认下注金额
	MaxWinLimit   float64                `protobuf:"fixed64,4,opt,name=maxWinLimit,proto3" json:"maxWinLimit,omitempty"`      // 最大中奖金额
	BetOptions    []float64              `protobuf:"fixed64,5,rep,packed,name=betOptions,proto3" json:"betOptions,omitempty"` // 下注选项
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameBetConfig) Reset() {
	*x = GameBetConfig{}
	mi := &file_api_history_v1_game_bet_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameBetConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameBetConfig) ProtoMessage() {}

func (x *GameBetConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_history_v1_game_bet_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameBetConfig.ProtoReflect.Descriptor instead.
func (*GameBetConfig) Descriptor() ([]byte, []int) {
	return file_api_history_v1_game_bet_config_proto_rawDescGZIP(), []int{2}
}

func (x *GameBetConfig) GetMinBet() float64 {
	if x != nil {
		return x.MinBet
	}
	return 0
}

func (x *GameBetConfig) GetMaxBet() float64 {
	if x != nil {
		return x.MaxBet
	}
	return 0
}

func (x *GameBetConfig) GetDefaultBet() float64 {
	if x != nil {
		return x.DefaultBet
	}
	return 0
}

func (x *GameBetConfig) GetMaxWinLimit() float64 {
	if x != nil {
		return x.MaxWinLimit
	}
	return 0
}

func (x *GameBetConfig) GetBetOptions() []float64 {
	if x != nil {
		return x.BetOptions
	}
	return nil
}

var File_api_history_v1_game_bet_config_proto protoreflect.FileDescriptor

const file_api_history_v1_game_bet_config_proto_rawDesc = "" +
	"\n" +
	"$api/history/v1/game_bet_config.proto\x12\x12game_bet_config.v1\"e\n" +
	"\x17GetGameBetConfigRequest\x12\x14\n" +
	"\x05appId\x18\x01 \x01(\tR\x05appId\x12\x1c\n" +
	"\tgameBrand\x18\x02 \x01(\tR\tgameBrand\x12\x16\n" +
	"\x06gameId\x18\x03 \x01(\tR\x06gameId\"x\n" +
	"\x15GetGameBetConfigReply\x12?\n" +
	"\tbetConfig\x18\x01 \x01(\v2!.game_bet_config.v1.GameBetConfigR\tbetConfig\x12\x1e\n" +
	"\n" +
	"configJson\x18\x02 \x01(\tR\n" +
	"configJson\"\xa1\x01\n" +
	"\rGameBetConfig\x12\x16\n" +
	"\x06minBet\x18\x01 \x01(\x01R\x06minBet\x12\x16\n" +
	"\x06maxBet\x18\x02 \x01(\x01R\x06maxBet\x12\x1e\n" +
	"\n" +
	"defaultBet\x18\x03 \x01(\x01R\n" +
	"defaultBet\x12 \n" +
	"\vmaxWinLimit\x18\x04 \x01(\x01R\vmaxWinLimit\x12\x1e\n" +
	"\n" +
	"betOptions\x18\x05 \x03(\x01R\n" +
	"betOptions2~\n" +
	"\x10GameBetConfigApi\x12j\n" +
	"\x10GetGameBetConfig\x12+.game_bet_config.v1.GetGameBetConfigRequest\x1a).game_bet_config.v1.GetGameBetConfigReplyBt\n" +
	"!dev.kratos.api.game_bet_config.v1B\x14GameBetConfigProtoV1P\x01Z7cn.qingdou.server/game_common/api/game_bet_config/v1;v1b\x06proto3"

var (
	file_api_history_v1_game_bet_config_proto_rawDescOnce sync.Once
	file_api_history_v1_game_bet_config_proto_rawDescData []byte
)

func file_api_history_v1_game_bet_config_proto_rawDescGZIP() []byte {
	file_api_history_v1_game_bet_config_proto_rawDescOnce.Do(func() {
		file_api_history_v1_game_bet_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_history_v1_game_bet_config_proto_rawDesc), len(file_api_history_v1_game_bet_config_proto_rawDesc)))
	})
	return file_api_history_v1_game_bet_config_proto_rawDescData
}

var file_api_history_v1_game_bet_config_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_history_v1_game_bet_config_proto_goTypes = []any{
	(*GetGameBetConfigRequest)(nil), // 0: game_bet_config.v1.GetGameBetConfigRequest
	(*GetGameBetConfigReply)(nil),   // 1: game_bet_config.v1.GetGameBetConfigReply
	(*GameBetConfig)(nil),           // 2: game_bet_config.v1.GameBetConfig
}
var file_api_history_v1_game_bet_config_proto_depIdxs = []int32{
	2, // 0: game_bet_config.v1.GetGameBetConfigReply.betConfig:type_name -> game_bet_config.v1.GameBetConfig
	0, // 1: game_bet_config.v1.GameBetConfigApi.GetGameBetConfig:input_type -> game_bet_config.v1.GetGameBetConfigRequest
	1, // 2: game_bet_config.v1.GameBetConfigApi.GetGameBetConfig:output_type -> game_bet_config.v1.GetGameBetConfigReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_history_v1_game_bet_config_proto_init() }
func file_api_history_v1_game_bet_config_proto_init() {
	if File_api_history_v1_game_bet_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_history_v1_game_bet_config_proto_rawDesc), len(file_api_history_v1_game_bet_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_history_v1_game_bet_config_proto_goTypes,
		DependencyIndexes: file_api_history_v1_game_bet_config_proto_depIdxs,
		MessageInfos:      file_api_history_v1_game_bet_config_proto_msgTypes,
	}.Build()
	File_api_history_v1_game_bet_config_proto = out.File
	file_api_history_v1_game_bet_config_proto_goTypes = nil
	file_api_history_v1_game_bet_config_proto_depIdxs = nil
}
