// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: history/v1/history.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameHistoryListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`                                 //appid
	GameBrand     string                 `protobuf:"bytes,2,opt,name=gameBrand,proto3" json:"gameBrand,omitempty"`                         //游戏品牌
	GameId        string                 `protobuf:"bytes,3,opt,name=gameId,proto3" json:"gameId,omitempty"`                               //游戏id
	PlayerId      string                 `protobuf:"bytes,4,opt,name=playerId,proto3" json:"playerId,omitempty"`                           //账号id
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                               // 数据的状态，空为所有
	StartTime     int64                  `protobuf:"varint,6,opt,name=startTime,proto3" json:"startTime,omitempty"`                        // 开始时间戳（必传, 单位：毫秒）
	EndTime       int64                  `protobuf:"varint,7,opt,name=endTime,proto3" json:"endTime,omitempty"`                            // 结束时间戳（必传, 单位：毫秒）
	PageIndex     int32                  `protobuf:"varint,8,opt,name=page_index,json=pageIndex,proto3" json:"page_index,omitempty"`       // 分页索引
	PageSize      int32                  `protobuf:"varint,9,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`          //  一页的数量
	NeedTotalNum  bool                   `protobuf:"varint,12,opt,name=needTotalNum,proto3" json:"needTotalNum,omitempty"`                 //是否需要返回历史记录总条数据
	IsAsc         bool                   `protobuf:"varint,10,opt,name=is_asc,json=isAsc,proto3" json:"is_asc,omitempty"`                  // 是否升序 (默认是倒序)
	NoGameData    bool                   `protobuf:"varint,11,opt,name=no_game_data,json=noGameData,proto3" json:"no_game_data,omitempty"` //不要返回游戏数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameHistoryListRequest) Reset() {
	*x = GameHistoryListRequest{}
	mi := &file_history_v1_history_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameHistoryListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameHistoryListRequest) ProtoMessage() {}

func (x *GameHistoryListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_history_v1_history_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameHistoryListRequest.ProtoReflect.Descriptor instead.
func (*GameHistoryListRequest) Descriptor() ([]byte, []int) {
	return file_history_v1_history_proto_rawDescGZIP(), []int{0}
}

func (x *GameHistoryListRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GameHistoryListRequest) GetGameBrand() string {
	if x != nil {
		return x.GameBrand
	}
	return ""
}

func (x *GameHistoryListRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GameHistoryListRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *GameHistoryListRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GameHistoryListRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GameHistoryListRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *GameHistoryListRequest) GetPageIndex() int32 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

func (x *GameHistoryListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GameHistoryListRequest) GetNeedTotalNum() bool {
	if x != nil {
		return x.NeedTotalNum
	}
	return false
}

func (x *GameHistoryListRequest) GetIsAsc() bool {
	if x != nil {
		return x.IsAsc
	}
	return false
}

func (x *GameHistoryListRequest) GetNoGameData() bool {
	if x != nil {
		return x.NoGameData
	}
	return false
}

type GameHistoryListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*GameHistory         `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`                             //记录列表
	PageIndex     int32                  `protobuf:"varint,2,opt,name=page_index,json=pageIndex,proto3" json:"page_index,omitempty"` // 分页索引
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`    //  一页的数量
	TotalNum      int64                  `protobuf:"varint,4,opt,name=totalNum,proto3" json:"totalNum,omitempty"`                    // 总条数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameHistoryListReply) Reset() {
	*x = GameHistoryListReply{}
	mi := &file_history_v1_history_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameHistoryListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameHistoryListReply) ProtoMessage() {}

func (x *GameHistoryListReply) ProtoReflect() protoreflect.Message {
	mi := &file_history_v1_history_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameHistoryListReply.ProtoReflect.Descriptor instead.
func (*GameHistoryListReply) Descriptor() ([]byte, []int) {
	return file_history_v1_history_proto_rawDescGZIP(), []int{1}
}

func (x *GameHistoryListReply) GetList() []*GameHistory {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GameHistoryListReply) GetPageIndex() int32 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

func (x *GameHistoryListReply) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GameHistoryListReply) GetTotalNum() int64 {
	if x != nil {
		return x.TotalNum
	}
	return 0
}

type GameHistoryDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`           //appid
	GameBrand     string                 `protobuf:"bytes,2,opt,name=gameBrand,proto3" json:"gameBrand,omitempty"`   //游戏品牌
	GameId        string                 `protobuf:"bytes,3,opt,name=gameId,proto3" json:"gameId,omitempty"`         //游戏id
	PlayerId      string                 `protobuf:"bytes,4,opt,name=playerId,proto3" json:"playerId,omitempty"`     //账号id
	RoundId       string                 `protobuf:"bytes,5,opt,name=roundId,proto3" json:"roundId,omitempty"`       //局号
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`         // 数据的状态，空为所有
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=createTime,proto3" json:"createTime,omitempty"` // 创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameHistoryDetailRequest) Reset() {
	*x = GameHistoryDetailRequest{}
	mi := &file_history_v1_history_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameHistoryDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameHistoryDetailRequest) ProtoMessage() {}

func (x *GameHistoryDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_history_v1_history_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameHistoryDetailRequest.ProtoReflect.Descriptor instead.
func (*GameHistoryDetailRequest) Descriptor() ([]byte, []int) {
	return file_history_v1_history_proto_rawDescGZIP(), []int{2}
}

func (x *GameHistoryDetailRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GameHistoryDetailRequest) GetGameBrand() string {
	if x != nil {
		return x.GameBrand
	}
	return ""
}

func (x *GameHistoryDetailRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GameHistoryDetailRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *GameHistoryDetailRequest) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *GameHistoryDetailRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GameHistoryDetailRequest) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

type GameHistoryDetailReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*GameHistory         `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"` //记录列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameHistoryDetailReply) Reset() {
	*x = GameHistoryDetailReply{}
	mi := &file_history_v1_history_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameHistoryDetailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameHistoryDetailReply) ProtoMessage() {}

func (x *GameHistoryDetailReply) ProtoReflect() protoreflect.Message {
	mi := &file_history_v1_history_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameHistoryDetailReply.ProtoReflect.Descriptor instead.
func (*GameHistoryDetailReply) Descriptor() ([]byte, []int) {
	return file_history_v1_history_proto_rawDescGZIP(), []int{3}
}

func (x *GameHistoryDetailReply) GetData() []*GameHistory {
	if x != nil {
		return x.Data
	}
	return nil
}

type GameHistory struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Bet              float64                `protobuf:"fixed64,1,opt,name=bet,proto3" json:"bet,omitempty"`                                                      //下注
	Win              float64                `protobuf:"fixed64,2,opt,name=win,proto3" json:"win,omitempty"`                                                      //赢钱
	RoundId          string                 `protobuf:"bytes,3,opt,name=roundId,proto3" json:"roundId,omitempty"`                                                //局号
	OrderNo          string                 `protobuf:"bytes,4,opt,name=orderNo,proto3" json:"orderNo,omitempty"`                                                //流水号
	PlayerId         string                 `protobuf:"bytes,5,opt,name=playerId,proto3" json:"playerId,omitempty"`                                              //账号id
	AppId            string                 `protobuf:"bytes,6,opt,name=appId,proto3" json:"appId,omitempty"`                                                    //appid
	GameBrand        string                 `protobuf:"bytes,7,opt,name=gameBrand,proto3" json:"gameBrand,omitempty"`                                            //游戏品牌
	GameId           string                 `protobuf:"bytes,8,opt,name=gameId,proto3" json:"gameId,omitempty"`                                                  //游戏id
	Sample           string                 `protobuf:"bytes,9,opt,name=sample,proto3" json:"sample,omitempty"`                                                  // 样本数据
	Note             string                 `protobuf:"bytes,10,opt,name=note,proto3" json:"note,omitempty"`                                                     // 备注
	Rtp              string                 `protobuf:"bytes,11,opt,name=rtp,proto3" json:"rtp,omitempty"`                                                       // 实时赔率
	Status           string                 `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`                                                 // 数据的状态，空为所有
	WinBalance       float64                `protobuf:"fixed64,18,opt,name=win_balance,json=winBalance,proto3" json:"win_balance,omitempty"`                     //结算后的金额
	AfterBetBalance  float64                `protobuf:"fixed64,19,opt,name=after_bet_balance,json=afterBetBalance,proto3" json:"after_bet_balance,omitempty"`    // 下注后的金额
	BeforeBetBalance float64                `protobuf:"fixed64,20,opt,name=before_bet_balance,json=beforeBetBalance,proto3" json:"before_bet_balance,omitempty"` // 下注前的金额
	CreateTime       *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=createTime,proto3" json:"createTime,omitempty"`                                         // 创建时间
	BetTime          *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=betTime,proto3" json:"betTime,omitempty"`                                               // 下注时间
	WinTime          *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=winTime,proto3" json:"winTime,omitempty"`                                               // 赢钱时间
	GameData         []byte                 `protobuf:"bytes,16,opt,name=GameData,proto3" json:"GameData,omitempty"`
	Compress         int32                  `protobuf:"varint,17,opt,name=compress,proto3" json:"compress,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GameHistory) Reset() {
	*x = GameHistory{}
	mi := &file_history_v1_history_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameHistory) ProtoMessage() {}

func (x *GameHistory) ProtoReflect() protoreflect.Message {
	mi := &file_history_v1_history_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameHistory.ProtoReflect.Descriptor instead.
func (*GameHistory) Descriptor() ([]byte, []int) {
	return file_history_v1_history_proto_rawDescGZIP(), []int{4}
}

func (x *GameHistory) GetBet() float64 {
	if x != nil {
		return x.Bet
	}
	return 0
}

func (x *GameHistory) GetWin() float64 {
	if x != nil {
		return x.Win
	}
	return 0
}

func (x *GameHistory) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *GameHistory) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *GameHistory) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *GameHistory) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GameHistory) GetGameBrand() string {
	if x != nil {
		return x.GameBrand
	}
	return ""
}

func (x *GameHistory) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GameHistory) GetSample() string {
	if x != nil {
		return x.Sample
	}
	return ""
}

func (x *GameHistory) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *GameHistory) GetRtp() string {
	if x != nil {
		return x.Rtp
	}
	return ""
}

func (x *GameHistory) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GameHistory) GetWinBalance() float64 {
	if x != nil {
		return x.WinBalance
	}
	return 0
}

func (x *GameHistory) GetAfterBetBalance() float64 {
	if x != nil {
		return x.AfterBetBalance
	}
	return 0
}

func (x *GameHistory) GetBeforeBetBalance() float64 {
	if x != nil {
		return x.BeforeBetBalance
	}
	return 0
}

func (x *GameHistory) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *GameHistory) GetBetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.BetTime
	}
	return nil
}

func (x *GameHistory) GetWinTime() *timestamppb.Timestamp {
	if x != nil {
		return x.WinTime
	}
	return nil
}

func (x *GameHistory) GetGameData() []byte {
	if x != nil {
		return x.GameData
	}
	return nil
}

func (x *GameHistory) GetCompress() int32 {
	if x != nil {
		return x.Compress
	}
	return 0
}

type GameHistoryByTimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`          //appid
	GameBrand     string                 `protobuf:"bytes,2,opt,name=gameBrand,proto3" json:"gameBrand,omitempty"`  //游戏品牌
	GameId        string                 `protobuf:"bytes,3,opt,name=gameId,proto3" json:"gameId,omitempty"`        //游戏id
	PlayerId      string                 `protobuf:"bytes,4,opt,name=playerId,proto3" json:"playerId,omitempty"`    //账号id
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`        // 数据的状态，空为所有
	StartTime     int64                  `protobuf:"varint,6,opt,name=startTime,proto3" json:"startTime,omitempty"` // 开始时间戳（单位：毫秒）
	EndTime       int64                  `protobuf:"varint,7,opt,name=endTime,proto3" json:"endTime,omitempty"`     // 结束时间戳（单位：毫秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameHistoryByTimeRequest) Reset() {
	*x = GameHistoryByTimeRequest{}
	mi := &file_history_v1_history_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameHistoryByTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameHistoryByTimeRequest) ProtoMessage() {}

func (x *GameHistoryByTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_history_v1_history_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameHistoryByTimeRequest.ProtoReflect.Descriptor instead.
func (*GameHistoryByTimeRequest) Descriptor() ([]byte, []int) {
	return file_history_v1_history_proto_rawDescGZIP(), []int{5}
}

func (x *GameHistoryByTimeRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GameHistoryByTimeRequest) GetGameBrand() string {
	if x != nil {
		return x.GameBrand
	}
	return ""
}

func (x *GameHistoryByTimeRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GameHistoryByTimeRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *GameHistoryByTimeRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GameHistoryByTimeRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GameHistoryByTimeRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type GameHistoryByTimeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*GameHistory         `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`            //记录列表
	StartTime     int64                  `protobuf:"varint,2,opt,name=startTime,proto3" json:"startTime,omitempty"` // 开始时间戳（单位：毫秒）
	EndTime       int64                  `protobuf:"varint,3,opt,name=endTime,proto3" json:"endTime,omitempty"`     // 结束时间戳（单位：毫秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameHistoryByTimeReply) Reset() {
	*x = GameHistoryByTimeReply{}
	mi := &file_history_v1_history_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameHistoryByTimeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameHistoryByTimeReply) ProtoMessage() {}

func (x *GameHistoryByTimeReply) ProtoReflect() protoreflect.Message {
	mi := &file_history_v1_history_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameHistoryByTimeReply.ProtoReflect.Descriptor instead.
func (*GameHistoryByTimeReply) Descriptor() ([]byte, []int) {
	return file_history_v1_history_proto_rawDescGZIP(), []int{6}
}

func (x *GameHistoryByTimeReply) GetList() []*GameHistory {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GameHistoryByTimeReply) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GameHistoryByTimeReply) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type GetTotalBetAndWinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`          //appid
	GameBrand     string                 `protobuf:"bytes,2,opt,name=gameBrand,proto3" json:"gameBrand,omitempty"`  //游戏品牌
	GameId        string                 `protobuf:"bytes,3,opt,name=gameId,proto3" json:"gameId,omitempty"`        //游戏id
	PlayerId      string                 `protobuf:"bytes,4,opt,name=playerId,proto3" json:"playerId,omitempty"`    //账号id
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`        // 数据的状态，空为所有
	StartTime     int64                  `protobuf:"varint,6,opt,name=startTime,proto3" json:"startTime,omitempty"` // 开始时间戳（单位：毫秒）
	EndTime       int64                  `protobuf:"varint,7,opt,name=endTime,proto3" json:"endTime,omitempty"`     // 结束时间戳（单位：毫秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTotalBetAndWinRequest) Reset() {
	*x = GetTotalBetAndWinRequest{}
	mi := &file_history_v1_history_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTotalBetAndWinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTotalBetAndWinRequest) ProtoMessage() {}

func (x *GetTotalBetAndWinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_history_v1_history_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTotalBetAndWinRequest.ProtoReflect.Descriptor instead.
func (*GetTotalBetAndWinRequest) Descriptor() ([]byte, []int) {
	return file_history_v1_history_proto_rawDescGZIP(), []int{7}
}

func (x *GetTotalBetAndWinRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GetTotalBetAndWinRequest) GetGameBrand() string {
	if x != nil {
		return x.GameBrand
	}
	return ""
}

func (x *GetTotalBetAndWinRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GetTotalBetAndWinRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *GetTotalBetAndWinRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetTotalBetAndWinRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetTotalBetAndWinRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type GetTotalBetAndWinReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalBet      float64                `protobuf:"fixed64,1,opt,name=totalBet,proto3" json:"totalBet,omitempty"`      // 总下注
	TotalWin      float64                `protobuf:"fixed64,2,opt,name=totalWin,proto3" json:"totalWin,omitempty"`      // 总赢钱
	RecordCount   int64                  `protobuf:"varint,3,opt,name=recordCount,proto3" json:"recordCount,omitempty"` // 记录数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTotalBetAndWinReply) Reset() {
	*x = GetTotalBetAndWinReply{}
	mi := &file_history_v1_history_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTotalBetAndWinReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTotalBetAndWinReply) ProtoMessage() {}

func (x *GetTotalBetAndWinReply) ProtoReflect() protoreflect.Message {
	mi := &file_history_v1_history_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTotalBetAndWinReply.ProtoReflect.Descriptor instead.
func (*GetTotalBetAndWinReply) Descriptor() ([]byte, []int) {
	return file_history_v1_history_proto_rawDescGZIP(), []int{8}
}

func (x *GetTotalBetAndWinReply) GetTotalBet() float64 {
	if x != nil {
		return x.TotalBet
	}
	return 0
}

func (x *GetTotalBetAndWinReply) GetTotalWin() float64 {
	if x != nil {
		return x.TotalWin
	}
	return 0
}

func (x *GetTotalBetAndWinReply) GetRecordCount() int64 {
	if x != nil {
		return x.RecordCount
	}
	return 0
}

// 创建一条记录 （创建的状态为init状态）
type CreateGameRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`         //appid
	GameBrand     string                 `protobuf:"bytes,2,opt,name=gameBrand,proto3" json:"gameBrand,omitempty"` //游戏品牌
	GameId        string                 `protobuf:"bytes,3,opt,name=gameId,proto3" json:"gameId,omitempty"`       //游戏id
	PlayerId      string                 `protobuf:"bytes,4,opt,name=playerId,proto3" json:"playerId,omitempty"`   //账号id
	RoundId       string                 `protobuf:"bytes,5,opt,name=roundId,proto3" json:"roundId,omitempty"`     //游戏回合, 长度64以內。
	OrderNo       string                 `protobuf:"bytes,6,opt,name=orderNo,proto3" json:"orderNo,omitempty"`     // 交易id, 长度64以內。
	RTP           string                 `protobuf:"bytes,7,opt,name=RTP,proto3" json:"RTP,omitempty"`
	Bet           float64                `protobuf:"fixed64,8,opt,name=bet,proto3" json:"bet,omitempty"`               //下注值
	RoundMoudle   string                 `protobuf:"bytes,9,opt,name=roundMoudle,proto3" json:"roundMoudle,omitempty"` //游戏的模式
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=createTime,proto3" json:"createTime,omitempty"`  // 状态时间
	PreOrderNo    string                 `protobuf:"bytes,11,opt,name=preOrderNo,proto3" json:"preOrderNo,omitempty"`  //上一把下注交易id, 长度64以內。
	Currency      string                 `protobuf:"bytes,12,opt,name=currency,proto3" json:"currency,omitempty"`      // 货币
	IsFree        bool                   `protobuf:"varint,13,opt,name=isFree,proto3" json:"isFree,omitempty"`         //免费模式
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameRecordRequest) Reset() {
	*x = CreateGameRecordRequest{}
	mi := &file_history_v1_history_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRecordRequest) ProtoMessage() {}

func (x *CreateGameRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_history_v1_history_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRecordRequest.ProtoReflect.Descriptor instead.
func (*CreateGameRecordRequest) Descriptor() ([]byte, []int) {
	return file_history_v1_history_proto_rawDescGZIP(), []int{9}
}

func (x *CreateGameRecordRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *CreateGameRecordRequest) GetGameBrand() string {
	if x != nil {
		return x.GameBrand
	}
	return ""
}

func (x *CreateGameRecordRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *CreateGameRecordRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *CreateGameRecordRequest) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *CreateGameRecordRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *CreateGameRecordRequest) GetRTP() string {
	if x != nil {
		return x.RTP
	}
	return ""
}

func (x *CreateGameRecordRequest) GetBet() float64 {
	if x != nil {
		return x.Bet
	}
	return 0
}

func (x *CreateGameRecordRequest) GetRoundMoudle() string {
	if x != nil {
		return x.RoundMoudle
	}
	return ""
}

func (x *CreateGameRecordRequest) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *CreateGameRecordRequest) GetPreOrderNo() string {
	if x != nil {
		return x.PreOrderNo
	}
	return ""
}

func (x *CreateGameRecordRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateGameRecordRequest) GetIsFree() bool {
	if x != nil {
		return x.IsFree
	}
	return false
}

type CreateGameRecordReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`        // 数据分配的表名
	RecordId      uint64                 `protobuf:"varint,2,opt,name=recordId,proto3" json:"recordId,omitempty"` //记录的id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameRecordReply) Reset() {
	*x = CreateGameRecordReply{}
	mi := &file_history_v1_history_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameRecordReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRecordReply) ProtoMessage() {}

func (x *CreateGameRecordReply) ProtoReflect() protoreflect.Message {
	mi := &file_history_v1_history_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRecordReply.ProtoReflect.Descriptor instead.
func (*CreateGameRecordReply) Descriptor() ([]byte, []int) {
	return file_history_v1_history_proto_rawDescGZIP(), []int{10}
}

func (x *CreateGameRecordReply) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *CreateGameRecordReply) GetRecordId() uint64 {
	if x != nil {
		return x.RecordId
	}
	return 0
}

// 下注的消息结构
type SetGameRecordStatusBetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`                   // 数据分配的表名
	RecordId      uint64                 `protobuf:"varint,2,opt,name=recordId,proto3" json:"recordId,omitempty"`            //记录的id
	BetTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=betTime,proto3" json:"betTime,omitempty"`               // 状态时间
	BeforeBalance float64                `protobuf:"fixed64,4,opt,name=beforeBalance,proto3" json:"beforeBalance,omitempty"` //下注前的钱
	AfterBalance  float64                `protobuf:"fixed64,5,opt,name=afterBalance,proto3" json:"afterBalance,omitempty"`   //下注后的钱
	TraceId       string                 `protobuf:"bytes,6,opt,name=traceId,proto3" json:"traceId,omitempty"`               //traceId
	// 如果未知 recordId 和tableName. 也可以使用使用下参数定位
	AppId         string `protobuf:"bytes,7,opt,name=appId,proto3" json:"appId,omitempty"`         //appid
	GameBrand     string `protobuf:"bytes,8,opt,name=gameBrand,proto3" json:"gameBrand,omitempty"` //游戏品牌
	RoundId       string `protobuf:"bytes,9,opt,name=roundId,proto3" json:"roundId,omitempty"`     //游戏id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGameRecordStatusBetRequest) Reset() {
	*x = SetGameRecordStatusBetRequest{}
	mi := &file_history_v1_history_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGameRecordStatusBetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGameRecordStatusBetRequest) ProtoMessage() {}

func (x *SetGameRecordStatusBetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_history_v1_history_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGameRecordStatusBetRequest.ProtoReflect.Descriptor instead.
func (*SetGameRecordStatusBetRequest) Descriptor() ([]byte, []int) {
	return file_history_v1_history_proto_rawDescGZIP(), []int{11}
}

func (x *SetGameRecordStatusBetRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *SetGameRecordStatusBetRequest) GetRecordId() uint64 {
	if x != nil {
		return x.RecordId
	}
	return 0
}

func (x *SetGameRecordStatusBetRequest) GetBetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.BetTime
	}
	return nil
}

func (x *SetGameRecordStatusBetRequest) GetBeforeBalance() float64 {
	if x != nil {
		return x.BeforeBalance
	}
	return 0
}

func (x *SetGameRecordStatusBetRequest) GetAfterBalance() float64 {
	if x != nil {
		return x.AfterBalance
	}
	return 0
}

func (x *SetGameRecordStatusBetRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *SetGameRecordStatusBetRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *SetGameRecordStatusBetRequest) GetGameBrand() string {
	if x != nil {
		return x.GameBrand
	}
	return ""
}

func (x *SetGameRecordStatusBetRequest) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

type SetGameRecordStatusBetReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGameRecordStatusBetReply) Reset() {
	*x = SetGameRecordStatusBetReply{}
	mi := &file_history_v1_history_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGameRecordStatusBetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGameRecordStatusBetReply) ProtoMessage() {}

func (x *SetGameRecordStatusBetReply) ProtoReflect() protoreflect.Message {
	mi := &file_history_v1_history_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGameRecordStatusBetReply.ProtoReflect.Descriptor instead.
func (*SetGameRecordStatusBetReply) Descriptor() ([]byte, []int) {
	return file_history_v1_history_proto_rawDescGZIP(), []int{12}
}

// 结算的消息结构
type SetGameRecordStatusWinRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Table      string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`             // 数据分配的表名
	RecordId   uint64                 `protobuf:"varint,2,opt,name=recordId,proto3" json:"recordId,omitempty"`      //记录的id
	Win        float64                `protobuf:"fixed64,3,opt,name=win,proto3" json:"win,omitempty"`               //赢钱数量
	WinTime    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=winTime,proto3" json:"winTime,omitempty"`         // 结算时间
	WinBalance float64                `protobuf:"fixed64,5,opt,name=winBalance,proto3" json:"winBalance,omitempty"` //最终结算后的钱
	GameData   []byte                 `protobuf:"bytes,6,opt,name=GameData,proto3" json:"GameData,omitempty"`       // 游戏数据
	Compress   uint32                 `protobuf:"varint,7,opt,name=compress,proto3" json:"compress,omitempty"`      //数据的压缩方式
	TraceId    string                 `protobuf:"bytes,8,opt,name=traceId,proto3" json:"traceId,omitempty"`         //traceId
	Simple     string                 `protobuf:"bytes,9,opt,name=simple,proto3" json:"simple,omitempty"`           // 数据样本信息
	// 如果未知 recordId 和tableName. 也可以使用使用下参数定位
	AppId         string `protobuf:"bytes,10,opt,name=appId,proto3" json:"appId,omitempty"`         //appid
	GameBrand     string `protobuf:"bytes,11,opt,name=gameBrand,proto3" json:"gameBrand,omitempty"` //游戏品牌
	RoundId       string `protobuf:"bytes,12,opt,name=roundId,proto3" json:"roundId,omitempty"`     //游戏id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGameRecordStatusWinRequest) Reset() {
	*x = SetGameRecordStatusWinRequest{}
	mi := &file_history_v1_history_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGameRecordStatusWinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGameRecordStatusWinRequest) ProtoMessage() {}

func (x *SetGameRecordStatusWinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_history_v1_history_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGameRecordStatusWinRequest.ProtoReflect.Descriptor instead.
func (*SetGameRecordStatusWinRequest) Descriptor() ([]byte, []int) {
	return file_history_v1_history_proto_rawDescGZIP(), []int{13}
}

func (x *SetGameRecordStatusWinRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *SetGameRecordStatusWinRequest) GetRecordId() uint64 {
	if x != nil {
		return x.RecordId
	}
	return 0
}

func (x *SetGameRecordStatusWinRequest) GetWin() float64 {
	if x != nil {
		return x.Win
	}
	return 0
}

func (x *SetGameRecordStatusWinRequest) GetWinTime() *timestamppb.Timestamp {
	if x != nil {
		return x.WinTime
	}
	return nil
}

func (x *SetGameRecordStatusWinRequest) GetWinBalance() float64 {
	if x != nil {
		return x.WinBalance
	}
	return 0
}

func (x *SetGameRecordStatusWinRequest) GetGameData() []byte {
	if x != nil {
		return x.GameData
	}
	return nil
}

func (x *SetGameRecordStatusWinRequest) GetCompress() uint32 {
	if x != nil {
		return x.Compress
	}
	return 0
}

func (x *SetGameRecordStatusWinRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *SetGameRecordStatusWinRequest) GetSimple() string {
	if x != nil {
		return x.Simple
	}
	return ""
}

func (x *SetGameRecordStatusWinRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *SetGameRecordStatusWinRequest) GetGameBrand() string {
	if x != nil {
		return x.GameBrand
	}
	return ""
}

func (x *SetGameRecordStatusWinRequest) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

type SetGameRecordStatusWinReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGameRecordStatusWinReply) Reset() {
	*x = SetGameRecordStatusWinReply{}
	mi := &file_history_v1_history_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGameRecordStatusWinReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGameRecordStatusWinReply) ProtoMessage() {}

func (x *SetGameRecordStatusWinReply) ProtoReflect() protoreflect.Message {
	mi := &file_history_v1_history_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGameRecordStatusWinReply.ProtoReflect.Descriptor instead.
func (*SetGameRecordStatusWinReply) Descriptor() ([]byte, []int) {
	return file_history_v1_history_proto_rawDescGZIP(), []int{14}
}

// 更新为退款状态
type SetGameRecordStatusRefundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`                   // 数据分配的表名
	RecordId      uint64                 `protobuf:"varint,2,opt,name=recordId,proto3" json:"recordId,omitempty"`            //记录的id
	RefundTime    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=refundTime,proto3" json:"refundTime,omitempty"`         // 退款时间
	RefundReason  string                 `protobuf:"bytes,4,opt,name=refundReason,proto3" json:"refundReason,omitempty"`     // 退款原因
	RefundBalance float64                `protobuf:"fixed64,5,opt,name=refundBalance,proto3" json:"refundBalance,omitempty"` //最终结算后的钱
	TraceId       string                 `protobuf:"bytes,6,opt,name=traceId,proto3" json:"traceId,omitempty"`               //traceId
	Balance       float64                `protobuf:"fixed64,7,opt,name=balance,proto3" json:"balance,omitempty"`             //退款后的钱
	// 如果未知 recordId 和tableName. 也可以使用使用下参数定位
	AppId         string `protobuf:"bytes,8,opt,name=appId,proto3" json:"appId,omitempty"`         //appid
	GameBrand     string `protobuf:"bytes,9,opt,name=gameBrand,proto3" json:"gameBrand,omitempty"` //游戏品牌
	RoundId       string `protobuf:"bytes,10,opt,name=roundId,proto3" json:"roundId,omitempty"`    //游戏id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGameRecordStatusRefundRequest) Reset() {
	*x = SetGameRecordStatusRefundRequest{}
	mi := &file_history_v1_history_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGameRecordStatusRefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGameRecordStatusRefundRequest) ProtoMessage() {}

func (x *SetGameRecordStatusRefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_history_v1_history_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGameRecordStatusRefundRequest.ProtoReflect.Descriptor instead.
func (*SetGameRecordStatusRefundRequest) Descriptor() ([]byte, []int) {
	return file_history_v1_history_proto_rawDescGZIP(), []int{15}
}

func (x *SetGameRecordStatusRefundRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *SetGameRecordStatusRefundRequest) GetRecordId() uint64 {
	if x != nil {
		return x.RecordId
	}
	return 0
}

func (x *SetGameRecordStatusRefundRequest) GetRefundTime() *timestamppb.Timestamp {
	if x != nil {
		return x.RefundTime
	}
	return nil
}

func (x *SetGameRecordStatusRefundRequest) GetRefundReason() string {
	if x != nil {
		return x.RefundReason
	}
	return ""
}

func (x *SetGameRecordStatusRefundRequest) GetRefundBalance() float64 {
	if x != nil {
		return x.RefundBalance
	}
	return 0
}

func (x *SetGameRecordStatusRefundRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *SetGameRecordStatusRefundRequest) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *SetGameRecordStatusRefundRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *SetGameRecordStatusRefundRequest) GetGameBrand() string {
	if x != nil {
		return x.GameBrand
	}
	return ""
}

func (x *SetGameRecordStatusRefundRequest) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

type SetGameRecordStatusRefundReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGameRecordStatusRefundReply) Reset() {
	*x = SetGameRecordStatusRefundReply{}
	mi := &file_history_v1_history_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGameRecordStatusRefundReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGameRecordStatusRefundReply) ProtoMessage() {}

func (x *SetGameRecordStatusRefundReply) ProtoReflect() protoreflect.Message {
	mi := &file_history_v1_history_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGameRecordStatusRefundReply.ProtoReflect.Descriptor instead.
func (*SetGameRecordStatusRefundReply) Descriptor() ([]byte, []int) {
	return file_history_v1_history_proto_rawDescGZIP(), []int{16}
}

type SetGameRecordStatusErrorRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Table    string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`        // 数据分配的表名
	RecordId uint64                 `protobuf:"varint,2,opt,name=recordId,proto3" json:"recordId,omitempty"` //记录的id
	Reason   string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`      // 错误原因
	// 如果未知 recordId 和tableName. 也可以使用使用下参数定位
	AppId         string `protobuf:"bytes,4,opt,name=appId,proto3" json:"appId,omitempty"`         //appid
	GameBrand     string `protobuf:"bytes,5,opt,name=gameBrand,proto3" json:"gameBrand,omitempty"` //游戏品牌
	RoundId       string `protobuf:"bytes,6,opt,name=roundId,proto3" json:"roundId,omitempty"`     //游戏id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGameRecordStatusErrorRequest) Reset() {
	*x = SetGameRecordStatusErrorRequest{}
	mi := &file_history_v1_history_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGameRecordStatusErrorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGameRecordStatusErrorRequest) ProtoMessage() {}

func (x *SetGameRecordStatusErrorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_history_v1_history_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGameRecordStatusErrorRequest.ProtoReflect.Descriptor instead.
func (*SetGameRecordStatusErrorRequest) Descriptor() ([]byte, []int) {
	return file_history_v1_history_proto_rawDescGZIP(), []int{17}
}

func (x *SetGameRecordStatusErrorRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *SetGameRecordStatusErrorRequest) GetRecordId() uint64 {
	if x != nil {
		return x.RecordId
	}
	return 0
}

func (x *SetGameRecordStatusErrorRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SetGameRecordStatusErrorRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *SetGameRecordStatusErrorRequest) GetGameBrand() string {
	if x != nil {
		return x.GameBrand
	}
	return ""
}

func (x *SetGameRecordStatusErrorRequest) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

type SetGameRecordStatusErrorReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGameRecordStatusErrorReply) Reset() {
	*x = SetGameRecordStatusErrorReply{}
	mi := &file_history_v1_history_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGameRecordStatusErrorReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGameRecordStatusErrorReply) ProtoMessage() {}

func (x *SetGameRecordStatusErrorReply) ProtoReflect() protoreflect.Message {
	mi := &file_history_v1_history_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGameRecordStatusErrorReply.ProtoReflect.Descriptor instead.
func (*SetGameRecordStatusErrorReply) Descriptor() ([]byte, []int) {
	return file_history_v1_history_proto_rawDescGZIP(), []int{18}
}

var File_history_v1_history_proto protoreflect.FileDescriptor

const file_history_v1_history_proto_rawDesc = "" +
	"\n" +
	"\x18history/v1/history.proto\x12\vghistory.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe9\x02\n" +
	"\x16GameHistoryListRequest\x12\x14\n" +
	"\x05appId\x18\x01 \x01(\tR\x05appId\x12\x1c\n" +
	"\tgameBrand\x18\x02 \x01(\tR\tgameBrand\x12\x16\n" +
	"\x06gameId\x18\x03 \x01(\tR\x06gameId\x12\x1a\n" +
	"\bplayerId\x18\x04 \x01(\tR\bplayerId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1c\n" +
	"\tstartTime\x18\x06 \x01(\x03R\tstartTime\x12\x18\n" +
	"\aendTime\x18\a \x01(\x03R\aendTime\x12\x1d\n" +
	"\n" +
	"page_index\x18\b \x01(\x05R\tpageIndex\x12\x1b\n" +
	"\tpage_size\x18\t \x01(\x05R\bpageSize\x12\"\n" +
	"\fneedTotalNum\x18\f \x01(\bR\fneedTotalNum\x12\x15\n" +
	"\x06is_asc\x18\n" +
	" \x01(\bR\x05isAsc\x12 \n" +
	"\fno_game_data\x18\v \x01(\bR\n" +
	"noGameData\"\x9c\x01\n" +
	"\x14GameHistoryListReply\x12,\n" +
	"\x04list\x18\x01 \x03(\v2\x18.ghistory.v1.GameHistoryR\x04list\x12\x1d\n" +
	"\n" +
	"page_index\x18\x02 \x01(\x05R\tpageIndex\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1a\n" +
	"\btotalNum\x18\x04 \x01(\x03R\btotalNum\"\xf0\x01\n" +
	"\x18GameHistoryDetailRequest\x12\x14\n" +
	"\x05appId\x18\x01 \x01(\tR\x05appId\x12\x1c\n" +
	"\tgameBrand\x18\x02 \x01(\tR\tgameBrand\x12\x16\n" +
	"\x06gameId\x18\x03 \x01(\tR\x06gameId\x12\x1a\n" +
	"\bplayerId\x18\x04 \x01(\tR\bplayerId\x12\x18\n" +
	"\aroundId\x18\x05 \x01(\tR\aroundId\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12:\n" +
	"\n" +
	"createTime\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\"F\n" +
	"\x16GameHistoryDetailReply\x12,\n" +
	"\x04data\x18\x01 \x03(\v2\x18.ghistory.v1.GameHistoryR\x04data\"\xfe\x04\n" +
	"\vGameHistory\x12\x10\n" +
	"\x03bet\x18\x01 \x01(\x01R\x03bet\x12\x10\n" +
	"\x03win\x18\x02 \x01(\x01R\x03win\x12\x18\n" +
	"\aroundId\x18\x03 \x01(\tR\aroundId\x12\x18\n" +
	"\aorderNo\x18\x04 \x01(\tR\aorderNo\x12\x1a\n" +
	"\bplayerId\x18\x05 \x01(\tR\bplayerId\x12\x14\n" +
	"\x05appId\x18\x06 \x01(\tR\x05appId\x12\x1c\n" +
	"\tgameBrand\x18\a \x01(\tR\tgameBrand\x12\x16\n" +
	"\x06gameId\x18\b \x01(\tR\x06gameId\x12\x16\n" +
	"\x06sample\x18\t \x01(\tR\x06sample\x12\x12\n" +
	"\x04note\x18\n" +
	" \x01(\tR\x04note\x12\x10\n" +
	"\x03rtp\x18\v \x01(\tR\x03rtp\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\x12\x1f\n" +
	"\vwin_balance\x18\x12 \x01(\x01R\n" +
	"winBalance\x12*\n" +
	"\x11after_bet_balance\x18\x13 \x01(\x01R\x0fafterBetBalance\x12,\n" +
	"\x12before_bet_balance\x18\x14 \x01(\x01R\x10beforeBetBalance\x12:\n" +
	"\n" +
	"createTime\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x124\n" +
	"\abetTime\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\abetTime\x124\n" +
	"\awinTime\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\awinTime\x12\x1a\n" +
	"\bGameData\x18\x10 \x01(\fR\bGameData\x12\x1a\n" +
	"\bcompress\x18\x11 \x01(\x05R\bcompress\"\xd2\x01\n" +
	"\x18GameHistoryByTimeRequest\x12\x14\n" +
	"\x05appId\x18\x01 \x01(\tR\x05appId\x12\x1c\n" +
	"\tgameBrand\x18\x02 \x01(\tR\tgameBrand\x12\x16\n" +
	"\x06gameId\x18\x03 \x01(\tR\x06gameId\x12\x1a\n" +
	"\bplayerId\x18\x04 \x01(\tR\bplayerId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1c\n" +
	"\tstartTime\x18\x06 \x01(\x03R\tstartTime\x12\x18\n" +
	"\aendTime\x18\a \x01(\x03R\aendTime\"~\n" +
	"\x16GameHistoryByTimeReply\x12,\n" +
	"\x04list\x18\x01 \x03(\v2\x18.ghistory.v1.GameHistoryR\x04list\x12\x1c\n" +
	"\tstartTime\x18\x02 \x01(\x03R\tstartTime\x12\x18\n" +
	"\aendTime\x18\x03 \x01(\x03R\aendTime\"\xd2\x01\n" +
	"\x18GetTotalBetAndWinRequest\x12\x14\n" +
	"\x05appId\x18\x01 \x01(\tR\x05appId\x12\x1c\n" +
	"\tgameBrand\x18\x02 \x01(\tR\tgameBrand\x12\x16\n" +
	"\x06gameId\x18\x03 \x01(\tR\x06gameId\x12\x1a\n" +
	"\bplayerId\x18\x04 \x01(\tR\bplayerId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1c\n" +
	"\tstartTime\x18\x06 \x01(\x03R\tstartTime\x12\x18\n" +
	"\aendTime\x18\a \x01(\x03R\aendTime\"r\n" +
	"\x16GetTotalBetAndWinReply\x12\x1a\n" +
	"\btotalBet\x18\x01 \x01(\x01R\btotalBet\x12\x1a\n" +
	"\btotalWin\x18\x02 \x01(\x01R\btotalWin\x12 \n" +
	"\vrecordCount\x18\x03 \x01(\x03R\vrecordCount\"\x8b\x03\n" +
	"\x17CreateGameRecordRequest\x12\x14\n" +
	"\x05appId\x18\x01 \x01(\tR\x05appId\x12\x1c\n" +
	"\tgameBrand\x18\x02 \x01(\tR\tgameBrand\x12\x16\n" +
	"\x06gameId\x18\x03 \x01(\tR\x06gameId\x12\x1a\n" +
	"\bplayerId\x18\x04 \x01(\tR\bplayerId\x12\x18\n" +
	"\aroundId\x18\x05 \x01(\tR\aroundId\x12\x18\n" +
	"\aorderNo\x18\x06 \x01(\tR\aorderNo\x12\x10\n" +
	"\x03RTP\x18\a \x01(\tR\x03RTP\x12\x10\n" +
	"\x03bet\x18\b \x01(\x01R\x03bet\x12 \n" +
	"\vroundMoudle\x18\t \x01(\tR\vroundMoudle\x12:\n" +
	"\n" +
	"createTime\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12\x1e\n" +
	"\n" +
	"preOrderNo\x18\v \x01(\tR\n" +
	"preOrderNo\x12\x1a\n" +
	"\bcurrency\x18\f \x01(\tR\bcurrency\x12\x16\n" +
	"\x06isFree\x18\r \x01(\bR\x06isFree\"I\n" +
	"\x15CreateGameRecordReply\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x1a\n" +
	"\brecordId\x18\x02 \x01(\x04R\brecordId\"\xb9\x02\n" +
	"\x1dSetGameRecordStatusBetRequest\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x1a\n" +
	"\brecordId\x18\x02 \x01(\x04R\brecordId\x124\n" +
	"\abetTime\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\abetTime\x12$\n" +
	"\rbeforeBalance\x18\x04 \x01(\x01R\rbeforeBalance\x12\"\n" +
	"\fafterBalance\x18\x05 \x01(\x01R\fafterBalance\x12\x18\n" +
	"\atraceId\x18\x06 \x01(\tR\atraceId\x12\x14\n" +
	"\x05appId\x18\a \x01(\tR\x05appId\x12\x1c\n" +
	"\tgameBrand\x18\b \x01(\tR\tgameBrand\x12\x18\n" +
	"\aroundId\x18\t \x01(\tR\aroundId\"\x1d\n" +
	"\x1bSetGameRecordStatusBetReply\"\xf1\x02\n" +
	"\x1dSetGameRecordStatusWinRequest\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x1a\n" +
	"\brecordId\x18\x02 \x01(\x04R\brecordId\x12\x10\n" +
	"\x03win\x18\x03 \x01(\x01R\x03win\x124\n" +
	"\awinTime\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\awinTime\x12\x1e\n" +
	"\n" +
	"winBalance\x18\x05 \x01(\x01R\n" +
	"winBalance\x12\x1a\n" +
	"\bGameData\x18\x06 \x01(\fR\bGameData\x12\x1a\n" +
	"\bcompress\x18\a \x01(\rR\bcompress\x12\x18\n" +
	"\atraceId\x18\b \x01(\tR\atraceId\x12\x16\n" +
	"\x06simple\x18\t \x01(\tR\x06simple\x12\x14\n" +
	"\x05appId\x18\n" +
	" \x01(\tR\x05appId\x12\x1c\n" +
	"\tgameBrand\x18\v \x01(\tR\tgameBrand\x12\x18\n" +
	"\aroundId\x18\f \x01(\tR\aroundId\"\x1d\n" +
	"\x1bSetGameRecordStatusWinReply\"\xdc\x02\n" +
	" SetGameRecordStatusRefundRequest\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x1a\n" +
	"\brecordId\x18\x02 \x01(\x04R\brecordId\x12:\n" +
	"\n" +
	"refundTime\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"refundTime\x12\"\n" +
	"\frefundReason\x18\x04 \x01(\tR\frefundReason\x12$\n" +
	"\rrefundBalance\x18\x05 \x01(\x01R\rrefundBalance\x12\x18\n" +
	"\atraceId\x18\x06 \x01(\tR\atraceId\x12\x18\n" +
	"\abalance\x18\a \x01(\x01R\abalance\x12\x14\n" +
	"\x05appId\x18\b \x01(\tR\x05appId\x12\x1c\n" +
	"\tgameBrand\x18\t \x01(\tR\tgameBrand\x12\x18\n" +
	"\aroundId\x18\n" +
	" \x01(\tR\aroundId\" \n" +
	"\x1eSetGameRecordStatusRefundReply\"\xb9\x01\n" +
	"\x1fSetGameRecordStatusErrorRequest\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x1a\n" +
	"\brecordId\x18\x02 \x01(\x04R\brecordId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x14\n" +
	"\x05appId\x18\x04 \x01(\tR\x05appId\x12\x1c\n" +
	"\tgameBrand\x18\x05 \x01(\tR\tgameBrand\x12\x18\n" +
	"\aroundId\x18\x06 \x01(\tR\aroundId\"\x1f\n" +
	"\x1dSetGameRecordStatusErrorReply2\xb7\a\n" +
	"\n" +
	"HistoryApi\x12Y\n" +
	"\x0fGameHistoryList\x12#.ghistory.v1.GameHistoryListRequest\x1a!.ghistory.v1.GameHistoryListReply\x12_\n" +
	"\x11GameHistoryDetail\x12%.ghistory.v1.GameHistoryDetailRequest\x1a#.ghistory.v1.GameHistoryDetailReply\x12_\n" +
	"\x11GameHistoryByTime\x12%.ghistory.v1.GameHistoryByTimeRequest\x1a#.ghistory.v1.GameHistoryByTimeReply\x12_\n" +
	"\x11GetTotalBetAndWin\x12%.ghistory.v1.GetTotalBetAndWinRequest\x1a#.ghistory.v1.GetTotalBetAndWinReply\x12\\\n" +
	"\x10CreateGameRecord\x12$.ghistory.v1.CreateGameRecordRequest\x1a\".ghistory.v1.CreateGameRecordReply\x12n\n" +
	"\x16SetGameRecordStatusBet\x12*.ghistory.v1.SetGameRecordStatusBetRequest\x1a(.ghistory.v1.SetGameRecordStatusBetReply\x12n\n" +
	"\x16SetGameRecordStatusWin\x12*.ghistory.v1.SetGameRecordStatusWinRequest\x1a(.ghistory.v1.SetGameRecordStatusWinReply\x12w\n" +
	"\x19SetGameRecordStatusRefund\x12-.ghistory.v1.SetGameRecordStatusRefundRequest\x1a+.ghistory.v1.SetGameRecordStatusRefundReply\x12t\n" +
	"\x18SetGameRecordStatusError\x12,.ghistory.v1.SetGameRecordStatusErrorRequest\x1a*.ghistory.v1.SetGameRecordStatusErrorReplyB^\n" +
	"\x19dev.kratos.api.history.v1B\x0eHistoryProtoV1P\x01Z/cn.qingdou.server/game_common/api/history/v1;v1b\x06proto3"

var (
	file_history_v1_history_proto_rawDescOnce sync.Once
	file_history_v1_history_proto_rawDescData []byte
)

func file_history_v1_history_proto_rawDescGZIP() []byte {
	file_history_v1_history_proto_rawDescOnce.Do(func() {
		file_history_v1_history_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_history_v1_history_proto_rawDesc), len(file_history_v1_history_proto_rawDesc)))
	})
	return file_history_v1_history_proto_rawDescData
}

var file_history_v1_history_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_history_v1_history_proto_goTypes = []any{
	(*GameHistoryListRequest)(nil),           // 0: ghistory.v1.GameHistoryListRequest
	(*GameHistoryListReply)(nil),             // 1: ghistory.v1.GameHistoryListReply
	(*GameHistoryDetailRequest)(nil),         // 2: ghistory.v1.GameHistoryDetailRequest
	(*GameHistoryDetailReply)(nil),           // 3: ghistory.v1.GameHistoryDetailReply
	(*GameHistory)(nil),                      // 4: ghistory.v1.GameHistory
	(*GameHistoryByTimeRequest)(nil),         // 5: ghistory.v1.GameHistoryByTimeRequest
	(*GameHistoryByTimeReply)(nil),           // 6: ghistory.v1.GameHistoryByTimeReply
	(*GetTotalBetAndWinRequest)(nil),         // 7: ghistory.v1.GetTotalBetAndWinRequest
	(*GetTotalBetAndWinReply)(nil),           // 8: ghistory.v1.GetTotalBetAndWinReply
	(*CreateGameRecordRequest)(nil),          // 9: ghistory.v1.CreateGameRecordRequest
	(*CreateGameRecordReply)(nil),            // 10: ghistory.v1.CreateGameRecordReply
	(*SetGameRecordStatusBetRequest)(nil),    // 11: ghistory.v1.SetGameRecordStatusBetRequest
	(*SetGameRecordStatusBetReply)(nil),      // 12: ghistory.v1.SetGameRecordStatusBetReply
	(*SetGameRecordStatusWinRequest)(nil),    // 13: ghistory.v1.SetGameRecordStatusWinRequest
	(*SetGameRecordStatusWinReply)(nil),      // 14: ghistory.v1.SetGameRecordStatusWinReply
	(*SetGameRecordStatusRefundRequest)(nil), // 15: ghistory.v1.SetGameRecordStatusRefundRequest
	(*SetGameRecordStatusRefundReply)(nil),   // 16: ghistory.v1.SetGameRecordStatusRefundReply
	(*SetGameRecordStatusErrorRequest)(nil),  // 17: ghistory.v1.SetGameRecordStatusErrorRequest
	(*SetGameRecordStatusErrorReply)(nil),    // 18: ghistory.v1.SetGameRecordStatusErrorReply
	(*timestamppb.Timestamp)(nil),            // 19: google.protobuf.Timestamp
}
var file_history_v1_history_proto_depIdxs = []int32{
	4,  // 0: ghistory.v1.GameHistoryListReply.list:type_name -> ghistory.v1.GameHistory
	19, // 1: ghistory.v1.GameHistoryDetailRequest.createTime:type_name -> google.protobuf.Timestamp
	4,  // 2: ghistory.v1.GameHistoryDetailReply.data:type_name -> ghistory.v1.GameHistory
	19, // 3: ghistory.v1.GameHistory.createTime:type_name -> google.protobuf.Timestamp
	19, // 4: ghistory.v1.GameHistory.betTime:type_name -> google.protobuf.Timestamp
	19, // 5: ghistory.v1.GameHistory.winTime:type_name -> google.protobuf.Timestamp
	4,  // 6: ghistory.v1.GameHistoryByTimeReply.list:type_name -> ghistory.v1.GameHistory
	19, // 7: ghistory.v1.CreateGameRecordRequest.createTime:type_name -> google.protobuf.Timestamp
	19, // 8: ghistory.v1.SetGameRecordStatusBetRequest.betTime:type_name -> google.protobuf.Timestamp
	19, // 9: ghistory.v1.SetGameRecordStatusWinRequest.winTime:type_name -> google.protobuf.Timestamp
	19, // 10: ghistory.v1.SetGameRecordStatusRefundRequest.refundTime:type_name -> google.protobuf.Timestamp
	0,  // 11: ghistory.v1.HistoryApi.GameHistoryList:input_type -> ghistory.v1.GameHistoryListRequest
	2,  // 12: ghistory.v1.HistoryApi.GameHistoryDetail:input_type -> ghistory.v1.GameHistoryDetailRequest
	5,  // 13: ghistory.v1.HistoryApi.GameHistoryByTime:input_type -> ghistory.v1.GameHistoryByTimeRequest
	7,  // 14: ghistory.v1.HistoryApi.GetTotalBetAndWin:input_type -> ghistory.v1.GetTotalBetAndWinRequest
	9,  // 15: ghistory.v1.HistoryApi.CreateGameRecord:input_type -> ghistory.v1.CreateGameRecordRequest
	11, // 16: ghistory.v1.HistoryApi.SetGameRecordStatusBet:input_type -> ghistory.v1.SetGameRecordStatusBetRequest
	13, // 17: ghistory.v1.HistoryApi.SetGameRecordStatusWin:input_type -> ghistory.v1.SetGameRecordStatusWinRequest
	15, // 18: ghistory.v1.HistoryApi.SetGameRecordStatusRefund:input_type -> ghistory.v1.SetGameRecordStatusRefundRequest
	17, // 19: ghistory.v1.HistoryApi.SetGameRecordStatusError:input_type -> ghistory.v1.SetGameRecordStatusErrorRequest
	1,  // 20: ghistory.v1.HistoryApi.GameHistoryList:output_type -> ghistory.v1.GameHistoryListReply
	3,  // 21: ghistory.v1.HistoryApi.GameHistoryDetail:output_type -> ghistory.v1.GameHistoryDetailReply
	6,  // 22: ghistory.v1.HistoryApi.GameHistoryByTime:output_type -> ghistory.v1.GameHistoryByTimeReply
	8,  // 23: ghistory.v1.HistoryApi.GetTotalBetAndWin:output_type -> ghistory.v1.GetTotalBetAndWinReply
	10, // 24: ghistory.v1.HistoryApi.CreateGameRecord:output_type -> ghistory.v1.CreateGameRecordReply
	12, // 25: ghistory.v1.HistoryApi.SetGameRecordStatusBet:output_type -> ghistory.v1.SetGameRecordStatusBetReply
	14, // 26: ghistory.v1.HistoryApi.SetGameRecordStatusWin:output_type -> ghistory.v1.SetGameRecordStatusWinReply
	16, // 27: ghistory.v1.HistoryApi.SetGameRecordStatusRefund:output_type -> ghistory.v1.SetGameRecordStatusRefundReply
	18, // 28: ghistory.v1.HistoryApi.SetGameRecordStatusError:output_type -> ghistory.v1.SetGameRecordStatusErrorReply
	20, // [20:29] is the sub-list for method output_type
	11, // [11:20] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_history_v1_history_proto_init() }
func file_history_v1_history_proto_init() {
	if File_history_v1_history_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_history_v1_history_proto_rawDesc), len(file_history_v1_history_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_history_v1_history_proto_goTypes,
		DependencyIndexes: file_history_v1_history_proto_depIdxs,
		MessageInfos:      file_history_v1_history_proto_msgTypes,
	}.Build()
	File_history_v1_history_proto = out.File
	file_history_v1_history_proto_goTypes = nil
	file_history_v1_history_proto_depIdxs = nil
}
