// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: history/v1/history.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HistoryApi_GameHistoryList_FullMethodName           = "/ghistory.v1.HistoryApi/GameHistoryList"
	HistoryApi_GameHistoryDetail_FullMethodName         = "/ghistory.v1.HistoryApi/GameHistoryDetail"
	HistoryApi_GameHistoryByTime_FullMethodName         = "/ghistory.v1.HistoryApi/GameHistoryByTime"
	HistoryApi_GetTotalBetAndWin_FullMethodName         = "/ghistory.v1.HistoryApi/GetTotalBetAndWin"
	HistoryApi_CreateGameRecord_FullMethodName          = "/ghistory.v1.HistoryApi/CreateGameRecord"
	HistoryApi_SetGameRecordStatusBet_FullMethodName    = "/ghistory.v1.HistoryApi/SetGameRecordStatusBet"
	HistoryApi_SetGameRecordStatusWin_FullMethodName    = "/ghistory.v1.HistoryApi/SetGameRecordStatusWin"
	HistoryApi_SetGameRecordStatusRefund_FullMethodName = "/ghistory.v1.HistoryApi/SetGameRecordStatusRefund"
	HistoryApi_SetGameRecordStatusError_FullMethodName  = "/ghistory.v1.HistoryApi/SetGameRecordStatusError"
)

// HistoryApiClient is the client API for HistoryApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HistoryApiClient interface {
	// 游戏历史记录
	GameHistoryList(ctx context.Context, in *GameHistoryListRequest, opts ...grpc.CallOption) (*GameHistoryListReply, error)
	// 获取历史记录详情
	GameHistoryDetail(ctx context.Context, in *GameHistoryDetailRequest, opts ...grpc.CallOption) (*GameHistoryDetailReply, error)
	// 通过开始时间以及结束时间获取历史记录
	GameHistoryByTime(ctx context.Context, in *GameHistoryByTimeRequest, opts ...grpc.CallOption) (*GameHistoryByTimeReply, error)
	// 获取下注的条数据，以及下注的总金额，以及赢钱的总金额
	GetTotalBetAndWin(ctx context.Context, in *GetTotalBetAndWinRequest, opts ...grpc.CallOption) (*GetTotalBetAndWinReply, error)
	// 创建一条记录(初使状态)
	CreateGameRecord(ctx context.Context, in *CreateGameRecordRequest, opts ...grpc.CallOption) (*CreateGameRecordReply, error)
	// 更新历史记录为已下注状态
	SetGameRecordStatusBet(ctx context.Context, in *SetGameRecordStatusBetRequest, opts ...grpc.CallOption) (*SetGameRecordStatusBetReply, error)
	// 更新历史记录为结算状态
	SetGameRecordStatusWin(ctx context.Context, in *SetGameRecordStatusWinRequest, opts ...grpc.CallOption) (*SetGameRecordStatusWinReply, error)
	// 更新历史记录为退款状态
	SetGameRecordStatusRefund(ctx context.Context, in *SetGameRecordStatusRefundRequest, opts ...grpc.CallOption) (*SetGameRecordStatusRefundReply, error)
	// 更新历史记录的错误状态
	SetGameRecordStatusError(ctx context.Context, in *SetGameRecordStatusErrorRequest, opts ...grpc.CallOption) (*SetGameRecordStatusErrorReply, error)
}

type historyApiClient struct {
	cc grpc.ClientConnInterface
}

func NewHistoryApiClient(cc grpc.ClientConnInterface) HistoryApiClient {
	return &historyApiClient{cc}
}

func (c *historyApiClient) GameHistoryList(ctx context.Context, in *GameHistoryListRequest, opts ...grpc.CallOption) (*GameHistoryListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GameHistoryListReply)
	err := c.cc.Invoke(ctx, HistoryApi_GameHistoryList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyApiClient) GameHistoryDetail(ctx context.Context, in *GameHistoryDetailRequest, opts ...grpc.CallOption) (*GameHistoryDetailReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GameHistoryDetailReply)
	err := c.cc.Invoke(ctx, HistoryApi_GameHistoryDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyApiClient) GameHistoryByTime(ctx context.Context, in *GameHistoryByTimeRequest, opts ...grpc.CallOption) (*GameHistoryByTimeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GameHistoryByTimeReply)
	err := c.cc.Invoke(ctx, HistoryApi_GameHistoryByTime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyApiClient) GetTotalBetAndWin(ctx context.Context, in *GetTotalBetAndWinRequest, opts ...grpc.CallOption) (*GetTotalBetAndWinReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTotalBetAndWinReply)
	err := c.cc.Invoke(ctx, HistoryApi_GetTotalBetAndWin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyApiClient) CreateGameRecord(ctx context.Context, in *CreateGameRecordRequest, opts ...grpc.CallOption) (*CreateGameRecordReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGameRecordReply)
	err := c.cc.Invoke(ctx, HistoryApi_CreateGameRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyApiClient) SetGameRecordStatusBet(ctx context.Context, in *SetGameRecordStatusBetRequest, opts ...grpc.CallOption) (*SetGameRecordStatusBetReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetGameRecordStatusBetReply)
	err := c.cc.Invoke(ctx, HistoryApi_SetGameRecordStatusBet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyApiClient) SetGameRecordStatusWin(ctx context.Context, in *SetGameRecordStatusWinRequest, opts ...grpc.CallOption) (*SetGameRecordStatusWinReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetGameRecordStatusWinReply)
	err := c.cc.Invoke(ctx, HistoryApi_SetGameRecordStatusWin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyApiClient) SetGameRecordStatusRefund(ctx context.Context, in *SetGameRecordStatusRefundRequest, opts ...grpc.CallOption) (*SetGameRecordStatusRefundReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetGameRecordStatusRefundReply)
	err := c.cc.Invoke(ctx, HistoryApi_SetGameRecordStatusRefund_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyApiClient) SetGameRecordStatusError(ctx context.Context, in *SetGameRecordStatusErrorRequest, opts ...grpc.CallOption) (*SetGameRecordStatusErrorReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetGameRecordStatusErrorReply)
	err := c.cc.Invoke(ctx, HistoryApi_SetGameRecordStatusError_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HistoryApiServer is the server API for HistoryApi service.
// All implementations must embed UnimplementedHistoryApiServer
// for forward compatibility.
type HistoryApiServer interface {
	// 游戏历史记录
	GameHistoryList(context.Context, *GameHistoryListRequest) (*GameHistoryListReply, error)
	// 获取历史记录详情
	GameHistoryDetail(context.Context, *GameHistoryDetailRequest) (*GameHistoryDetailReply, error)
	// 通过开始时间以及结束时间获取历史记录
	GameHistoryByTime(context.Context, *GameHistoryByTimeRequest) (*GameHistoryByTimeReply, error)
	// 获取下注的条数据，以及下注的总金额，以及赢钱的总金额
	GetTotalBetAndWin(context.Context, *GetTotalBetAndWinRequest) (*GetTotalBetAndWinReply, error)
	// 创建一条记录(初使状态)
	CreateGameRecord(context.Context, *CreateGameRecordRequest) (*CreateGameRecordReply, error)
	// 更新历史记录为已下注状态
	SetGameRecordStatusBet(context.Context, *SetGameRecordStatusBetRequest) (*SetGameRecordStatusBetReply, error)
	// 更新历史记录为结算状态
	SetGameRecordStatusWin(context.Context, *SetGameRecordStatusWinRequest) (*SetGameRecordStatusWinReply, error)
	// 更新历史记录为退款状态
	SetGameRecordStatusRefund(context.Context, *SetGameRecordStatusRefundRequest) (*SetGameRecordStatusRefundReply, error)
	// 更新历史记录的错误状态
	SetGameRecordStatusError(context.Context, *SetGameRecordStatusErrorRequest) (*SetGameRecordStatusErrorReply, error)
	mustEmbedUnimplementedHistoryApiServer()
}

// UnimplementedHistoryApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHistoryApiServer struct{}

func (UnimplementedHistoryApiServer) GameHistoryList(context.Context, *GameHistoryListRequest) (*GameHistoryListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GameHistoryList not implemented")
}
func (UnimplementedHistoryApiServer) GameHistoryDetail(context.Context, *GameHistoryDetailRequest) (*GameHistoryDetailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GameHistoryDetail not implemented")
}
func (UnimplementedHistoryApiServer) GameHistoryByTime(context.Context, *GameHistoryByTimeRequest) (*GameHistoryByTimeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GameHistoryByTime not implemented")
}
func (UnimplementedHistoryApiServer) GetTotalBetAndWin(context.Context, *GetTotalBetAndWinRequest) (*GetTotalBetAndWinReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTotalBetAndWin not implemented")
}
func (UnimplementedHistoryApiServer) CreateGameRecord(context.Context, *CreateGameRecordRequest) (*CreateGameRecordReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGameRecord not implemented")
}
func (UnimplementedHistoryApiServer) SetGameRecordStatusBet(context.Context, *SetGameRecordStatusBetRequest) (*SetGameRecordStatusBetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetGameRecordStatusBet not implemented")
}
func (UnimplementedHistoryApiServer) SetGameRecordStatusWin(context.Context, *SetGameRecordStatusWinRequest) (*SetGameRecordStatusWinReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetGameRecordStatusWin not implemented")
}
func (UnimplementedHistoryApiServer) SetGameRecordStatusRefund(context.Context, *SetGameRecordStatusRefundRequest) (*SetGameRecordStatusRefundReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetGameRecordStatusRefund not implemented")
}
func (UnimplementedHistoryApiServer) SetGameRecordStatusError(context.Context, *SetGameRecordStatusErrorRequest) (*SetGameRecordStatusErrorReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetGameRecordStatusError not implemented")
}
func (UnimplementedHistoryApiServer) mustEmbedUnimplementedHistoryApiServer() {}
func (UnimplementedHistoryApiServer) testEmbeddedByValue()                    {}

// UnsafeHistoryApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HistoryApiServer will
// result in compilation errors.
type UnsafeHistoryApiServer interface {
	mustEmbedUnimplementedHistoryApiServer()
}

func RegisterHistoryApiServer(s grpc.ServiceRegistrar, srv HistoryApiServer) {
	// If the following call pancis, it indicates UnimplementedHistoryApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HistoryApi_ServiceDesc, srv)
}

func _HistoryApi_GameHistoryList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameHistoryListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryApiServer).GameHistoryList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryApi_GameHistoryList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryApiServer).GameHistoryList(ctx, req.(*GameHistoryListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryApi_GameHistoryDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameHistoryDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryApiServer).GameHistoryDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryApi_GameHistoryDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryApiServer).GameHistoryDetail(ctx, req.(*GameHistoryDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryApi_GameHistoryByTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameHistoryByTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryApiServer).GameHistoryByTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryApi_GameHistoryByTime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryApiServer).GameHistoryByTime(ctx, req.(*GameHistoryByTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryApi_GetTotalBetAndWin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTotalBetAndWinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryApiServer).GetTotalBetAndWin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryApi_GetTotalBetAndWin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryApiServer).GetTotalBetAndWin(ctx, req.(*GetTotalBetAndWinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryApi_CreateGameRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGameRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryApiServer).CreateGameRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryApi_CreateGameRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryApiServer).CreateGameRecord(ctx, req.(*CreateGameRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryApi_SetGameRecordStatusBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetGameRecordStatusBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryApiServer).SetGameRecordStatusBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryApi_SetGameRecordStatusBet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryApiServer).SetGameRecordStatusBet(ctx, req.(*SetGameRecordStatusBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryApi_SetGameRecordStatusWin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetGameRecordStatusWinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryApiServer).SetGameRecordStatusWin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryApi_SetGameRecordStatusWin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryApiServer).SetGameRecordStatusWin(ctx, req.(*SetGameRecordStatusWinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryApi_SetGameRecordStatusRefund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetGameRecordStatusRefundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryApiServer).SetGameRecordStatusRefund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryApi_SetGameRecordStatusRefund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryApiServer).SetGameRecordStatusRefund(ctx, req.(*SetGameRecordStatusRefundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryApi_SetGameRecordStatusError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetGameRecordStatusErrorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryApiServer).SetGameRecordStatusError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryApi_SetGameRecordStatusError_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryApiServer).SetGameRecordStatusError(ctx, req.(*SetGameRecordStatusErrorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HistoryApi_ServiceDesc is the grpc.ServiceDesc for HistoryApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HistoryApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ghistory.v1.HistoryApi",
	HandlerType: (*HistoryApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GameHistoryList",
			Handler:    _HistoryApi_GameHistoryList_Handler,
		},
		{
			MethodName: "GameHistoryDetail",
			Handler:    _HistoryApi_GameHistoryDetail_Handler,
		},
		{
			MethodName: "GameHistoryByTime",
			Handler:    _HistoryApi_GameHistoryByTime_Handler,
		},
		{
			MethodName: "GetTotalBetAndWin",
			Handler:    _HistoryApi_GetTotalBetAndWin_Handler,
		},
		{
			MethodName: "CreateGameRecord",
			Handler:    _HistoryApi_CreateGameRecord_Handler,
		},
		{
			MethodName: "SetGameRecordStatusBet",
			Handler:    _HistoryApi_SetGameRecordStatusBet_Handler,
		},
		{
			MethodName: "SetGameRecordStatusWin",
			Handler:    _HistoryApi_SetGameRecordStatusWin_Handler,
		},
		{
			MethodName: "SetGameRecordStatusRefund",
			Handler:    _HistoryApi_SetGameRecordStatusRefund_Handler,
		},
		{
			MethodName: "SetGameRecordStatusError",
			Handler:    _HistoryApi_SetGameRecordStatusError_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "history/v1/history.proto",
}
