// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: lifeServiceProto.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LifeServiceInitInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`        // Field tag 1
	AccountID     int64                  `protobuf:"varint,2,opt,name=accountID,proto3" json:"accountID,omitempty"` // Field tag 2
	GameID        int32                  `protobuf:"varint,3,opt,name=gameID,proto3" json:"gameID,omitempty"`       // Field tag 3
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`          // Field tag 4
	Route         int32                  `protobuf:"varint,5,opt,name=route,proto3" json:"route,omitempty"`         // Field tag 5
	ApiID         int32                  `protobuf:"varint,6,opt,name=apiID,proto3" json:"apiID,omitempty"`         // Field tag 6
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LifeServiceInitInfo) Reset() {
	*x = LifeServiceInitInfo{}
	mi := &file_lifeServiceProto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LifeServiceInitInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifeServiceInitInfo) ProtoMessage() {}

func (x *LifeServiceInitInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lifeServiceProto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifeServiceInitInfo.ProtoReflect.Descriptor instead.
func (*LifeServiceInitInfo) Descriptor() ([]byte, []int) {
	return file_lifeServiceProto_proto_rawDescGZIP(), []int{0}
}

func (x *LifeServiceInitInfo) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *LifeServiceInitInfo) GetAccountID() int64 {
	if x != nil {
		return x.AccountID
	}
	return 0
}

func (x *LifeServiceInitInfo) GetGameID() int32 {
	if x != nil {
		return x.GameID
	}
	return 0
}

func (x *LifeServiceInitInfo) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LifeServiceInitInfo) GetRoute() int32 {
	if x != nil {
		return x.Route
	}
	return 0
}

func (x *LifeServiceInitInfo) GetApiID() int32 {
	if x != nil {
		return x.ApiID
	}
	return 0
}

var File_lifeServiceProto_proto protoreflect.FileDescriptor

const file_lifeServiceProto_proto_rawDesc = "" +
	"\n" +
	"\x16lifeServiceProto.proto\x12\x10lifeServiceProto\"\xa5\x01\n" +
	"\x13LifeServiceInitInfo\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x1c\n" +
	"\taccountID\x18\x02 \x01(\x03R\taccountID\x12\x16\n" +
	"\x06gameID\x18\x03 \x01(\x05R\x06gameID\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x12\x14\n" +
	"\x05route\x18\x05 \x01(\x05R\x05route\x12\x14\n" +
	"\x05apiID\x18\x06 \x01(\x05R\x05apiIDB\x05Z\x03/pbb\x06proto3"

var (
	file_lifeServiceProto_proto_rawDescOnce sync.Once
	file_lifeServiceProto_proto_rawDescData []byte
)

func file_lifeServiceProto_proto_rawDescGZIP() []byte {
	file_lifeServiceProto_proto_rawDescOnce.Do(func() {
		file_lifeServiceProto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lifeServiceProto_proto_rawDesc), len(file_lifeServiceProto_proto_rawDesc)))
	})
	return file_lifeServiceProto_proto_rawDescData
}

var file_lifeServiceProto_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_lifeServiceProto_proto_goTypes = []any{
	(*LifeServiceInitInfo)(nil), // 0: lifeServiceProto.LifeServiceInitInfo
}
var file_lifeServiceProto_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lifeServiceProto_proto_init() }
func file_lifeServiceProto_proto_init() {
	if File_lifeServiceProto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lifeServiceProto_proto_rawDesc), len(file_lifeServiceProto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lifeServiceProto_proto_goTypes,
		DependencyIndexes: file_lifeServiceProto_proto_depIdxs,
		MessageInfos:      file_lifeServiceProto_proto_msgTypes,
	}.Build()
	File_lifeServiceProto_proto = out.File
	file_lifeServiceProto_proto_goTypes = nil
	file_lifeServiceProto_proto_depIdxs = nil
}
