package utils

// 机器人人名库
var BotNicknames = []string{
	"Ace", "Bolt", "Comet", "Dash", "Echo", "Fury", "Ghost", "Hawk",
	"Iron", "Jolt", "King", "Lion", "Mage", "Nova", "Orion", "Peak",
	"Queen", "Rage", "Storm", "Titan", "Unit", "Viper", "Wolf", "Xeno",
	"Yeti", "Zest", "Alpha", "Bravo", "Charlie", "Delta", "Eagle",
	"Faker", "Gamer", "Hero", "Icon", "Joker", "Knight", "Legend",
	"Master", "Ninja", "Omega", "Pilot", "Raptor", "Shadow", "T-Rex",
	"Blaze", "Crusher", "Venom", "Hunter", "Phantom", "Samurai", "Reaper",
	"Drake", "Specter", "Wraith", "Phoenix", "Striker", "Sniper", "Cobra",
	"Rogue", "Gladiator", "Berserk", "Monk", "Zephyr", "Rider", "Ranger",
	"Slayer", "Overlord", "Grim", "Titanium", "Cyber", "Punk",
	"Shogun", "Dagger", "Spartan", "Thunder", "Bullet", "Predator",
	"Hurricane", "Avalanche", "Cyclone", "Inferno",
	"Neon", "Vortex", "Razor", "Pulse", "Blitz", "Shock", "Vector", "Surge",
	"Quantum", "EchoX", "Zero", "Core", "Mecha", "Steel", "Plasma", "Chrome",
	"Drift", "Torque", "Turbo", "Nitro", "Axel", "Radar", "Jet", "Hydra",
	"Zeus", "Loki", "Hades", "Ares", "Apollo", "Athena", "Odin", "Ra",
	"Anubis", "Poseidon", "Hermes", "Nyx", "Chronos",
	"Sigma", "Beta", "Gamma", "DeltaX", "Zeta", "Omicron", "Epsilon",
	"Cipher", "Glitch", "Matrix", "Proxy", "Nano", "Circuit", "Kernel",
	"Crimson", "Onyx", "Blizzard", "Frost", "Ember", "Solar", "Lunar",
	"EchoBot", "RoboX", "Drone", "Unit-7", "X-99", "MK-II", "Sentinel",
	"Watcher", "Guardian", "Executor", "Vanguard", "Artemis", "NovaX",
	"Tempest", "Blaster", "Overdrive", "Rift", "Meteor", "Skull", "Orbit", "Coma",
	"Jetstream", "Lightning", "Voltage", "Survivor", "Nemesis", "Chaos", "Order",
	"Pulsefire", "Ironclad", "Steelheart", "Wildfire", "Frostbite", "Warden", "Bane",
	"Drifter", "Gunner", "Breaker", "Sonic", "Flash", "EchoOne", "CrusherX", "Panther",
	"Falcon", "RogueX", "StormRider", "Thunderbolt", "Aftershock", "Impact", "VectorX",
	"Hydron", "Flare", "Quasar", "Radiant", "Oblivion", "Eclipse", "Cosmos", "NovaCore",
	"Photon", "QuantumX", "Zodiac", "Spectra", "Infernal", "Terra", "Aqua", "Aero",
	"Pyro", "Cryo", "Volt", "SurgeX", "Ignite", "Tornado", "Cycler", "Firestorm",
	"Gravity", "Blitzkrieg", "Rampage", "Savage", "TitanX", "Rex", "VortexX", "Phase",
	"Signal", "Neural", "BotZero", "Omni", "Prime", "Mega", "Ultra", "Hyper", "NanoX",
	"CyberCore", "OmegaX", "VectorZ", "Cyborg", "RoboPrime", "Aether", "Eon", "Epoch",
	"Draco", "Argo", "Kairos", "Nemora", "Solon", "Icarus", "Vulcan", "Mercury", "Juno",
	"Gaia", "Atlas", "Hyperion", "Cronos", "Thanatos", "Erebus", "Morpheus", "Helios",
	"Pyra", "Eris", "Orcus", "NyxX", "Astra", "Venus", "Mars", "Jupiter", "Pluto",
	"Neptune", "Saturn", "Ceres", "Vesta", "Titanus", "Andromeda", "OrionX", "PhoenixX",
	"ShadowX", "Darkfire", "Darklight", "Lightbringer", "Sunstrike", "Starfall",
	"Moonlight", "Starborn", "EclipseX", "Skyline", "Skylord", "Bladestorm", "Soulfire",
	"Nightmare", "Dreamer", "Vision", "Spectral", "PulseBot", "BlitzBot", "Crash", "Burner",
	"Forge", "Smith", "CoreX", "Data", "Byte", "Node", "Protocol", "Packet", "Root",
	"Binary", "Bitwise", "Token", "CipherX", "Virus", "Trojan", "MatrixX", "Logic", "Synth",
	"AI-9", "Unit-42", "DroneX", "MechOne", "UnitZ", "EchoZero", "Gamma9", "Sigma7", "Beta4",
	"Delta5", "Alpha9", "OmniCore", "HyperBot", "QuantumZ", "CyberEdge", "Blade", "WardenX",
	"Fortress", "TitaniumX", "IronWolf", "SteelFox", "Bronze", "Silver", "Gold", "Platinum",
	"Diamond", "Obsidian", "Ruby", "Emerald", "Sapphire", "Topaz", "OnyxX", "Crystal",
	"Glass", "Shard", "Prism", "NovaPrime", "Solaris", "Lunaris", "Ignis", "AquaX", "Terrax",
	"Voltex", "Cyclonis", "Typhoon", "HurricaneX", "Tremor", "Seismic", "Avalon", "Mythos",
	"Valor", "Virtue", "EchoAI", "Neo", "Zion", "MorpheusX", "Trinity", "Oracle", "CipherBot",
	"CodeX", "KernelX", "Nexus", "Portal", "Bridge", "Link", "Wave", "SignalX", "NodeX",
	"Cluster", "Array", "VectorAI", "CoreAI", "CyberMind", "Synapse", "Neuron", "Memory",
	"Processor", "QuantumAI", "LogicX", "Reason", "Intel", "Cortex", "Module", "System",
	"Entity", "Shell", "Avatar", "Program", "DataX", "Machine", "Engine", "Motor", "Servo",
	"Drive", "UnitX", "BotNet", "GuardianX", "Protector", "Defender", "HunterX", "SniperX",
	"Marksman", "Sharpshot", "Quickshot", "Gunmetal", "Tracer", "Tracker", "Scout", "Spy",
	"Recon", "Pathfinder", "Voyager", "Pioneer", "Explorer", "RangerX", "Nomad", "Wanderer",
	"Outlaw", "Bandit", "Rebel", "Raider", "Marauder", "Corsair", "Pirate", "Captain", "Admiral",
	"Commander", "General", "Major", "Colonel", "Sergeant", "Private", "Agent", "Operative",
	"Assassin", "HunterBot", "Killjoy", "Deadeye", "Widow", "GhostX", "SpecterX", "Shade", "Gloom",
	"EchoDark", "Noir", "Ash", "Cinder", "Coal", "Smog", "Mist", "Fog", "Drizzle", "Rain", "Snow",
	"Hail", "ThunderX", "LightningX", "Spark", "Charge", "Static", "Current", "Ion", "Electron",
	"Proton", "Neutron", "Fusion", "Fission", "PlasmaX", "Arc", "Beam", "Laser", "PulseRay",
	"PhotonX", "Quark", "Boson", "Atom", "Molecule", "Matter", "Energy", "DarkMatter", "Void",
	"Singularity", "Abyss", "VortexZ", "EventHorizon", "GravityX", "BlackHole", "NovaZ",
	"Infinity", "Eternity", "AetherX", "Nebula", "Galaxy", "Cosmic", "Starlord", "Supernova",
	"VoidWalker", "SpaceRanger", "Astro", "OrbitX", "Satellite", "CometX", "MeteorX",
	"Asteroid", "LunaX", "SolarFlare", "Sunspot", "Daybreak", "Twilight", "Midnight", "Aurora",
	"Polaris", "Zenith", "Nadir", "EclipseZ", "CosmosX", "Skyfire", "Heaven", "Inferna", "Purgis",
	"Demon", "Angel", "Saint", "Monarch", "Reign", "Crown", "Throne", "Empire", "Dynasty", "Realm",
	"KingX", "QueenX", "Lord", "Duke", "Baron", "Squire", "KnightX", "Paladin", "Crusader", "Templar",
	"SamuraiX", "Ronin", "NinjaX", "Shinobi", "Yokai", "Oni", "Kami", "Spirit", "Soul", "Essence",
	"Life", "Death", "Fate", "Destiny", "Karma", "EchoSoul", "SoulBot", "Dream", "VisionX", "Mind",
	"Brain", "Heart", "CoreZ", "PulseX", "NovaAI", "BotPrime", "CyberSoul", "NeuralX", "SynX",
	"Zynapse", "MechX", "NanoBot", "OmegaAI", "BetaAI", "AlphaAI", "DeltaAI", "SigmaAI", "GammaAI",
	"ZetaAI", "EpsilonAI", "OmicronAI", "ThetaAI", "LambdaAI", "KappaAI", "RhoAI", "TauAI",
	"PsiAI", "ChiAI", "PhiAI", "OmegaZ", "InfinityX", "Limitless", "Boundless", "Unreal",
	"PhantomX", "SpectraX", "WraithX", "ShadeX", "OblivionX", "DarkNova", "SolarNova", "LunarNova",
	"VoidNova", "PulseNova", "CyberNova", "TitanNova", "NeoNova", "RoboNova", "StarNova",
	"QuantumNova", "VortexNova", "NovaUnit", "XenoNova", "AetherNova", "PlasmaNova",
}
