// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: game/v1/game_error.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	// 业务错误码
	ErrorReason_SUCCESS                ErrorReason = 0  // 成功
	ErrorReason_INTERNAL_SERVER_ERROR  ErrorReason = 9  // 内部服务器错误
	ErrorReason_INVALID_OPERATOR       ErrorReason = 10 // 无效的运营商
	ErrorReason_LIMITED_PERMISSIONS    ErrorReason = 11 // 运营商权限不足
	ErrorReason_INVALID_HASH_CODE      ErrorReason = 12 // 无效的哈希码
	ErrorReason_INVALID_PARAMETERS     ErrorReason = 13 // 请求参数错误
	ErrorReason_INVALID_PLAYER_TOKEN   ErrorReason = 14 // 无效的玩家令牌
	ErrorReason_PLAYER_TOKEN_EXPIRED   ErrorReason = 15 // 玩家令牌已过期
	ErrorReason_GAME_MAINTENANCE       ErrorReason = 16 // 游戏维护中
	ErrorReason_GAME_UNAVAILABLE       ErrorReason = 17 // 游戏不可用
	ErrorReason_GAME_NOT_FOUND         ErrorReason = 18 // 游戏不存在
	ErrorReason_PLAYER_NOT_FOUND_ERROR ErrorReason = 19 // 玩家不存在
	ErrorReason_BET_PENDING            ErrorReason = 20 // 投注异常
	ErrorReason_TRANSACTION_NOT_FOUND  ErrorReason = 21 // 交易不存在
	ErrorReason_INVALID_CURRENCY_CODE  ErrorReason = 22 // 货币代码错误
	ErrorReason_INVALID_REQUEST        ErrorReason = 23 // 无效请求
	ErrorReason_PLAYER_ALREADY_EXISTED ErrorReason = 24 // 玩家已存在
	ErrorReason_TRANSACTION_EXISTS     ErrorReason = 25 // 交易已存在
	ErrorReason_INVALID_IP             ErrorReason = 26 // 无效 IP
	ErrorReason_MAX_REQUEST_LIMIT      ErrorReason = 27 // 已达最大请求限制
	ErrorReason_INVALID_RTP            ErrorReason = 28 // 无效 RTP
	ErrorReason_INSUFFICIENT_BALANCE   ErrorReason = 29 // 玩家余额不足
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:  "SUCCESS",
		9:  "INTERNAL_SERVER_ERROR",
		10: "INVALID_OPERATOR",
		11: "LIMITED_PERMISSIONS",
		12: "INVALID_HASH_CODE",
		13: "INVALID_PARAMETERS",
		14: "INVALID_PLAYER_TOKEN",
		15: "PLAYER_TOKEN_EXPIRED",
		16: "GAME_MAINTENANCE",
		17: "GAME_UNAVAILABLE",
		18: "GAME_NOT_FOUND",
		19: "PLAYER_NOT_FOUND_ERROR",
		20: "BET_PENDING",
		21: "TRANSACTION_NOT_FOUND",
		22: "INVALID_CURRENCY_CODE",
		23: "INVALID_REQUEST",
		24: "PLAYER_ALREADY_EXISTED",
		25: "TRANSACTION_EXISTS",
		26: "INVALID_IP",
		27: "MAX_REQUEST_LIMIT",
		28: "INVALID_RTP",
		29: "INSUFFICIENT_BALANCE",
	}
	ErrorReason_value = map[string]int32{
		"SUCCESS":                0,
		"INTERNAL_SERVER_ERROR":  9,
		"INVALID_OPERATOR":       10,
		"LIMITED_PERMISSIONS":    11,
		"INVALID_HASH_CODE":      12,
		"INVALID_PARAMETERS":     13,
		"INVALID_PLAYER_TOKEN":   14,
		"PLAYER_TOKEN_EXPIRED":   15,
		"GAME_MAINTENANCE":       16,
		"GAME_UNAVAILABLE":       17,
		"GAME_NOT_FOUND":         18,
		"PLAYER_NOT_FOUND_ERROR": 19,
		"BET_PENDING":            20,
		"TRANSACTION_NOT_FOUND":  21,
		"INVALID_CURRENCY_CODE":  22,
		"INVALID_REQUEST":        23,
		"PLAYER_ALREADY_EXISTED": 24,
		"TRANSACTION_EXISTS":     25,
		"INVALID_IP":             26,
		"MAX_REQUEST_LIMIT":      27,
		"INVALID_RTP":            28,
		"INSUFFICIENT_BALANCE":   29,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_game_v1_game_error_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_game_v1_game_error_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_game_v1_game_error_proto_rawDescGZIP(), []int{0}
}

var File_game_v1_game_error_proto protoreflect.FileDescriptor

const file_game_v1_game_error_proto_rawDesc = "" +
	"\n" +
	"\x18game/v1/game_error.proto\x12\agame.v1\x1a\x13errors/errors.proto*\x8f\x05\n" +
	"\vErrorReason\x12\x11\n" +
	"\aSUCCESS\x10\x00\x1a\x04\xa8E\xc8\x01\x12\x1f\n" +
	"\x15INTERNAL_SERVER_ERROR\x10\t\x1a\x04\xa8E\xf4\x03\x12\x1a\n" +
	"\x10INVALID_OPERATOR\x10\n" +
	"\x1a\x04\xa8E\x90\x03\x12\x1d\n" +
	"\x13LIMITED_PERMISSIONS\x10\v\x1a\x04\xa8E\x93\x03\x12\x1b\n" +
	"\x11INVALID_HASH_CODE\x10\f\x1a\x04\xa8E\x90\x03\x12\x1c\n" +
	"\x12INVALID_PARAMETERS\x10\r\x1a\x04\xa8E\x90\x03\x12\x1e\n" +
	"\x14INVALID_PLAYER_TOKEN\x10\x0e\x1a\x04\xa8E\x91\x03\x12\x1e\n" +
	"\x14PLAYER_TOKEN_EXPIRED\x10\x0f\x1a\x04\xa8E\x91\x03\x12\x1a\n" +
	"\x10GAME_MAINTENANCE\x10\x10\x1a\x04\xa8E\xf7\x03\x12\x1a\n" +
	"\x10GAME_UNAVAILABLE\x10\x11\x1a\x04\xa8E\xf7\x03\x12\x18\n" +
	"\x0eGAME_NOT_FOUND\x10\x12\x1a\x04\xa8E\x94\x03\x12 \n" +
	"\x16PLAYER_NOT_FOUND_ERROR\x10\x13\x1a\x04\xa8E\x94\x03\x12\x15\n" +
	"\vBET_PENDING\x10\x14\x1a\x04\xa8E\x98\x03\x12\x1f\n" +
	"\x15TRANSACTION_NOT_FOUND\x10\x15\x1a\x04\xa8E\x94\x03\x12\x1f\n" +
	"\x15INVALID_CURRENCY_CODE\x10\x16\x1a\x04\xa8E\x90\x03\x12\x19\n" +
	"\x0fINVALID_REQUEST\x10\x17\x1a\x04\xa8E\x90\x03\x12 \n" +
	"\x16PLAYER_ALREADY_EXISTED\x10\x18\x1a\x04\xa8E\x99\x03\x12\x1c\n" +
	"\x12TRANSACTION_EXISTS\x10\x19\x1a\x04\xa8E\x99\x03\x12\x14\n" +
	"\n" +
	"INVALID_IP\x10\x1a\x1a\x04\xa8E\x93\x03\x12\x1b\n" +
	"\x11MAX_REQUEST_LIMIT\x10\x1b\x1a\x04\xa8E\xad\x03\x12\x15\n" +
	"\vINVALID_RTP\x10\x1c\x1a\x04\xa8E\x90\x03\x12\x1e\n" +
	"\x14INSUFFICIENT_BALANCE\x10\x1d\x1a\x04\xa8E\x90\x03\x1a\x04\xa0E\xf4\x03BU\n" +
	"\x16dev.kratos.api.game.v1B\vGameProtoV1P\x01Z,cn.qingdou.server/game_common/api/game/v1;v1b\x06proto3"

var (
	file_game_v1_game_error_proto_rawDescOnce sync.Once
	file_game_v1_game_error_proto_rawDescData []byte
)

func file_game_v1_game_error_proto_rawDescGZIP() []byte {
	file_game_v1_game_error_proto_rawDescOnce.Do(func() {
		file_game_v1_game_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_v1_game_error_proto_rawDesc), len(file_game_v1_game_error_proto_rawDesc)))
	})
	return file_game_v1_game_error_proto_rawDescData
}

var file_game_v1_game_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_game_v1_game_error_proto_goTypes = []any{
	(ErrorReason)(0), // 0: game.v1.ErrorReason
}
var file_game_v1_game_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_game_v1_game_error_proto_init() }
func file_game_v1_game_error_proto_init() {
	if File_game_v1_game_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_v1_game_error_proto_rawDesc), len(file_game_v1_game_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_v1_game_error_proto_goTypes,
		DependencyIndexes: file_game_v1_game_error_proto_depIdxs,
		EnumInfos:         file_game_v1_game_error_proto_enumTypes,
	}.Build()
	File_game_v1_game_error_proto = out.File
	file_game_v1_game_error_proto_goTypes = nil
	file_game_v1_game_error_proto_depIdxs = nil
}
