// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 业务错误码
func IsSuccess(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_SUCCESS.String() && e.Code == 200
}

// 业务错误码
func ErrorSuccess(format string, args ...interface{}) *errors.Error {
	return errors.New(200, ErrorReason_SUCCESS.String(), fmt.Sprintf(format, args...))
}

// 内部服务器错误
func IsInternalServerError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INTERNAL_SERVER_ERROR.String() && e.Code == 500
}

// 内部服务器错误
func ErrorInternalServerError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_INTERNAL_SERVER_ERROR.String(), fmt.Sprintf(format, args...))
}

// 无效的运营商
func IsInvalidOperator(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INVALID_OPERATOR.String() && e.Code == 400
}

// 无效的运营商
func ErrorInvalidOperator(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_INVALID_OPERATOR.String(), fmt.Sprintf(format, args...))
}

// 运营商权限不足
func IsLimitedPermissions(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_LIMITED_PERMISSIONS.String() && e.Code == 403
}

// 运营商权限不足
func ErrorLimitedPermissions(format string, args ...interface{}) *errors.Error {
	return errors.New(403, ErrorReason_LIMITED_PERMISSIONS.String(), fmt.Sprintf(format, args...))
}

// 无效的哈希码
func IsInvalidHashCode(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INVALID_HASH_CODE.String() && e.Code == 400
}

// 无效的哈希码
func ErrorInvalidHashCode(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_INVALID_HASH_CODE.String(), fmt.Sprintf(format, args...))
}

// 请求参数错误
func IsInvalidParameters(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INVALID_PARAMETERS.String() && e.Code == 400
}

// 请求参数错误
func ErrorInvalidParameters(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_INVALID_PARAMETERS.String(), fmt.Sprintf(format, args...))
}

// 无效的玩家令牌
func IsInvalidPlayerToken(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INVALID_PLAYER_TOKEN.String() && e.Code == 401
}

// 无效的玩家令牌
func ErrorInvalidPlayerToken(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_INVALID_PLAYER_TOKEN.String(), fmt.Sprintf(format, args...))
}

// 玩家令牌已过期
func IsPlayerTokenExpired(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_PLAYER_TOKEN_EXPIRED.String() && e.Code == 401
}

// 玩家令牌已过期
func ErrorPlayerTokenExpired(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_PLAYER_TOKEN_EXPIRED.String(), fmt.Sprintf(format, args...))
}

// 游戏维护中
func IsGameMaintenance(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_GAME_MAINTENANCE.String() && e.Code == 503
}

// 游戏维护中
func ErrorGameMaintenance(format string, args ...interface{}) *errors.Error {
	return errors.New(503, ErrorReason_GAME_MAINTENANCE.String(), fmt.Sprintf(format, args...))
}

// 游戏不可用
func IsGameUnavailable(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_GAME_UNAVAILABLE.String() && e.Code == 503
}

// 游戏不可用
func ErrorGameUnavailable(format string, args ...interface{}) *errors.Error {
	return errors.New(503, ErrorReason_GAME_UNAVAILABLE.String(), fmt.Sprintf(format, args...))
}

// 游戏不存在
func IsGameNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_GAME_NOT_FOUND.String() && e.Code == 404
}

// 游戏不存在
func ErrorGameNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_GAME_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

// 玩家不存在
func IsPlayerNotFoundError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_PLAYER_NOT_FOUND_ERROR.String() && e.Code == 404
}

// 玩家不存在
func ErrorPlayerNotFoundError(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_PLAYER_NOT_FOUND_ERROR.String(), fmt.Sprintf(format, args...))
}

// 投注异常
func IsBetPending(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_BET_PENDING.String() && e.Code == 408
}

// 投注异常
func ErrorBetPending(format string, args ...interface{}) *errors.Error {
	return errors.New(408, ErrorReason_BET_PENDING.String(), fmt.Sprintf(format, args...))
}

// 交易不存在
func IsTransactionNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_TRANSACTION_NOT_FOUND.String() && e.Code == 404
}

// 交易不存在
func ErrorTransactionNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_TRANSACTION_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

// 货币代码错误
func IsInvalidCurrencyCode(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INVALID_CURRENCY_CODE.String() && e.Code == 400
}

// 货币代码错误
func ErrorInvalidCurrencyCode(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_INVALID_CURRENCY_CODE.String(), fmt.Sprintf(format, args...))
}

// 无效请求
func IsInvalidRequest(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INVALID_REQUEST.String() && e.Code == 400
}

// 无效请求
func ErrorInvalidRequest(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_INVALID_REQUEST.String(), fmt.Sprintf(format, args...))
}

// 玩家已存在
func IsPlayerAlreadyExisted(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_PLAYER_ALREADY_EXISTED.String() && e.Code == 409
}

// 玩家已存在
func ErrorPlayerAlreadyExisted(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_PLAYER_ALREADY_EXISTED.String(), fmt.Sprintf(format, args...))
}

// 交易已存在
func IsTransactionExists(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_TRANSACTION_EXISTS.String() && e.Code == 409
}

// 交易已存在
func ErrorTransactionExists(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_TRANSACTION_EXISTS.String(), fmt.Sprintf(format, args...))
}

// 无效 IP
func IsInvalidIp(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INVALID_IP.String() && e.Code == 403
}

// 无效 IP
func ErrorInvalidIp(format string, args ...interface{}) *errors.Error {
	return errors.New(403, ErrorReason_INVALID_IP.String(), fmt.Sprintf(format, args...))
}

// 已达最大请求限制
func IsMaxRequestLimit(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_MAX_REQUEST_LIMIT.String() && e.Code == 429
}

// 已达最大请求限制
func ErrorMaxRequestLimit(format string, args ...interface{}) *errors.Error {
	return errors.New(429, ErrorReason_MAX_REQUEST_LIMIT.String(), fmt.Sprintf(format, args...))
}

// 无效 RTP
func IsInvalidRtp(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INVALID_RTP.String() && e.Code == 400
}

// 无效 RTP
func ErrorInvalidRtp(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_INVALID_RTP.String(), fmt.Sprintf(format, args...))
}

// 玩家余额不足
func IsInsufficientBalance(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INSUFFICIENT_BALANCE.String() && e.Code == 400
}

// 玩家余额不足
func ErrorInsufficientBalance(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_INSUFFICIENT_BALANCE.String(), fmt.Sprintf(format, args...))
}
