// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: game/v1/game.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameApi_Balance_FullMethodName         = "/game.v1.GameApi/Balance"
	GameApi_Bet_FullMethodName             = "/game.v1.GameApi/Bet"
	GameApi_Win_FullMethodName             = "/game.v1.GameApi/Win"
	GameApi_Refund_FullMethodName          = "/game.v1.GameApi/Refund"
	GameApi_GameHistoryList_FullMethodName = "/game.v1.GameApi/GameHistoryList"
	GameApi_JiliGameHistory_FullMethodName = "/game.v1.GameApi/JiliGameHistory"
	GameApi_AppGameList_FullMethodName     = "/game.v1.GameApi/AppGameList"
)

// GameApiClient is the client API for GameApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameApiClient interface {
	// 获取商户平台玩家钱包拥有货币余额。
	Balance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceReply, error)
	// 玩家游戏投注数据及开奖结果信息推送，先扣除玩家投注金额，再加上玩家中奖金额
	Bet(ctx context.Context, in *BetRequest, opts ...grpc.CallOption) (*BetReply, error)
	// 派彩
	Win(ctx context.Context, in *WinRequest, opts ...grpc.CallOption) (*WinReply, error)
	// 回退
	Refund(ctx context.Context, in *RefundRequest, opts ...grpc.CallOption) (*RefundReply, error)
	// 游戏历史记录
	GameHistoryList(ctx context.Context, in *GameHistoryRequest, opts ...grpc.CallOption) (*GameHistoryReply, error)
	// Jili游戏历史记录
	JiliGameHistory(ctx context.Context, in *JiliGameHistoryRequest, opts ...grpc.CallOption) (*JiliGameHistoryReply, error)
	// 商户游戏列表
	AppGameList(ctx context.Context, in *AppGameListRequest, opts ...grpc.CallOption) (*AppGameListReply, error)
}

type gameApiClient struct {
	cc grpc.ClientConnInterface
}

func NewGameApiClient(cc grpc.ClientConnInterface) GameApiClient {
	return &gameApiClient{cc}
}

func (c *gameApiClient) Balance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BalanceReply)
	err := c.cc.Invoke(ctx, GameApi_Balance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameApiClient) Bet(ctx context.Context, in *BetRequest, opts ...grpc.CallOption) (*BetReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BetReply)
	err := c.cc.Invoke(ctx, GameApi_Bet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameApiClient) Win(ctx context.Context, in *WinRequest, opts ...grpc.CallOption) (*WinReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WinReply)
	err := c.cc.Invoke(ctx, GameApi_Win_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameApiClient) Refund(ctx context.Context, in *RefundRequest, opts ...grpc.CallOption) (*RefundReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefundReply)
	err := c.cc.Invoke(ctx, GameApi_Refund_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameApiClient) GameHistoryList(ctx context.Context, in *GameHistoryRequest, opts ...grpc.CallOption) (*GameHistoryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GameHistoryReply)
	err := c.cc.Invoke(ctx, GameApi_GameHistoryList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameApiClient) JiliGameHistory(ctx context.Context, in *JiliGameHistoryRequest, opts ...grpc.CallOption) (*JiliGameHistoryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JiliGameHistoryReply)
	err := c.cc.Invoke(ctx, GameApi_JiliGameHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameApiClient) AppGameList(ctx context.Context, in *AppGameListRequest, opts ...grpc.CallOption) (*AppGameListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppGameListReply)
	err := c.cc.Invoke(ctx, GameApi_AppGameList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameApiServer is the server API for GameApi service.
// All implementations must embed UnimplementedGameApiServer
// for forward compatibility.
type GameApiServer interface {
	// 获取商户平台玩家钱包拥有货币余额。
	Balance(context.Context, *BalanceRequest) (*BalanceReply, error)
	// 玩家游戏投注数据及开奖结果信息推送，先扣除玩家投注金额，再加上玩家中奖金额
	Bet(context.Context, *BetRequest) (*BetReply, error)
	// 派彩
	Win(context.Context, *WinRequest) (*WinReply, error)
	// 回退
	Refund(context.Context, *RefundRequest) (*RefundReply, error)
	// 游戏历史记录
	GameHistoryList(context.Context, *GameHistoryRequest) (*GameHistoryReply, error)
	// Jili游戏历史记录
	JiliGameHistory(context.Context, *JiliGameHistoryRequest) (*JiliGameHistoryReply, error)
	// 商户游戏列表
	AppGameList(context.Context, *AppGameListRequest) (*AppGameListReply, error)
	mustEmbedUnimplementedGameApiServer()
}

// UnimplementedGameApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameApiServer struct{}

func (UnimplementedGameApiServer) Balance(context.Context, *BalanceRequest) (*BalanceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Balance not implemented")
}
func (UnimplementedGameApiServer) Bet(context.Context, *BetRequest) (*BetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Bet not implemented")
}
func (UnimplementedGameApiServer) Win(context.Context, *WinRequest) (*WinReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Win not implemented")
}
func (UnimplementedGameApiServer) Refund(context.Context, *RefundRequest) (*RefundReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Refund not implemented")
}
func (UnimplementedGameApiServer) GameHistoryList(context.Context, *GameHistoryRequest) (*GameHistoryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GameHistoryList not implemented")
}
func (UnimplementedGameApiServer) JiliGameHistory(context.Context, *JiliGameHistoryRequest) (*JiliGameHistoryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JiliGameHistory not implemented")
}
func (UnimplementedGameApiServer) AppGameList(context.Context, *AppGameListRequest) (*AppGameListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppGameList not implemented")
}
func (UnimplementedGameApiServer) mustEmbedUnimplementedGameApiServer() {}
func (UnimplementedGameApiServer) testEmbeddedByValue()                 {}

// UnsafeGameApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameApiServer will
// result in compilation errors.
type UnsafeGameApiServer interface {
	mustEmbedUnimplementedGameApiServer()
}

func RegisterGameApiServer(s grpc.ServiceRegistrar, srv GameApiServer) {
	// If the following call pancis, it indicates UnimplementedGameApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameApi_ServiceDesc, srv)
}

func _GameApi_Balance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameApiServer).Balance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameApi_Balance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameApiServer).Balance(ctx, req.(*BalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameApi_Bet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameApiServer).Bet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameApi_Bet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameApiServer).Bet(ctx, req.(*BetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameApi_Win_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameApiServer).Win(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameApi_Win_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameApiServer).Win(ctx, req.(*WinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameApi_Refund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameApiServer).Refund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameApi_Refund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameApiServer).Refund(ctx, req.(*RefundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameApi_GameHistoryList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameApiServer).GameHistoryList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameApi_GameHistoryList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameApiServer).GameHistoryList(ctx, req.(*GameHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameApi_JiliGameHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JiliGameHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameApiServer).JiliGameHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameApi_JiliGameHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameApiServer).JiliGameHistory(ctx, req.(*JiliGameHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameApi_AppGameList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppGameListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameApiServer).AppGameList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameApi_AppGameList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameApiServer).AppGameList(ctx, req.(*AppGameListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameApi_ServiceDesc is the grpc.ServiceDesc for GameApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.v1.GameApi",
	HandlerType: (*GameApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Balance",
			Handler:    _GameApi_Balance_Handler,
		},
		{
			MethodName: "Bet",
			Handler:    _GameApi_Bet_Handler,
		},
		{
			MethodName: "Win",
			Handler:    _GameApi_Win_Handler,
		},
		{
			MethodName: "Refund",
			Handler:    _GameApi_Refund_Handler,
		},
		{
			MethodName: "GameHistoryList",
			Handler:    _GameApi_GameHistoryList_Handler,
		},
		{
			MethodName: "JiliGameHistory",
			Handler:    _GameApi_JiliGameHistory_Handler,
		},
		{
			MethodName: "AppGameList",
			Handler:    _GameApi_AppGameList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "game/v1/game.proto",
}
