// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: game/v1/game.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceRequest) Reset() {
	*x = BalanceRequest{}
	mi := &file_game_v1_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceRequest) ProtoMessage() {}

func (x *BalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceRequest.ProtoReflect.Descriptor instead.
func (*BalanceRequest) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{0}
}

func (x *BalanceRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *BalanceRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type BalanceReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      string                 `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Balance       float64                `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceReply) Reset() {
	*x = BalanceReply{}
	mi := &file_game_v1_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceReply) ProtoMessage() {}

func (x *BalanceReply) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceReply.ProtoReflect.Descriptor instead.
func (*BalanceReply) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{1}
}

func (x *BalanceReply) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *BalanceReply) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type BetRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PlayerId         string                 `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`     //账号id
	RoundId          string                 `protobuf:"bytes,2,opt,name=roundId,proto3" json:"roundId,omitempty"`       //游戏回合, 长度64以內。
	PreRoundId       string                 `protobuf:"bytes,3,opt,name=preRoundId,proto3" json:"preRoundId,omitempty"` //上一把游戏回合, 长度64以內。
	Currency         string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Bet              float64                `protobuf:"fixed64,5,opt,name=bet,proto3" json:"bet,omitempty"`                               //下注
	GameBrand        string                 `protobuf:"bytes,6,opt,name=gameBrand,proto3" json:"gameBrand,omitempty"`                     //游戏品牌
	GameId           string                 `protobuf:"bytes,7,opt,name=gameId,proto3" json:"gameId,omitempty"`                           //游戏id
	Rtp              string                 `protobuf:"bytes,8,opt,name=rtp,proto3" json:"rtp,omitempty"`                                 //rtp档位
	RoundModel       string                 `protobuf:"bytes,9,opt,name=round_model,json=roundModel,proto3" json:"round_model,omitempty"` // 模式
	GameData         []byte                 `protobuf:"bytes,10,opt,name=game_data,json=gameData,proto3" json:"game_data,omitempty"`      // 游戏数据
	TraceId          string                 `protobuf:"bytes,11,opt,name=traceId,proto3" json:"traceId,omitempty"`                        // 跟踪id
	TransactionId    string                 `protobuf:"bytes,12,opt,name=transactionId,proto3" json:"transactionId,omitempty"`            // 下注交易id
	IsFree           bool                   `protobuf:"varint,13,opt,name=isFree,proto3" json:"isFree,omitempty"`                         // 是否免费模式
	PreTransactionId string                 `protobuf:"bytes,14,opt,name=preTransactionId,proto3" json:"preTransactionId,omitempty"`      // 上一次下注交易id
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BetRequest) Reset() {
	*x = BetRequest{}
	mi := &file_game_v1_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetRequest) ProtoMessage() {}

func (x *BetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetRequest.ProtoReflect.Descriptor instead.
func (*BetRequest) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{2}
}

func (x *BetRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *BetRequest) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *BetRequest) GetPreRoundId() string {
	if x != nil {
		return x.PreRoundId
	}
	return ""
}

func (x *BetRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *BetRequest) GetBet() float64 {
	if x != nil {
		return x.Bet
	}
	return 0
}

func (x *BetRequest) GetGameBrand() string {
	if x != nil {
		return x.GameBrand
	}
	return ""
}

func (x *BetRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *BetRequest) GetRtp() string {
	if x != nil {
		return x.Rtp
	}
	return ""
}

func (x *BetRequest) GetRoundModel() string {
	if x != nil {
		return x.RoundModel
	}
	return ""
}

func (x *BetRequest) GetGameData() []byte {
	if x != nil {
		return x.GameData
	}
	return nil
}

func (x *BetRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *BetRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *BetRequest) GetIsFree() bool {
	if x != nil {
		return x.IsFree
	}
	return false
}

func (x *BetRequest) GetPreTransactionId() string {
	if x != nil {
		return x.PreTransactionId
	}
	return ""
}

type BetReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      string                 `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Balance       float64                `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BetReply) Reset() {
	*x = BetReply{}
	mi := &file_game_v1_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetReply) ProtoMessage() {}

func (x *BetReply) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetReply.ProtoReflect.Descriptor instead.
func (*BetReply) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{3}
}

func (x *BetReply) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *BetReply) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type WinRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PlayerId         string                 `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`     //账号id
	RoundId          string                 `protobuf:"bytes,2,opt,name=roundId,proto3" json:"roundId,omitempty"`       //游戏回合, 长度64以內。
	PreRoundId       string                 `protobuf:"bytes,3,opt,name=preRoundId,proto3" json:"preRoundId,omitempty"` //上一把游戏回合, 长度64以內。
	Currency         string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Bet              float64                `protobuf:"fixed64,5,opt,name=bet,proto3" json:"bet,omitempty"`                          //下注
	GameBrand        string                 `protobuf:"bytes,6,opt,name=gameBrand,proto3" json:"gameBrand,omitempty"`                //游戏品牌
	GameId           string                 `protobuf:"bytes,7,opt,name=gameId,proto3" json:"gameId,omitempty"`                      //游戏id
	Win              float64                `protobuf:"fixed64,8,opt,name=win,proto3" json:"win,omitempty"`                          //赢钱
	BetTransactionId string                 `protobuf:"bytes,9,opt,name=betTransactionId,proto3" json:"betTransactionId,omitempty"`  // 下注交易id(必填，用来查关联下注记录)
	GameData         []byte                 `protobuf:"bytes,10,opt,name=game_data,json=gameData,proto3" json:"game_data,omitempty"` // 游戏数据
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WinRequest) Reset() {
	*x = WinRequest{}
	mi := &file_game_v1_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WinRequest) ProtoMessage() {}

func (x *WinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WinRequest.ProtoReflect.Descriptor instead.
func (*WinRequest) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{4}
}

func (x *WinRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *WinRequest) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *WinRequest) GetPreRoundId() string {
	if x != nil {
		return x.PreRoundId
	}
	return ""
}

func (x *WinRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *WinRequest) GetBet() float64 {
	if x != nil {
		return x.Bet
	}
	return 0
}

func (x *WinRequest) GetGameBrand() string {
	if x != nil {
		return x.GameBrand
	}
	return ""
}

func (x *WinRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *WinRequest) GetWin() float64 {
	if x != nil {
		return x.Win
	}
	return 0
}

func (x *WinRequest) GetBetTransactionId() string {
	if x != nil {
		return x.BetTransactionId
	}
	return ""
}

func (x *WinRequest) GetGameData() []byte {
	if x != nil {
		return x.GameData
	}
	return nil
}

type WinReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      string                 `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Balance       float64                `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	HashBalance   bool                   `protobuf:"varint,3,opt,name=hashBalance,proto3" json:"hashBalance,omitempty"` // 是否有余额，部分商家不返回余额
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WinReply) Reset() {
	*x = WinReply{}
	mi := &file_game_v1_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WinReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WinReply) ProtoMessage() {}

func (x *WinReply) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WinReply.ProtoReflect.Descriptor instead.
func (*WinReply) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{5}
}

func (x *WinReply) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *WinReply) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *WinReply) GetHashBalance() bool {
	if x != nil {
		return x.HashBalance
	}
	return false
}

type RefundRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PlayerId         string                 `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`     //账号id
	RoundId          string                 `protobuf:"bytes,2,opt,name=roundId,proto3" json:"roundId,omitempty"`       //游戏回合, 长度64以內。
	PreRoundId       string                 `protobuf:"bytes,3,opt,name=preRoundId,proto3" json:"preRoundId,omitempty"` //上一把游戏回合, 长度64以內。
	Currency         string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Bet              float64                `protobuf:"fixed64,5,opt,name=bet,proto3" json:"bet,omitempty"`                         //下注
	GameBrand        string                 `protobuf:"bytes,6,opt,name=gameBrand,proto3" json:"gameBrand,omitempty"`               //游戏品牌
	GameId           string                 `protobuf:"bytes,7,opt,name=gameId,proto3" json:"gameId,omitempty"`                     //游戏id
	BetTransactionId string                 `protobuf:"bytes,8,opt,name=betTransactionId,proto3" json:"betTransactionId,omitempty"` // 下注交易id(必填，用来查关联下注记录)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RefundRequest) Reset() {
	*x = RefundRequest{}
	mi := &file_game_v1_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundRequest) ProtoMessage() {}

func (x *RefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundRequest.ProtoReflect.Descriptor instead.
func (*RefundRequest) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{6}
}

func (x *RefundRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *RefundRequest) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *RefundRequest) GetPreRoundId() string {
	if x != nil {
		return x.PreRoundId
	}
	return ""
}

func (x *RefundRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *RefundRequest) GetBet() float64 {
	if x != nil {
		return x.Bet
	}
	return 0
}

func (x *RefundRequest) GetGameBrand() string {
	if x != nil {
		return x.GameBrand
	}
	return ""
}

func (x *RefundRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *RefundRequest) GetBetTransactionId() string {
	if x != nil {
		return x.BetTransactionId
	}
	return ""
}

type RefundReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`     // 状态：SETTLED-已经结算，CANCELED-已经取消, NOTFOUND-没有订单, REFUNDING-正在处理
	Balance       float64                `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"` // 玩家余额
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundReply) Reset() {
	*x = RefundReply{}
	mi := &file_game_v1_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundReply) ProtoMessage() {}

func (x *RefundReply) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundReply.ProtoReflect.Descriptor instead.
func (*RefundReply) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{7}
}

func (x *RefundReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RefundReply) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type PlayerRtpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"` //账号id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerRtpRequest) Reset() {
	*x = PlayerRtpRequest{}
	mi := &file_game_v1_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerRtpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerRtpRequest) ProtoMessage() {}

func (x *PlayerRtpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerRtpRequest.ProtoReflect.Descriptor instead.
func (*PlayerRtpRequest) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{8}
}

func (x *PlayerRtpRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type PlayerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rtp           string                 `protobuf:"bytes,1,opt,name=rtp,proto3" json:"rtp,omitempty"` // rtp档位
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerReply) Reset() {
	*x = PlayerReply{}
	mi := &file_game_v1_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerReply) ProtoMessage() {}

func (x *PlayerReply) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerReply.ProtoReflect.Descriptor instead.
func (*PlayerReply) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{9}
}

func (x *PlayerReply) GetRtp() string {
	if x != nil {
		return x.Rtp
	}
	return ""
}

type GameHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameBrand     string                 `protobuf:"bytes,1,opt,name=gameBrand,proto3" json:"gameBrand,omitempty"`                  //游戏品牌
	GameId        string                 `protobuf:"bytes,2,opt,name=gameId,proto3" json:"gameId,omitempty"`                        //游戏id
	PlayerId      string                 `protobuf:"bytes,3,opt,name=playerId,proto3" json:"playerId,omitempty"`                    //账号id
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"` // 分页
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	RoundId       string                 `protobuf:"bytes,6,opt,name=roundId,proto3" json:"roundId,omitempty"` //游戏回合, 长度64以內。
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameHistoryRequest) Reset() {
	*x = GameHistoryRequest{}
	mi := &file_game_v1_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameHistoryRequest) ProtoMessage() {}

func (x *GameHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameHistoryRequest.ProtoReflect.Descriptor instead.
func (*GameHistoryRequest) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{10}
}

func (x *GameHistoryRequest) GetGameBrand() string {
	if x != nil {
		return x.GameBrand
	}
	return ""
}

func (x *GameHistoryRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GameHistoryRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *GameHistoryRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *GameHistoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GameHistoryRequest) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

type GameHistoryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*GameHistory         `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`                            //记录列表
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"` //分页
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameHistoryReply) Reset() {
	*x = GameHistoryReply{}
	mi := &file_game_v1_game_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameHistoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameHistoryReply) ProtoMessage() {}

func (x *GameHistoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameHistoryReply.ProtoReflect.Descriptor instead.
func (*GameHistoryReply) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{11}
}

func (x *GameHistoryReply) GetList() []*GameHistory {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GameHistoryReply) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type GameHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`     //账号id
	RoundId       string                 `protobuf:"bytes,2,opt,name=roundId,proto3" json:"roundId,omitempty"`       //游戏回合, 长度64以內。
	PreRoundId    string                 `protobuf:"bytes,3,opt,name=preRoundId,proto3" json:"preRoundId,omitempty"` //上一把游戏回合, 长度64以內。
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Bet           float64                `protobuf:"fixed64,5,opt,name=bet,proto3" json:"bet,omitempty"`                          //下注
	GameBrand     string                 `protobuf:"bytes,6,opt,name=gameBrand,proto3" json:"gameBrand,omitempty"`                //游戏品牌
	GameId        string                 `protobuf:"bytes,7,opt,name=gameId,proto3" json:"gameId,omitempty"`                      //游戏id
	Rtp           string                 `protobuf:"bytes,8,opt,name=rtp,proto3" json:"rtp,omitempty"`                            //rtp档位
	Win           float64                `protobuf:"fixed64,9,opt,name=win,proto3" json:"win,omitempty"`                          //赢钱
	GameData      []byte                 `protobuf:"bytes,10,opt,name=game_data,json=gameData,proto3" json:"game_data,omitempty"` // 游戏数据
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	PostBalance   float64                `protobuf:"fixed64,12,opt,name=postBalance,proto3" json:"postBalance,omitempty"`
	RoundModel    string                 `protobuf:"bytes,13,opt,name=roundModel,proto3" json:"roundModel,omitempty"` // 模式:DEFAULT,EXTRA,BUY
	GameType      string                 `protobuf:"bytes,14,opt,name=gameType,proto3" json:"gameType,omitempty"`     // 游戏类型：slot
	TraceId       string                 `protobuf:"bytes,15,opt,name=traceId,proto3" json:"traceId,omitempty"`       //traceId,下注时游戏自己拼接参数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameHistory) Reset() {
	*x = GameHistory{}
	mi := &file_game_v1_game_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameHistory) ProtoMessage() {}

func (x *GameHistory) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameHistory.ProtoReflect.Descriptor instead.
func (*GameHistory) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{12}
}

func (x *GameHistory) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *GameHistory) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *GameHistory) GetPreRoundId() string {
	if x != nil {
		return x.PreRoundId
	}
	return ""
}

func (x *GameHistory) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GameHistory) GetBet() float64 {
	if x != nil {
		return x.Bet
	}
	return 0
}

func (x *GameHistory) GetGameBrand() string {
	if x != nil {
		return x.GameBrand
	}
	return ""
}

func (x *GameHistory) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GameHistory) GetRtp() string {
	if x != nil {
		return x.Rtp
	}
	return ""
}

func (x *GameHistory) GetWin() float64 {
	if x != nil {
		return x.Win
	}
	return 0
}

func (x *GameHistory) GetGameData() []byte {
	if x != nil {
		return x.GameData
	}
	return nil
}

func (x *GameHistory) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GameHistory) GetPostBalance() float64 {
	if x != nil {
		return x.PostBalance
	}
	return 0
}

func (x *GameHistory) GetRoundModel() string {
	if x != nil {
		return x.RoundModel
	}
	return ""
}

func (x *GameHistory) GetGameType() string {
	if x != nil {
		return x.GameType
	}
	return ""
}

func (x *GameHistory) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type JiliGameHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`            //appid
	PlayerId      string                 `protobuf:"bytes,2,opt,name=playerId,proto3" json:"playerId,omitempty"`      //账号id
	GameName      string                 `protobuf:"bytes,3,opt,name=gameName,proto3" json:"gameName,omitempty"`      //游戏名称
	StartIndex    int32                  `protobuf:"varint,4,opt,name=startIndex,proto3" json:"startIndex,omitempty"` // 分页
	EndIndex      int32                  `protobuf:"varint,5,opt,name=endIndex,proto3" json:"endIndex,omitempty"`     // 分页
	RoundId       string                 `protobuf:"bytes,6,opt,name=roundId,proto3" json:"roundId,omitempty"`        //游戏回合, 长度64以內。
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=endTime,proto3" json:"endTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JiliGameHistoryRequest) Reset() {
	*x = JiliGameHistoryRequest{}
	mi := &file_game_v1_game_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JiliGameHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JiliGameHistoryRequest) ProtoMessage() {}

func (x *JiliGameHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JiliGameHistoryRequest.ProtoReflect.Descriptor instead.
func (*JiliGameHistoryRequest) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{13}
}

func (x *JiliGameHistoryRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *JiliGameHistoryRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *JiliGameHistoryRequest) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

func (x *JiliGameHistoryRequest) GetStartIndex() int32 {
	if x != nil {
		return x.StartIndex
	}
	return 0
}

func (x *JiliGameHistoryRequest) GetEndIndex() int32 {
	if x != nil {
		return x.EndIndex
	}
	return 0
}

func (x *JiliGameHistoryRequest) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *JiliGameHistoryRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *JiliGameHistoryRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type JiliGameHistoryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*GameHistory         `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"` //记录列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JiliGameHistoryReply) Reset() {
	*x = JiliGameHistoryReply{}
	mi := &file_game_v1_game_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JiliGameHistoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JiliGameHistoryReply) ProtoMessage() {}

func (x *JiliGameHistoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JiliGameHistoryReply.ProtoReflect.Descriptor instead.
func (*JiliGameHistoryReply) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{14}
}

func (x *JiliGameHistoryReply) GetList() []*GameHistory {
	if x != nil {
		return x.List
	}
	return nil
}

type AppGameListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`         //appid
	GameBrand     string                 `protobuf:"bytes,2,opt,name=gameBrand,proto3" json:"gameBrand,omitempty"` //游戏品牌
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppGameListRequest) Reset() {
	*x = AppGameListRequest{}
	mi := &file_game_v1_game_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppGameListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppGameListRequest) ProtoMessage() {}

func (x *AppGameListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppGameListRequest.ProtoReflect.Descriptor instead.
func (*AppGameListRequest) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{15}
}

func (x *AppGameListRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *AppGameListRequest) GetGameBrand() string {
	if x != nil {
		return x.GameBrand
	}
	return ""
}

type AppGameListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*AppGameList         `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"` //记录列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppGameListReply) Reset() {
	*x = AppGameListReply{}
	mi := &file_game_v1_game_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppGameListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppGameListReply) ProtoMessage() {}

func (x *AppGameListReply) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppGameListReply.ProtoReflect.Descriptor instead.
func (*AppGameListReply) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{16}
}

func (x *AppGameListReply) GetList() []*AppGameList {
	if x != nil {
		return x.List
	}
	return nil
}

type AppGameList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=gameId,proto3" json:"gameId,omitempty"`             //游戏ID
	GameName      string                 `protobuf:"bytes,2,opt,name=gameName,proto3" json:"gameName,omitempty"`         //游戏id
	GameFullName  string                 `protobuf:"bytes,3,opt,name=gameFullName,proto3" json:"gameFullName,omitempty"` //游戏全名称
	GameType      string                 `protobuf:"bytes,4,opt,name=gameType,proto3" json:"gameType,omitempty"`         //游戏类型(slot)
	GameBrand     string                 `protobuf:"bytes,5,opt,name=gameBrand,proto3" json:"gameBrand,omitempty"`       //游戏厂商
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppGameList) Reset() {
	*x = AppGameList{}
	mi := &file_game_v1_game_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppGameList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppGameList) ProtoMessage() {}

func (x *AppGameList) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppGameList.ProtoReflect.Descriptor instead.
func (*AppGameList) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{17}
}

func (x *AppGameList) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *AppGameList) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

func (x *AppGameList) GetGameFullName() string {
	if x != nil {
		return x.GameFullName
	}
	return ""
}

func (x *AppGameList) GetGameType() string {
	if x != nil {
		return x.GameType
	}
	return ""
}

func (x *AppGameList) GetGameBrand() string {
	if x != nil {
		return x.GameBrand
	}
	return ""
}

var File_game_v1_game_proto protoreflect.FileDescriptor

const file_game_v1_game_proto_rawDesc = "" +
	"\n" +
	"\x12game/v1/game.proto\x12\agame.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"H\n" +
	"\x0eBalanceRequest\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\tR\bplayerId\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"D\n" +
	"\fBalanceReply\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\tR\bcurrency\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x01R\abalance\"\x9a\x03\n" +
	"\n" +
	"BetRequest\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\tR\bplayerId\x12\x18\n" +
	"\aroundId\x18\x02 \x01(\tR\aroundId\x12\x1e\n" +
	"\n" +
	"preRoundId\x18\x03 \x01(\tR\n" +
	"preRoundId\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x10\n" +
	"\x03bet\x18\x05 \x01(\x01R\x03bet\x12\x1c\n" +
	"\tgameBrand\x18\x06 \x01(\tR\tgameBrand\x12\x16\n" +
	"\x06gameId\x18\a \x01(\tR\x06gameId\x12\x10\n" +
	"\x03rtp\x18\b \x01(\tR\x03rtp\x12\x1f\n" +
	"\vround_model\x18\t \x01(\tR\n" +
	"roundModel\x12\x1b\n" +
	"\tgame_data\x18\n" +
	" \x01(\fR\bgameData\x12\x18\n" +
	"\atraceId\x18\v \x01(\tR\atraceId\x12$\n" +
	"\rtransactionId\x18\f \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06isFree\x18\r \x01(\bR\x06isFree\x12*\n" +
	"\x10preTransactionId\x18\x0e \x01(\tR\x10preTransactionId\"@\n" +
	"\bBetReply\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\tR\bcurrency\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x01R\abalance\"\xa1\x02\n" +
	"\n" +
	"WinRequest\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\tR\bplayerId\x12\x18\n" +
	"\aroundId\x18\x02 \x01(\tR\aroundId\x12\x1e\n" +
	"\n" +
	"preRoundId\x18\x03 \x01(\tR\n" +
	"preRoundId\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x10\n" +
	"\x03bet\x18\x05 \x01(\x01R\x03bet\x12\x1c\n" +
	"\tgameBrand\x18\x06 \x01(\tR\tgameBrand\x12\x16\n" +
	"\x06gameId\x18\a \x01(\tR\x06gameId\x12\x10\n" +
	"\x03win\x18\b \x01(\x01R\x03win\x12*\n" +
	"\x10betTransactionId\x18\t \x01(\tR\x10betTransactionId\x12\x1b\n" +
	"\tgame_data\x18\n" +
	" \x01(\fR\bgameData\"b\n" +
	"\bWinReply\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\tR\bcurrency\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x01R\abalance\x12 \n" +
	"\vhashBalance\x18\x03 \x01(\bR\vhashBalance\"\xf5\x01\n" +
	"\rRefundRequest\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\tR\bplayerId\x12\x18\n" +
	"\aroundId\x18\x02 \x01(\tR\aroundId\x12\x1e\n" +
	"\n" +
	"preRoundId\x18\x03 \x01(\tR\n" +
	"preRoundId\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x10\n" +
	"\x03bet\x18\x05 \x01(\x01R\x03bet\x12\x1c\n" +
	"\tgameBrand\x18\x06 \x01(\tR\tgameBrand\x12\x16\n" +
	"\x06gameId\x18\a \x01(\tR\x06gameId\x12*\n" +
	"\x10betTransactionId\x18\b \x01(\tR\x10betTransactionId\"?\n" +
	"\vRefundReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x01R\abalance\".\n" +
	"\x10PlayerRtpRequest\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\tR\bplayerId\"\x1f\n" +
	"\vPlayerReply\x12\x10\n" +
	"\x03rtp\x18\x01 \x01(\tR\x03rtp\"\xbc\x01\n" +
	"\x12GameHistoryRequest\x12\x1c\n" +
	"\tgameBrand\x18\x01 \x01(\tR\tgameBrand\x12\x16\n" +
	"\x06gameId\x18\x02 \x01(\tR\x06gameId\x12\x1a\n" +
	"\bplayerId\x18\x03 \x01(\tR\bplayerId\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\x12\x18\n" +
	"\aroundId\x18\x06 \x01(\tR\aroundId\"[\n" +
	"\x10GameHistoryReply\x12(\n" +
	"\x04list\x18\x01 \x03(\v2\x14.game.v1.GameHistoryR\x04list\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"\xbb\x03\n" +
	"\vGameHistory\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\tR\bplayerId\x12\x18\n" +
	"\aroundId\x18\x02 \x01(\tR\aroundId\x12\x1e\n" +
	"\n" +
	"preRoundId\x18\x03 \x01(\tR\n" +
	"preRoundId\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x10\n" +
	"\x03bet\x18\x05 \x01(\x01R\x03bet\x12\x1c\n" +
	"\tgameBrand\x18\x06 \x01(\tR\tgameBrand\x12\x16\n" +
	"\x06gameId\x18\a \x01(\tR\x06gameId\x12\x10\n" +
	"\x03rtp\x18\b \x01(\tR\x03rtp\x12\x10\n" +
	"\x03win\x18\t \x01(\x01R\x03win\x12\x1b\n" +
	"\tgame_data\x18\n" +
	" \x01(\fR\bgameData\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12 \n" +
	"\vpostBalance\x18\f \x01(\x01R\vpostBalance\x12\x1e\n" +
	"\n" +
	"roundModel\x18\r \x01(\tR\n" +
	"roundModel\x12\x1a\n" +
	"\bgameType\x18\x0e \x01(\tR\bgameType\x12\x18\n" +
	"\atraceId\x18\x0f \x01(\tR\atraceId\"\xac\x02\n" +
	"\x16JiliGameHistoryRequest\x12\x14\n" +
	"\x05appId\x18\x01 \x01(\tR\x05appId\x12\x1a\n" +
	"\bplayerId\x18\x02 \x01(\tR\bplayerId\x12\x1a\n" +
	"\bgameName\x18\x03 \x01(\tR\bgameName\x12\x1e\n" +
	"\n" +
	"startIndex\x18\x04 \x01(\x05R\n" +
	"startIndex\x12\x1a\n" +
	"\bendIndex\x18\x05 \x01(\x05R\bendIndex\x12\x18\n" +
	"\aroundId\x18\x06 \x01(\tR\aroundId\x128\n" +
	"\tstartTime\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x124\n" +
	"\aendTime\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"@\n" +
	"\x14JiliGameHistoryReply\x12(\n" +
	"\x04list\x18\x01 \x03(\v2\x14.game.v1.GameHistoryR\x04list\"H\n" +
	"\x12AppGameListRequest\x12\x14\n" +
	"\x05appId\x18\x01 \x01(\tR\x05appId\x12\x1c\n" +
	"\tgameBrand\x18\x02 \x01(\tR\tgameBrand\"<\n" +
	"\x10AppGameListReply\x12(\n" +
	"\x04list\x18\x01 \x03(\v2\x14.game.v1.AppGameListR\x04list\"\x9f\x01\n" +
	"\vAppGameList\x12\x16\n" +
	"\x06gameId\x18\x01 \x01(\tR\x06gameId\x12\x1a\n" +
	"\bgameName\x18\x02 \x01(\tR\bgameName\x12\"\n" +
	"\fgameFullName\x18\x03 \x01(\tR\fgameFullName\x12\x1a\n" +
	"\bgameType\x18\x04 \x01(\tR\bgameType\x12\x1c\n" +
	"\tgameBrand\x18\x05 \x01(\tR\tgameBrand2\xbf\x03\n" +
	"\aGameApi\x129\n" +
	"\aBalance\x12\x17.game.v1.BalanceRequest\x1a\x15.game.v1.BalanceReply\x12-\n" +
	"\x03Bet\x12\x13.game.v1.BetRequest\x1a\x11.game.v1.BetReply\x12-\n" +
	"\x03Win\x12\x13.game.v1.WinRequest\x1a\x11.game.v1.WinReply\x126\n" +
	"\x06Refund\x12\x16.game.v1.RefundRequest\x1a\x14.game.v1.RefundReply\x12I\n" +
	"\x0fGameHistoryList\x12\x1b.game.v1.GameHistoryRequest\x1a\x19.game.v1.GameHistoryReply\x12Q\n" +
	"\x0fJiliGameHistory\x12\x1f.game.v1.JiliGameHistoryRequest\x1a\x1d.game.v1.JiliGameHistoryReply\x12E\n" +
	"\vAppGameList\x12\x1b.game.v1.AppGameListRequest\x1a\x19.game.v1.AppGameListReplyBU\n" +
	"\x16dev.kratos.api.game.v1B\vGameProtoV1P\x01Z,github.com/zuodazuoqianggame/game_common/api/game/v1;v1b\x06proto3"

var (
	file_game_v1_game_proto_rawDescOnce sync.Once
	file_game_v1_game_proto_rawDescData []byte
)

func file_game_v1_game_proto_rawDescGZIP() []byte {
	file_game_v1_game_proto_rawDescOnce.Do(func() {
		file_game_v1_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_v1_game_proto_rawDesc), len(file_game_v1_game_proto_rawDesc)))
	})
	return file_game_v1_game_proto_rawDescData
}

var file_game_v1_game_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_game_v1_game_proto_goTypes = []any{
	(*BalanceRequest)(nil),         // 0: game.v1.BalanceRequest
	(*BalanceReply)(nil),           // 1: game.v1.BalanceReply
	(*BetRequest)(nil),             // 2: game.v1.BetRequest
	(*BetReply)(nil),               // 3: game.v1.BetReply
	(*WinRequest)(nil),             // 4: game.v1.WinRequest
	(*WinReply)(nil),               // 5: game.v1.WinReply
	(*RefundRequest)(nil),          // 6: game.v1.RefundRequest
	(*RefundReply)(nil),            // 7: game.v1.RefundReply
	(*PlayerRtpRequest)(nil),       // 8: game.v1.PlayerRtpRequest
	(*PlayerReply)(nil),            // 9: game.v1.PlayerReply
	(*GameHistoryRequest)(nil),     // 10: game.v1.GameHistoryRequest
	(*GameHistoryReply)(nil),       // 11: game.v1.GameHistoryReply
	(*GameHistory)(nil),            // 12: game.v1.GameHistory
	(*JiliGameHistoryRequest)(nil), // 13: game.v1.JiliGameHistoryRequest
	(*JiliGameHistoryReply)(nil),   // 14: game.v1.JiliGameHistoryReply
	(*AppGameListRequest)(nil),     // 15: game.v1.AppGameListRequest
	(*AppGameListReply)(nil),       // 16: game.v1.AppGameListReply
	(*AppGameList)(nil),            // 17: game.v1.AppGameList
	(*timestamppb.Timestamp)(nil),  // 18: google.protobuf.Timestamp
}
var file_game_v1_game_proto_depIdxs = []int32{
	12, // 0: game.v1.GameHistoryReply.list:type_name -> game.v1.GameHistory
	18, // 1: game.v1.GameHistory.created_at:type_name -> google.protobuf.Timestamp
	18, // 2: game.v1.JiliGameHistoryRequest.startTime:type_name -> google.protobuf.Timestamp
	18, // 3: game.v1.JiliGameHistoryRequest.endTime:type_name -> google.protobuf.Timestamp
	12, // 4: game.v1.JiliGameHistoryReply.list:type_name -> game.v1.GameHistory
	17, // 5: game.v1.AppGameListReply.list:type_name -> game.v1.AppGameList
	0,  // 6: game.v1.GameApi.Balance:input_type -> game.v1.BalanceRequest
	2,  // 7: game.v1.GameApi.Bet:input_type -> game.v1.BetRequest
	4,  // 8: game.v1.GameApi.Win:input_type -> game.v1.WinRequest
	6,  // 9: game.v1.GameApi.Refund:input_type -> game.v1.RefundRequest
	10, // 10: game.v1.GameApi.GameHistoryList:input_type -> game.v1.GameHistoryRequest
	13, // 11: game.v1.GameApi.JiliGameHistory:input_type -> game.v1.JiliGameHistoryRequest
	15, // 12: game.v1.GameApi.AppGameList:input_type -> game.v1.AppGameListRequest
	1,  // 13: game.v1.GameApi.Balance:output_type -> game.v1.BalanceReply
	3,  // 14: game.v1.GameApi.Bet:output_type -> game.v1.BetReply
	5,  // 15: game.v1.GameApi.Win:output_type -> game.v1.WinReply
	7,  // 16: game.v1.GameApi.Refund:output_type -> game.v1.RefundReply
	11, // 17: game.v1.GameApi.GameHistoryList:output_type -> game.v1.GameHistoryReply
	14, // 18: game.v1.GameApi.JiliGameHistory:output_type -> game.v1.JiliGameHistoryReply
	16, // 19: game.v1.GameApi.AppGameList:output_type -> game.v1.AppGameListReply
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_game_v1_game_proto_init() }
func file_game_v1_game_proto_init() {
	if File_game_v1_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_v1_game_proto_rawDesc), len(file_game_v1_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_v1_game_proto_goTypes,
		DependencyIndexes: file_game_v1_game_proto_depIdxs,
		MessageInfos:      file_game_v1_game_proto_msgTypes,
	}.Build()
	File_game_v1_game_proto = out.File
	file_game_v1_game_proto_goTypes = nil
	file_game_v1_game_proto_depIdxs = nil
}
